'use client'

import {useMemo,useState} from 'react'
import {GraduationCap,ShieldCheck} from 'lucide-react'
import {PageHeader} from '@/components/shell/page-header'
import {Panel,PanelBody,PanelHeader} from '@/components/ui/panel'
import {RuntimeUnavailable} from '@/components/runtime-state'
import {StatusBadge,Tag} from '@/components/ui/status-badge'
import {useWpeRuntime,type RuntimeCollectionState,type RuntimeTeacherLesson} from '@/components/runtime-bridge'
import {useI18n} from '@/lib/i18n/context'

type Tab='current'|'archive'|'recommendations'|'corrections'|'outcomes'|'notifications'

type Copy={
 title:string;description:string;authorityTitle:string;authorityBody:string;current:string;archive:string;recommendations:string;corrections:string;outcomes:string;notifications:string;
 currentTitle:string;archiveTitle:string;recommendationsTitle:string;correctionsTitle:string;outcomesTitle:string;notificationsTitle:string;
 emptyLessons:string;emptyRecommendations:string;emptyCorrections:string;emptyOutcomes:string;unavailable:string;stale:string;error:string;
 scheduled:string;generated:string;level:string;language:string;timezone:string;persona:string;execution:string;evidence:string;issued:string;expires:string;version:string;
 confirmation:string;invalidation:string;risks:string;benchmark:string;horizon:string;instrumentReturn:string;relativeReturn:string;mae:string;process:string;evaluated:string;
}

const copyByLocale:Record<string,Copy>={
 en_US:{title:'Financial Teacher',description:'Evidence-bound lessons, research candidates, corrections and point-in-time outcomes',authorityTitle:'No trading authority',authorityBody:'Teacher can explain host-provided facts and research candidates, but cannot place orders, approve trades, change strategies, or bypass the Risk Gate.',current:'Latest',archive:'Archive',recommendations:'Research candidates',corrections:'Corrections',outcomes:'Outcomes',notifications:'Notifications',currentTitle:'Latest lesson',archiveTitle:'Lesson archive',recommendationsTitle:'Conditional research candidates',correctionsTitle:'Append-only corrections',outcomesTitle:'Point-in-time outcome review',notificationsTitle:'Teacher notification state',emptyLessons:'No Teacher lessons are available.',emptyRecommendations:'No research candidates are available.',emptyCorrections:'No corrections are available.',emptyOutcomes:'No outcome reviews are available.',unavailable:'This Teacher evidence is not connected.',stale:'Teacher evidence is stale and withheld.',error:'Teacher evidence could not be read.',scheduled:'Scheduled',generated:'Generated',level:'Teaching level',language:'Language',timezone:'Time zone',persona:'Persona version',execution:'Execution authority',evidence:'Evidence hashes',issued:'Issued',expires:'Expires',version:'Version',confirmation:'Confirmation conditions',invalidation:'Invalidation conditions',risks:'Material risks',benchmark:'Benchmark',horizon:'Horizon',instrumentReturn:'Instrument return',relativeReturn:'Relative return',mae:'Maximum adverse excursion',process:'Process state',evaluated:'Evaluated'},
 zh_CN:{title:'金融教师',description:'基于证据的课程、研究候选、追加式修正与点时结果复盘',authorityTitle:'没有交易权限',authorityBody:'教师只能解释宿主提供的事实和研究候选，不能下单、批准交易、修改策略或绕过 Risk Gate。',current:'最近课程',archive:'课程档案',recommendations:'研究候选',corrections:'修正记录',outcomes:'结果复盘',notifications:'通知状态',currentTitle:'最近生成课程',archiveTitle:'课程档案',recommendationsTitle:'条件性研究候选',correctionsTitle:'追加式修正记录',outcomesTitle:'点时结果复盘',notificationsTitle:'教师通知状态',emptyLessons:'当前没有可用课程。',emptyRecommendations:'当前没有研究候选。',emptyCorrections:'当前没有课程修正。',emptyOutcomes:'当前没有结果复盘记录。',unavailable:'教师证据尚未接入。',stale:'教师证据已过期，旧数据已隐藏。',error:'教师证据读取失败。',scheduled:'计划时间',generated:'生成时间',level:'教学等级',language:'语言',timezone:'时区',persona:'人设版本',execution:'执行权限',evidence:'证据哈希',issued:'发布',expires:'到期',version:'版本',confirmation:'确认条件',invalidation:'失效条件',risks:'主要风险',benchmark:'基准',horizon:'周期',instrumentReturn:'标的收益',relativeReturn:'相对收益',mae:'最大不利波动',process:'流程状态',evaluated:'评价时间'},
 zh_TW:{title:'金融教師',description:'以證據為基礎的課程、研究候選、追加式修正與點時結果複盤',authorityTitle:'沒有交易權限',authorityBody:'教師只能解釋宿主提供的事實與研究候選，不能下單、核准交易、修改策略或繞過 Risk Gate。',current:'最近課程',archive:'課程檔案',recommendations:'研究候選',corrections:'修正記錄',outcomes:'結果複盤',notifications:'通知狀態',currentTitle:'最近生成課程',archiveTitle:'課程檔案',recommendationsTitle:'條件式研究候選',correctionsTitle:'追加式修正記錄',outcomesTitle:'點時結果複盤',notificationsTitle:'教師通知狀態',emptyLessons:'目前沒有可用課程。',emptyRecommendations:'目前沒有研究候選。',emptyCorrections:'目前沒有課程修正。',emptyOutcomes:'目前沒有結果複盤記錄。',unavailable:'教師證據尚未接入。',stale:'教師證據已過期，舊資料已隱藏。',error:'教師證據讀取失敗。',scheduled:'計畫時間',generated:'生成時間',level:'教學等級',language:'語言',timezone:'時區',persona:'人設版本',execution:'執行權限',evidence:'證據雜湊',issued:'發布',expires:'到期',version:'版本',confirmation:'確認條件',invalidation:'失效條件',risks:'主要風險',benchmark:'基準',horizon:'週期',instrumentReturn:'標的收益',relativeReturn:'相對收益',mae:'最大不利波動',process:'流程狀態',evaluated:'評價時間'},
 ja_JP:{title:'金融ティーチャー',description:'証拠に基づくレッスン、研究候補、追記型訂正、時点評価',authorityTitle:'取引権限なし',authorityBody:'Teacher はホスト提供の事実と研究候補を説明できますが、注文、取引承認、戦略変更、Risk Gate の回避はできません。',current:'最新',archive:'アーカイブ',recommendations:'研究候補',corrections:'訂正',outcomes:'結果',notifications:'通知',currentTitle:'最新レッスン',archiveTitle:'レッスンアーカイブ',recommendationsTitle:'条件付き研究候補',correctionsTitle:'追記型訂正',outcomesTitle:'時点結果レビュー',notificationsTitle:'Teacher 通知状態',emptyLessons:'利用可能なレッスンはありません。',emptyRecommendations:'研究候補はありません。',emptyCorrections:'訂正はありません。',emptyOutcomes:'結果レビューはありません。',unavailable:'Teacher 証拠は未接続です。',stale:'Teacher 証拠は期限切れのため非表示です。',error:'Teacher 証拠を読み取れません。',scheduled:'予定',generated:'生成',level:'教育レベル',language:'言語',timezone:'タイムゾーン',persona:'ペルソナ版',execution:'実行権限',evidence:'証拠ハッシュ',issued:'発行',expires:'期限',version:'バージョン',confirmation:'確認条件',invalidation:'無効化条件',risks:'主要リスク',benchmark:'ベンチマーク',horizon:'期間',instrumentReturn:'対象リターン',relativeReturn:'相対リターン',mae:'最大逆行幅',process:'プロセス状態',evaluated:'評価時刻'},
 ko_KR:{title:'금융 교사',description:'증거 기반 수업, 연구 후보, 추가형 수정 및 시점 결과 평가',authorityTitle:'거래 권한 없음',authorityBody:'Teacher는 호스트가 제공한 사실과 연구 후보를 설명할 수 있지만 주문, 거래 승인, 전략 변경 또는 Risk Gate 우회는 할 수 없습니다.',current:'최근',archive:'보관함',recommendations:'연구 후보',corrections:'수정',outcomes:'결과',notifications:'알림',currentTitle:'최근 수업',archiveTitle:'수업 보관함',recommendationsTitle:'조건부 연구 후보',correctionsTitle:'추가형 수정 기록',outcomesTitle:'시점 결과 평가',notificationsTitle:'Teacher 알림 상태',emptyLessons:'사용 가능한 수업이 없습니다.',emptyRecommendations:'연구 후보가 없습니다.',emptyCorrections:'수정 기록이 없습니다.',emptyOutcomes:'결과 평가가 없습니다.',unavailable:'Teacher 증거가 연결되지 않았습니다.',stale:'Teacher 증거가 만료되어 숨겼습니다.',error:'Teacher 증거를 읽을 수 없습니다.',scheduled:'예정',generated:'생성',level:'교육 수준',language:'언어',timezone:'시간대',persona:'페르소나 버전',execution:'실행 권한',evidence:'증거 해시',issued:'발행',expires:'만료',version:'버전',confirmation:'확인 조건',invalidation:'무효화 조건',risks:'주요 위험',benchmark:'벤치마크',horizon:'기간',instrumentReturn:'대상 수익률',relativeReturn:'상대 수익률',mae:'최대 불리 변동',process:'프로세스 상태',evaluated:'평가 시간'},
 it_IT:{title:'Docente finanziario',description:'Lezioni basate su evidenze, candidati di ricerca, correzioni append-only e risultati point-in-time',authorityTitle:'Nessuna autorità di trading',authorityBody:'Il Teacher può spiegare fatti forniti dall’host e candidati di ricerca, ma non può inviare ordini, approvare operazioni, modificare strategie o aggirare il Risk Gate.',current:'Più recente',archive:'Archivio',recommendations:'Candidati di ricerca',corrections:'Correzioni',outcomes:'Risultati',notifications:'Notifiche',currentTitle:'Lezione più recente',archiveTitle:'Archivio lezioni',recommendationsTitle:'Candidati di ricerca condizionali',correctionsTitle:'Correzioni append-only',outcomesTitle:'Valutazione point-in-time',notificationsTitle:'Stato notifiche Teacher',emptyLessons:'Nessuna lezione disponibile.',emptyRecommendations:'Nessun candidato di ricerca disponibile.',emptyCorrections:'Nessuna correzione disponibile.',emptyOutcomes:'Nessuna valutazione disponibile.',unavailable:'Le evidenze Teacher non sono collegate.',stale:'Le evidenze Teacher sono scadute e vengono nascoste.',error:'Impossibile leggere le evidenze Teacher.',scheduled:'Pianificata',generated:'Generata',level:'Livello didattico',language:'Lingua',timezone:'Fuso orario',persona:'Versione persona',execution:'Autorità di esecuzione',evidence:'Hash delle evidenze',issued:'Pubblicata',expires:'Scadenza',version:'Versione',confirmation:'Condizioni di conferma',invalidation:'Condizioni di invalidazione',risks:'Rischi principali',benchmark:'Benchmark',horizon:'Orizzonte',instrumentReturn:'Rendimento strumento',relativeReturn:'Rendimento relativo',mae:'Escursione avversa massima',process:'Stato processo',evaluated:'Valutata'},
}

function collectionMessage(state:RuntimeCollectionState|undefined,copy:Copy){if(state==='stale')return copy.stale;if(state==='error')return copy.error;return copy.unavailable}
function pct(value:number,formatNumber:(value:number,options?:Intl.NumberFormatOptions)=>string){return `${formatNumber(value,{maximumFractionDigits:2})}%`}
function Hashes({values}:{values:string[]}){return <div className="flex flex-wrap gap-1.5">{values.map(value=><code key={value} className="max-w-full break-all rounded bg-muted px-1.5 py-1 text-[10px] text-muted-foreground">{value}</code>)}</div>}
function Empty({text}:{text:string}){return <div className="py-8 text-center text-sm text-muted-foreground">{text}</div>}

function Lesson({lesson,copy,formatDate}:{lesson:RuntimeTeacherLesson;copy:Copy;formatDate:(value:string)=>string}){
 return <article className="space-y-4 rounded-lg border border-border bg-muted/20 p-4">
  <div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-2"><Tag>{lesson.kind}</Tag><Tag>{lesson.language}</Tag></div><StatusBadge token="muted" label="executionAuthority=false"/></div>
  <dl className="grid gap-3 text-xs sm:grid-cols-2 lg:grid-cols-4"><Meta label={copy.scheduled} value={formatDate(lesson.scheduledForUtc)}/><Meta label={copy.generated} value={formatDate(lesson.generatedAtUtc)}/><Meta label={copy.level} value={lesson.teachingLevel}/><Meta label={copy.timezone} value={lesson.timeZoneId}/><Meta label={copy.persona} value={lesson.personaVersion}/><Meta label={copy.execution} value="false"/></dl>
  <div className="space-y-3">{lesson.blocks.map(block=><section key={block.blockId} className="rounded border border-border bg-card/60 p-3"><div className="mb-2 flex flex-wrap items-center gap-2"><Tag>{block.kind}</Tag><h3 className="text-sm font-medium">{block.heading}</h3></div><p className="whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{block.content}</p>{block.evidenceHashes.length>0&&<details className="mt-3"><summary className="cursor-pointer text-xs text-muted-foreground">{copy.evidence}</summary><div className="mt-2"><Hashes values={block.evidenceHashes}/></div></details>}</section>)}</div>
 </article>
}
function Meta({label,value}:{label:string;value:string|number}){return <div><dt className="text-[10px] uppercase text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-foreground">{value}</dd></div>}
function List({title,items}:{title:string;items:string[]}){return <div><h4 className="mb-1 text-[10px] uppercase text-muted-foreground">{title}</h4>{items.length?<ul className="space-y-1 text-xs text-foreground">{items.map(item=><li key={item} className="break-words">• {item}</li>)}</ul>:<span className="text-xs text-muted-foreground">—</span>}</div>}

export default function TeacherPage(){
 const runtime=useWpeRuntime(),{locale,formatDate,formatNumber}=useI18n(),copy=copyByLocale[locale]??copyByLocale.en_US
 const[tab,setTab]=useState<Tab>('current')
 const lessons=useMemo(()=>[...(runtime.teacherLessons??[])].sort((a,b)=>b.generatedAtUtc.localeCompare(a.generatedAtUtc)),[runtime.teacherLessons])
 const recommendations=useMemo(()=>[...(runtime.teacherRecommendations??[])].sort((a,b)=>b.issuedAtUtc.localeCompare(a.issuedAtUtc)),[runtime.teacherRecommendations])
 const corrections=useMemo(()=>[...(runtime.teacherCorrections??[])].sort((a,b)=>b.issuedAtUtc.localeCompare(a.issuedAtUtc)),[runtime.teacherCorrections])
 const outcomes=useMemo(()=>[...(runtime.teacherOutcomes??[])].sort((a,b)=>b.evaluatedAtUtc.localeCompare(a.evaluatedAtUtc)),[runtime.teacherOutcomes])
 if(!runtime.runtimeFresh)return <RuntimeUnavailable stale={Boolean(runtime.lastUpdated)} subject={copy.title}/>
 const tabs:Array<[Tab,string]>=[['current',copy.current],['archive',copy.archive],['recommendations',copy.recommendations],['corrections',copy.corrections],['outcomes',copy.outcomes],['notifications',copy.notifications]]
 return <div className="flex flex-col gap-6 p-6">
  <PageHeader title={copy.title} description={copy.description}/>
  <Panel><PanelBody className="flex items-start gap-3"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-info"/><div><h2 className="text-sm font-medium">{copy.authorityTitle}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{copy.authorityBody}</p></div></PanelBody></Panel>
  <div className="flex flex-wrap gap-2">{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>setTab(id)} className={`rounded-md border px-3 py-1.5 text-xs ${tab===id?'border-info/40 bg-info/10 text-info':'border-border text-muted-foreground hover:bg-accent'}`}>{label}</button>)}</div>
  {tab==='current'&&<Panel><PanelHeader icon={<GraduationCap className="size-4"/>} title={copy.currentTitle}/><PanelBody>{runtime.collectionStates?.teacherLessons!=='available'?<Empty text={collectionMessage(runtime.collectionStates?.teacherLessons,copy)}/>:lessons[0]?<Lesson lesson={lessons[0]} copy={copy} formatDate={formatDate}/>:<Empty text={copy.emptyLessons}/>}</PanelBody></Panel>}
  {tab==='archive'&&<Panel><PanelHeader title={copy.archiveTitle}/><PanelBody className="space-y-3">{runtime.collectionStates?.teacherLessons!=='available'?<Empty text={collectionMessage(runtime.collectionStates?.teacherLessons,copy)}/>:lessons.length?lessons.map(lesson=><details key={lesson.lessonId} className="rounded-lg border border-border"><summary className="cursor-pointer px-4 py-3 text-sm"><span className="font-medium">{lesson.kind}</span><span className="ml-2 text-xs text-muted-foreground">{formatDate(lesson.generatedAtUtc)}</span></summary><div className="border-t border-border p-3"><Lesson lesson={lesson} copy={copy} formatDate={formatDate}/></div></details>):<Empty text={copy.emptyLessons}/>}</PanelBody></Panel>}
  {tab==='recommendations'&&<Panel><PanelHeader title={copy.recommendationsTitle}/><PanelBody className="space-y-3">{runtime.collectionStates?.teacherRecommendations!=='available'?<Empty text={collectionMessage(runtime.collectionStates?.teacherRecommendations,copy)}/>:recommendations.length?recommendations.map(item=><article key={`${item.recommendationId}-${item.version}`} className="space-y-3 rounded-lg border border-border bg-muted/20 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-medium">{item.instrument}</h3><p className="text-xs text-muted-foreground">{item.assetClass} · {item.horizon}</p></div><div className="flex gap-2"><StatusBadge token={item.state==='avoid_high_risk'?'danger':item.state==='expired'?'muted':'info'} label={item.state}/><StatusBadge token="muted" label="executionAuthority=false"/></div></div><p className="text-sm leading-6 text-muted-foreground">{item.thesis}</p><dl className="grid gap-3 text-xs sm:grid-cols-3"><Meta label={copy.issued} value={formatDate(item.issuedAtUtc)}/><Meta label={copy.expires} value={formatDate(item.expiresAtUtc)}/><Meta label={copy.version} value={item.version}/></dl><div className="grid gap-4 lg:grid-cols-3"><List title={copy.confirmation} items={item.confirmationConditions}/><List title={copy.invalidation} items={item.invalidationConditions}/><List title={copy.risks} items={item.materialRisks}/></div>{item.evidenceHashes.length>0&&<details><summary className="cursor-pointer text-xs text-muted-foreground">{copy.evidence}</summary><div className="mt-2"><Hashes values={item.evidenceHashes}/></div></details>}</article>):<Empty text={copy.emptyRecommendations}/>}</PanelBody></Panel>}
  {tab==='corrections'&&<Panel><PanelHeader title={copy.correctionsTitle}/><PanelBody className="space-y-3">{runtime.collectionStates?.teacherCorrections!=='available'?<Empty text={collectionMessage(runtime.collectionStates?.teacherCorrections,copy)}/>:corrections.length?corrections.map(item=><article key={item.correctionId} className="space-y-3 rounded-lg border border-border p-4"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-medium">{item.correctionId}</h3><p className="text-xs text-muted-foreground">{item.supersededLessonId}</p></div><StatusBadge token="warning" label={item.reasonCode}/></div><p className="text-xs text-muted-foreground">{formatDate(item.issuedAtUtc)}</p>{item.replacementBlocks.map(block=><section key={block.blockId} className="rounded border border-border bg-muted/20 p-3"><h4 className="text-sm font-medium">{block.heading}</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{block.content}</p></section>)}<Hashes values={[item.sha256]}/></article>):<Empty text={copy.emptyCorrections}/>}</PanelBody></Panel>}
  {tab==='outcomes'&&<Panel><PanelHeader title={copy.outcomesTitle}/><PanelBody>{runtime.collectionStates?.teacherOutcomes!=='available'?<Empty text={collectionMessage(runtime.collectionStates?.teacherOutcomes,copy)}/>:outcomes.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="text-muted-foreground"><tr>{[copy.horizon,copy.benchmark,copy.instrumentReturn,copy.relativeReturn,copy.mae,copy.process,copy.evaluated].map(label=><th key={label} className="pb-2 font-normal">{label}</th>)}</tr></thead><tbody>{outcomes.map(item=><tr key={item.outcomeId} className="border-t border-border"><td className="py-3"><strong>{item.instrument}</strong> · {item.horizon}</td><td>{item.benchmark}</td><td>{pct(item.instrumentReturnPct,formatNumber)}</td><td>{pct(item.relativeReturnPct,formatNumber)}</td><td>{pct(item.maximumAdverseExcursionPct,formatNumber)}</td><td>{item.processState}</td><td>{formatDate(item.evaluatedAtUtc)}</td></tr>)}</tbody></table></div>:<Empty text={copy.emptyOutcomes}/>}</PanelBody></Panel>}
  {tab==='notifications'&&<Panel><PanelHeader title={copy.notificationsTitle}/><PanelBody>{runtime.notificationStatus?.state!=='available'||!runtime.notificationStatus.value?<Empty text={collectionMessage(runtime.notificationStatus?.state,copy)}/>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Meta label="Telegram" value={runtime.notificationStatus.value.telegramReady?'ready':'not ready'}/><Meta label="WhatsApp" value={runtime.notificationStatus.value.whatsAppReady?'ready':'not ready'}/><Meta label="Events" value={runtime.notificationStatus.value.eventKinds.join(', ')||'—'}/><Meta label="Quiet hours" value={runtime.notificationStatus.value.quietHoursEnabled?`${runtime.notificationStatus.value.quietHoursStart}-${runtime.notificationStatus.value.quietHoursEnd}`:'off'}/></div>}</PanelBody></Panel>}
 </div>
}
