'use client'
import {AlertTriangle,DatabaseZap,FileCheck2} from 'lucide-react'
import type {RuntimeCollectionState,RuntimeCrossAssetResearch,RuntimeCrossAssetResearchCollection} from '@/components/runtime-bridge'
import {Panel,PanelBody,PanelHeader} from '@/components/ui/panel'
import {StatusBadge} from '@/components/ui/status-badge'
export type ResearchProjection=RuntimeCrossAssetResearchCollection
export const unsupportedResearchProjection:ResearchProjection={state:'unsupported',items:[],message:'The current host runtime does not expose research artifacts.'}
const tone:Record<RuntimeCollectionState,string>={available:'success',unsupported:'muted',stale:'warning',error:'danger'}
const copy={unsupported:'Research artifacts are not supported by the host.',stale:'Research artifacts are stale. Previous artifacts are hidden.',error:'Research artifacts could not be read. No cached results are shown.'} as const
function time(value:string|null){if(!value)return'Not provided';const parsed=Date.parse(value);return Number.isNaN(parsed)?value:new Date(parsed).toLocaleString()}
function percent(value:number){return `${(value*100).toFixed(2)}%`}
function shortHash(value:string){return value?`${value.slice(0,12)}...`:'Not provided'}
export function ResearchStatusView({projection}:{projection:ResearchProjection}){
 const items=projection.state==='available'?projection.items:[]
 return <div className="min-w-0 space-y-5">
  <div className="grid gap-3 sm:grid-cols-3" role="status" aria-live="polite" aria-atomic="true">
   <div className="rounded-lg border border-border bg-panel/40 p-3"><div className="text-xs text-muted-foreground">Capability</div><div className="mt-2"><StatusBadge token={tone[projection.state]} label={projection.state}/></div></div>
   <div className="rounded-lg border border-border bg-panel/40 p-3"><div className="text-xs text-muted-foreground">Artifacts</div><div className="mt-1 text-sm font-medium">{projection.state==='available'?items.length:'Not available'}</div></div>
   <div className="rounded-lg border border-border bg-panel/40 p-3"><div className="text-xs text-muted-foreground">Latest evaluation</div><div className="mt-1 [overflow-wrap:anywhere] text-sm font-medium">{items.length?time(items[0].evaluatedAtUtc):'Not provided'}</div></div>
  </div>
  {projection.state!=='available'?<Panel><PanelBody className="flex min-h-52 flex-col items-center justify-center p-6 text-center"><div role={projection.state==='error'?'alert':'status'} aria-live={projection.state==='error'?'assertive':'polite'} aria-atomic="true" className="flex flex-col items-center"><AlertTriangle aria-hidden="true" className="mb-3 size-5 text-warning"/><h2 className="text-sm font-medium">Research collection {projection.state}</h2><p className="mt-2 max-w-xl [overflow-wrap:anywhere] text-xs leading-5 text-muted-foreground">{projection.message||copy[projection.state]}</p></div></PanelBody></Panel>
  :items.length===0?<Panel><PanelBody className="flex min-h-52 flex-col items-center justify-center p-6 text-center"><div role="status" aria-live="polite" aria-atomic="true" className="flex flex-col items-center"><DatabaseZap aria-hidden="true" className="mb-3 size-5 text-muted-foreground"/><h2 className="text-sm font-medium">No research artifacts</h2><p className="mt-2 text-xs text-muted-foreground">The host returned an available collection with no validated artifacts.</p></div></PanelBody></Panel>
  :<Panel className="min-w-0 overflow-hidden"><PanelHeader icon={<FileCheck2 className="size-4"/>} title={<h2 className="text-sm font-medium">Validation evidence</h2>} action={<span className="text-xs text-muted-foreground">{items.length}</span>}/><div className="grid min-w-0 gap-3 p-3">{items.map(item=><ResearchItem key={item.researchId} item={item}/>)}</div></Panel>}
 </div>
}
function ResearchItem({item}:{item:RuntimeCrossAssetResearch}){return <article className="min-w-0 rounded-lg border border-border p-4"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><div className="[overflow-wrap:anywhere] font-medium">{item.strategyId}</div><div className="mt-1 [overflow-wrap:anywhere] font-mono text-[11px] text-muted-foreground">{item.instrumentId} / {item.assetClass} / {item.strategyVersion}</div></div><StatusBadge token={item.status==='Unsupported'?'muted':item.passed?'success':'warning'} label={item.status}/></div><dl className="mt-4 grid gap-3 border-t border-border pt-3 text-xs sm:grid-cols-2 lg:grid-cols-4"><Cell label="Lifecycle" value={item.lifecycle}/><Cell label="Evaluated" value={time(item.evaluatedAtUtc)}/><Cell label="OOS window" value={`${time(item.outOfSampleStartsAtUtc)} to ${time(item.outOfSampleEndsAtUtc)}`}/><Cell label="Purge / embargo" value={`${item.oosPurgeObservations} / ${item.oosEmbargoObservations}`}/>{item.metrics&&<><Cell label="Observations / trades" value={`${item.metrics.observations} / ${item.metrics.trades}`}/><Cell label="OOS return" value={percent(item.metrics.outOfSampleReturn)}/><Cell label="Max drawdown" value={percent(item.metrics.maximumDrawdown)}/><Cell label="Walk-forward / MC loss" value={`${item.metrics.walkForwardScore.toFixed(3)} / ${percent(item.metrics.monteCarloLossProbability)}`}/></>}<Cell label="Artifact hash" value={shortHash(item.artifactHash)} mono/><Cell label="Dataset hash" value={shortHash(item.datasetHash)} mono/><Cell label="Parameter hash" value={shortHash(item.parameterHash)} mono/><Cell label="Code / seed" value={`${item.codeVersion||'Not provided'} / ${item.seed}`}/><Cell label="Alignment" value={item.alignment.required?`${item.alignment.venueCount} venues / ${item.alignment.alignmentPointCount} points`:'Not required'}/><Cell label="Multiple testing" value={item.multipleTesting?`${item.multipleTesting.correctionMethod} / ${item.multipleTesting.trialCount} trials`:'Not provided'}/><div className="sm:col-span-2 lg:col-span-4"><dt className="text-muted-foreground">Reason codes</dt><dd className="mt-1 flex flex-wrap gap-1">{item.reasonCodes.length?item.reasonCodes.map(code=><span key={code} className="max-w-full rounded-md bg-muted px-1.5 py-0.5 font-mono text-[10px] [overflow-wrap:anywhere]">{code}</span>):'None provided'}</dd></div></dl></article>}
function Cell({label,value,mono=false}:{label:string;value:string;mono?:boolean}){return <div className="min-w-0"><dt className="text-muted-foreground">{label}</dt><dd className={`${mono?'font-mono text-[11px] ':''}[overflow-wrap:anywhere]`}>{value}</dd></div>}
