using System.Globalization;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Windows;
using System.Windows.Controls;
using Microsoft.Win32;
using 币安量化机器人.Services;
using 币安量化机器人.Services.Access;
using 币安量化机器人.Services.Agent;
using 币安量化机器人.Services.Localization;

namespace 币安量化机器人;

public partial class SetupWindow:Window
{
    private readonly AgentSettingsStore _store=new();private readonly AccessReadinessService _readiness=new();private AgentSettings _settings;private AccessReadinessReport? _last;private static LocalizationService I18n=>LocalizationService.Current;public bool SetupCompleted{get;private set;}
    public SetupWindow(string user,bool configurationMode=false){InitializeComponent();_settings=_store.Load();_settings.ActiveUser=user;UserText.Text="● "+user;LoadSettings();if(configurationMode){WizardTabs.SelectedIndex=1;}I18n.LanguageChanged+=LanguageChanged;}
    protected override void OnClosed(EventArgs e){I18n.LanguageChanged-=LanguageChanged;base.OnClosed(e);}
    private void LoadSettings(){var s=_store.GetActiveExchange(_settings);ApiBaseBox.Text=s.Endpoint;ReceiveWindowBox.Text=s.ReceiveWindow.ToString();ExchangeTimeoutBox.Text=s.TimeoutSeconds.ToString();ProxyCheck.IsChecked=s.UseProxy;ProxyBox.Text=s.ProxyUrl;ApiKeyHint.Text=Mask(s.EncryptedCredentials.GetValueOrDefault("apiKey")??string.Empty,"Access.StoredCredential");ApiSecretHint.Text=Mask(s.EncryptedCredentials.GetValueOrDefault("secret")??string.Empty,"Access.StoredCredential");if(!_settings.Brains.TryGetValue(_settings.ActiveBrain,out var b)){b=new BrainSlot();_settings.Brains[_settings.ActiveBrain]=b;}SelectProvider(b.Provider);BrainEndpointBox.Text=b.Endpoint;BrainModelBox.Text=b.Model;BrainKeyHint.Text=Mask(b.EncryptedKey,"Access.StoredCredential");MaxTokenBox.Text=b.MaxTokens.ToString();TemperatureBox.Text=b.Temperature.ToString(CultureInfo.InvariantCulture);BrainTimeoutBox.Text=b.TimeoutSeconds.ToString();RetryBox.Text=b.RetryCount.ToString();PromptVersionBox.Text=b.PromptVersion;ContextLimitBox.Text=b.ContextLimit.ToString();LocalBrainCheck.IsChecked=b.IsLocal;FallbackCheck.IsChecked=b.EnableFallback;SymbolsBox.Text=string.Join(", ",_settings.Symbols);RealtimeDataCheck.IsChecked=_settings.DataSources.BinanceRealtimeEnabled;NewsDataCheck.IsChecked=_settings.DataSources.NewsEnabled;NotificationCheck.IsChecked=_settings.Notification.Enabled;LeverageBox.Text=_settings.Risk.Leverage.ToString();TradeRiskBox.Text=(_settings.Risk.MaxRiskPerTrade*100).ToString("0.##",CultureInfo.InvariantCulture);AccountExposureBox.Text=(_settings.Risk.MaxAccountExposure*100).ToString("0.##",CultureInfo.InvariantCulture);}
    private static string Mask(string encrypted,string key)
    {
        if(string.IsNullOrWhiteSpace(encrypted))return I18n.T("Access.NotConfigured");
        try{var value=SecretVaultService.Decrypt(encrypted);return value.Length>8?$"{value[..4]}********{value[^4..]}":I18n.T(key);}catch{return I18n.T("Access.CredentialUnavailable");}
    }
    private void SaveExchange(){if(!Uri.TryCreate(ApiBaseBox.Text,UriKind.Absolute,out var uri)||uri.Scheme!="https")throw new InvalidOperationException(I18n.T("Setup.HttpsOnly"));var s=_store.GetActiveExchange(_settings);if(ApiKeyBox.Password.Length>0)s.EncryptedCredentials["apiKey"]=SecretVaultService.Encrypt(ApiKeyBox.Password.Trim());if(ApiSecretBox.Password.Length>0)s.EncryptedCredentials["secret"]=SecretVaultService.Encrypt(ApiSecretBox.Password.Trim());s.Endpoint=uri.ToString().TrimEnd('/');s.UseProxy=ProxyCheck.IsChecked==true;s.ProxyUrl=ProxyBox.Text.Trim();s.ReceiveWindow=int.TryParse(ReceiveWindowBox.Text,out var rw)?Math.Clamp(rw,1000,60000):5000;s.TimeoutSeconds=int.TryParse(ExchangeTimeoutBox.Text,out var timeout)?Math.Clamp(timeout,5,120):20;s.IsTestnet=true;_settings.Environment=ExchangeEnvironment.Testnet;_settings.EnvironmentMode="ProviderTestnet";_store.Save(_settings);}
    private void SaveBrain(){var provider=(ProviderBox.SelectedItem as ComboBoxItem)?.Content?.ToString()??"DeepSeek";if(!Uri.TryCreate(BrainEndpointBox.Text,UriKind.Absolute,out var uri)||uri.Scheme is not("https" or "http"))throw new InvalidOperationException(I18n.T("Setup.EndpointInvalid"));var name=provider;var old=_settings.Brains.GetValueOrDefault(name)??new BrainSlot();old.Provider=provider;old.Endpoint=uri.ToString();old.Model=BrainModelBox.Text.Trim();if(BrainKeyBox.Password.Length>0)old.EncryptedKey=SecretVaultService.Encrypt(BrainKeyBox.Password.Trim());old.MaxTokens=Int(MaxTokenBox.Text,1200,128,32768);old.Temperature=Double(TemperatureBox.Text,.1,0,2);old.TimeoutSeconds=Int(BrainTimeoutBox.Text,75,5,300);old.RetryCount=Int(RetryBox.Text,2,0,5);old.PromptVersion=PromptVersionBox.Text.Trim();old.ContextLimit=Int(ContextLimitBox.Text,32000,2048,1000000);old.IsLocal=LocalBrainCheck.IsChecked==true;old.EnableFallback=FallbackCheck.IsChecked==true;_settings.Brains[name]=old;_settings.ActiveBrain=name;_store.Save(_settings);}
    private async Task CheckAll(){SaveExchange();SaveBrain();SaveAdvanced();HealthText.Text=I18n.T("Setup.Checking");_last=await _readiness.CheckAsync(_settings);HealthText.Text=_last.Summary;_settings.LastAccessCheckAtUtc=_last.CheckedAtUtc;_store.Save(_settings);}
    private void SaveExchange_Click(object sender,RoutedEventArgs e){Try(()=>{SaveExchange();ExchangeStatus.Text=I18n.T("Setup.Saved");});}
    private void OpenExchangeManager_Click(object sender,RoutedEventArgs e){new ExchangeManagerWindow{Owner=this}.ShowDialog();_settings=_store.Load();LoadSettings();}
    private async void TestExchange_Click(object sender,RoutedEventArgs e){try{SaveExchange();var report=await _readiness.CheckAsync(_settings);var exchange=report.Checks.Where(x=>x.Key is "exchange" or "trade_permission" or "withdraw_permission" or "clock");ExchangeStatus.Text=string.Join("\n",exchange.Select(x=>$"{(x.Passed?"●":"○")} {x.Detail}"));}catch(Exception ex){ExchangeStatus.Text=ex.Message;}}
    private void SaveBrain_Click(object sender,RoutedEventArgs e){Try(()=>{SaveBrain();BrainStatus.Text=I18n.T("Setup.Saved");});}
    private void RevealExchange_Changed(object sender,RoutedEventArgs e){var profile=_store.GetActiveExchange(_settings);if(RevealExchangeCheck.IsChecked==true){ApiKeyBox.Password=Decrypt(profile.EncryptedCredentials.GetValueOrDefault("apiKey")??string.Empty);ApiSecretBox.Password=Decrypt(profile.EncryptedCredentials.GetValueOrDefault("secret")??string.Empty);}else{ApiKeyBox.Clear();ApiSecretBox.Clear();}}
    private void RevealBrain_Changed(object sender,RoutedEventArgs e){if(RevealBrainCheck.IsChecked==true&&_settings.Brains.TryGetValue(_settings.ActiveBrain,out var brain))BrainKeyBox.Password=Decrypt(brain.EncryptedKey);else BrainKeyBox.Clear();}
    private void DeleteExchange_Click(object sender,RoutedEventArgs e){if(MessageBox.Show(I18n.T("Access.DeleteConfirm"),I18n.T("Setup.ExchangeTitle"),MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;var s=_store.GetActiveExchange(_settings);s.EncryptedCredentials.Clear();s.ReadPermission=s.TradePermission=s.WithdrawPermission=false;s.AccountId=string.Empty;_settings.SetupCompleted=false;_store.Save(_settings);ApiKeyBox.Clear();ApiSecretBox.Clear();LoadSettings();}
    private void DeleteBrain_Click(object sender,RoutedEventArgs e){if(MessageBox.Show(I18n.T("Access.DeleteConfirm"),I18n.T("Setup.BrainTitle"),MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;if(_settings.Brains.TryGetValue(_settings.ActiveBrain,out var b))b.EncryptedKey=string.Empty;_settings.SetupCompleted=false;_store.Save(_settings);BrainKeyBox.Clear();LoadSettings();}
    private void SaveAdvanced(){_settings.Symbols=SymbolsBox.Text.Split([',',';',' '],StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim().ToUpperInvariant()).Where(x=>x.EndsWith("USDT",StringComparison.Ordinal)&&x.Length is >=7 and <=20).Distinct().Take(8).ToList();if(_settings.Symbols.Count==0)_settings.Symbols=["BTCUSDT","ETHUSDT"];_settings.DataSources.BinanceRealtimeEnabled=RealtimeDataCheck.IsChecked==true;_settings.DataSources.NewsEnabled=NewsDataCheck.IsChecked==true;_settings.Notification.Enabled=NotificationCheck.IsChecked==true;_settings.Risk.Leverage=Int(LeverageBox.Text,5,1,20);_settings.Risk.MaxRiskPerTrade=(decimal)(Double(TradeRiskBox.Text,1,.25,2)/100);_settings.Risk.MaxAccountExposure=(decimal)(Double(AccountExposureBox.Text,60,10,60)/100);_store.Save(_settings);}
    private void SaveAdvanced_Click(object sender,RoutedEventArgs e){Try(()=>{SaveAdvanced();AdvancedStatus.Text=I18n.T("Setup.Saved");});}
    private void Backup_Click(object sender,RoutedEventArgs e){Try(()=>{SaveAdvanced();AdvancedStatus.Text=I18n.T("Setup.BackupCreated",CreateBackup());});}
    private void Restore_Click(object sender,RoutedEventArgs e){var dialog=new OpenFileDialog{Filter="WPE Backup (*.zip)|*.zip",InitialDirectory=Path.Combine(AppContext.BaseDirectory,"Data","Backups")};if(dialog.ShowDialog()!=true)return;if(MessageBox.Show(I18n.T("Setup.RestoreConfirm"),I18n.T("Setup.Restore"),MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;Try(()=>{var safety=CreateBackup();RestoreBackup(dialog.FileName);_settings=_store.Load();LoadSettings();AdvancedStatus.Text=I18n.T("Setup.Restored",safety);});}
    private void OpenLogs_Click(object sender,RoutedEventArgs e){var path=Path.Combine(AppContext.BaseDirectory,"logs");Directory.CreateDirectory(path);Process.Start(new ProcessStartInfo("explorer.exe",$"\"{path}\""){UseShellExecute=true});}
    private static string CreateBackup(){var data=Path.Combine(AppContext.BaseDirectory,"Data");var dir=Path.Combine(data,"Backups");Directory.CreateDirectory(dir);var path=Path.Combine(dir,$"wpe-access-{DateTime.Now:yyyyMMdd-HHmmss}.zip");using var zip=ZipFile.Open(path,ZipArchiveMode.Create);foreach(var name in new[]{"agent-settings.json","local-accounts.json"}){var source=Path.Combine(data,name);if(File.Exists(source))zip.CreateEntryFromFile(source,name,CompressionLevel.Optimal);}return path;}
    private static void RestoreBackup(string archive){var data=Path.Combine(AppContext.BaseDirectory,"Data");using var zip=ZipFile.OpenRead(archive);foreach(var name in new[]{"agent-settings.json","local-accounts.json"}){var entry=zip.GetEntry(name);if(entry is null)continue;var target=Path.GetFullPath(Path.Combine(data,name));if(!target.StartsWith(Path.GetFullPath(data)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Unsafe backup path");entry.ExtractToFile(target,true);}}
    private async void TestBrain_Click(object sender,RoutedEventArgs e){try{SaveBrain();var report=await _readiness.CheckAsync(_settings);var b=report.Checks.First(x=>x.Key=="brain");BrainStatus.Text=$"{(b.Passed?"●":"○")} {b.Detail}";}catch(Exception ex){BrainStatus.Text=ex.Message;}}
    private async void CheckAll_Click(object sender,RoutedEventArgs e){try{await CheckAll();}catch(Exception ex){HealthText.Text=ex.Message;}}
    private async void Finish_Click(object sender,RoutedEventArgs e){try{await CheckAll();if(_last?.Ready!=true){FinishStatus.Text=I18n.T("Setup.NotReady");WizardTabs.SelectedIndex=3;return;}if(RiskConfirmBox.IsChecked!=true){FinishStatus.Text=I18n.T("Setup.ConfirmRequired");WizardTabs.SelectedIndex=4;return;}_settings.SetupCompleted=true;_settings.SetupCompletedAtUtc=DateTime.UtcNow;_store.Save(_settings);SetupCompleted=true;DialogResult=true;}catch(Exception ex){FinishStatus.Text=ex.Message;}}
    private void Environment_Changed(object sender,SelectionChangedEventArgs e){if(!IsLoaded)return;var tag=(EnvironmentBox.SelectedItem as ComboBoxItem)?.Tag?.ToString();if(tag=="Mainnet"){EnvironmentBox.SelectedIndex=0;MessageBox.Show(I18n.T("Setup.MainnetDisabled"));}}
    private void Provider_Changed(object sender,SelectionChangedEventArgs e){if(!IsLoaded)return;var p=(ProviderBox.SelectedItem as ComboBoxItem)?.Content?.ToString();if(p=="DeepSeek"){BrainEndpointBox.Text="https://api.deepseek.com/chat/completions";BrainModelBox.Text="deepseek-chat";}else if(p=="OpenAI"){BrainEndpointBox.Text="https://api.openai.com/v1/responses";BrainModelBox.Text="gpt-5";}else if(p=="Anthropic"){BrainEndpointBox.Text="https://api.anthropic.com/v1/messages";BrainModelBox.Text="claude-sonnet-4-5";}else if(p=="Local Ollama"){BrainEndpointBox.Text="http://127.0.0.1:11434/v1/chat/completions";BrainModelBox.Text="qwen3";LocalBrainCheck.IsChecked=true;}}
    private void SelectProvider(string provider){foreach(var item in ProviderBox.Items.OfType<ComboBoxItem>())if(string.Equals(item.Content?.ToString(),provider,StringComparison.OrdinalIgnoreCase)){ProviderBox.SelectedItem=item;return;}}
    private void Nav_Click(object sender,RoutedEventArgs e){if(int.TryParse((sender as Button)?.Tag?.ToString(),out var i))WizardTabs.SelectedIndex=i;}
    private void Previous_Click(object sender,RoutedEventArgs e)=>WizardTabs.SelectedIndex=Math.Max(0,WizardTabs.SelectedIndex-1);private void Next_Click(object sender,RoutedEventArgs e)=>WizardTabs.SelectedIndex=Math.Min(5,WizardTabs.SelectedIndex+1);
    private void Language_Click(object sender,RoutedEventArgs e){var menu=new ContextMenu{PlacementTarget=LanguageButton};foreach(var language in I18n.AvailableLanguages){var item=new MenuItem{Header=language.DisplayName,Tag=language.Code};item.Click+=(_,_)=>I18n.SetLanguage((string)item.Tag);menu.Items.Add(item);}LanguageButton.ContextMenu=menu;menu.IsOpen=true;}
    private void LanguageChanged()=>Dispatcher.Invoke(()=>{Language=System.Windows.Markup.XmlLanguage.GetLanguage(I18n.Culture.IetfLanguageTag);LoadSettings();});private static string Decrypt(string encrypted){try{return string.IsNullOrWhiteSpace(encrypted)?string.Empty:SecretVaultService.Decrypt(encrypted);}catch{return string.Empty;}}private static void Try(Action action){try{action();}catch(Exception ex){MessageBox.Show(ex.Message);}}private static int Int(string s,int fallback,int min,int max)=>int.TryParse(s,out var v)?Math.Clamp(v,min,max):fallback;private static double Double(string s,double fallback,double min,double max)=>double.TryParse(s,NumberStyles.Any,CultureInfo.InvariantCulture,out var v)?Math.Clamp(v,min,max):fallback;
}
