using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Data.Sqlite;
using System.IO;
using 币安量化机器人.Services;
using 币安量化机器人.Services.Agent;

namespace WpeAgent.ModelOff;

public sealed record AuditAggregateAcceptanceRunResult(bool Success,string ArtifactDirectory,IReadOnlyList<string> Errors);

public static class AuditAggregateAcceptanceRunnerV1
{
    public static async Task<AuditAggregateAcceptanceRunResult> RunAsync(CancellationToken ct=default)
    {
        var directory=Path.Combine(AppDataPaths.TestArtifactsDirectory,"audit-aggregate-acceptance",DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(directory);var errors=new List<string>();var files=new List<object>();var candidate=await Candidate(ct);var temp=Path.Combine(Path.GetTempPath(),"wpe-audit-acceptance-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(temp);
        try
        {
            var now=DateTimeOffset.UtcNow;await using var source=new BinanceTestnetMarketAcceptanceSourceV1();var market=await source.ReadAsync("BTCUSDT",ct);if(!MarketEvidenceProvenanceCanonicalizerV1.IsCanonical(market))throw new InvalidOperationException("Audit acceptance Testnet source is noncanonical.");var liveHash=market.Provenance!.CanonicalSha256;var cycle="audit-acceptance-"+Guid.NewGuid().ToString("N");var inputs=Inputs(cycle,now,liveHash);var database=Path.Combine(temp,"agent.db");var firstStore=new AgentSqliteStore(database,()=>now);var request=new ModelOffProductionCycleRequestV1(cycle,now,inputs);var first=await new ModelOffProductionCycleOrchestratorV1(firstStore).RunAsync(request,ct);if(!first.EligibleForRiskIncrease||first.Code!="model-off.production-cycle-ready"||first.Outputs.Count!=7||first.Handoffs.Count!=6)throw new InvalidOperationException("Audit acceptance production cycle was incomplete.");
            SqliteConnection.ClearAllPools();var restarted=new AgentSqliteStore(database,()=>now.AddSeconds(1));var beforeOutputs=await restarted.GetModelOffCanonicalAuditsAsync(cycle,ct);var beforeHandoffs=await restarted.GetModelOffCanonicalHandoffsAsync(cycle,ct);if(!PersistedComplete(beforeOutputs,beforeHandoffs,cycle))throw new InvalidOperationException("Audit acceptance did not survive restart with a complete canonical chain.");var replay=await new ModelOffProductionCycleOrchestratorV1(restarted).RunAsync(request,ct);if(!replay.EligibleForRiskIncrease||replay.Code!="model-off.production-cycle-ready")throw new InvalidOperationException("Audit acceptance idempotent replay failed.");var afterOutputs=await restarted.GetModelOffCanonicalAuditsAsync(cycle,ct);var afterHandoffs=await restarted.GetModelOffCanonicalHandoffsAsync(cycle,ct);var durable=Same(beforeOutputs.Select(x=>x.CanonicalSha256),afterOutputs.Select(x=>x.CanonicalSha256))&&Same(beforeHandoffs.Select(x=>x.HandoffSha256),afterHandoffs.Select(x=>x.HandoffSha256));if(!durable)throw new InvalidOperationException("Audit canonical identity changed after restart or replay.");var outputHashes=afterOutputs.OrderBy(x=>RoleIndex(x.OutputKind)).Select(x=>x.CanonicalSha256).ToArray();var handoffHashes=afterHandoffs.OrderBy(x=>x.HandoffId,StringComparer.Ordinal).Select(x=>x.HandoffSha256).ToArray();var auditSources=first.Outputs[ModelOffAgentV1.Audit].Sources.Count;var observed=DateTimeOffset.UtcNow;
            foreach(var requirement in new[]{AuditAggregateEvidenceCanonicalizerV1.LiveCycleRequirement,AuditAggregateEvidenceCanonicalizerV1.RestartRequirement}){var artifact=AuditAggregateEvidenceCanonicalizerV1.Create(requirement,candidate,observed,liveHash,outputHashes,handoffHashes,auditSources,durable,true);if(!AuditAggregateEvidenceCanonicalizerV1.IsCanonical(artifact,DateTimeOffset.UtcNow))throw new InvalidOperationException("Generated Audit evidence is ineligible: "+requirement);var name=requirement+".json";await AtomicWrite(Path.Combine(directory,name),artifact.CanonicalBytes,ct);if(!AuditAggregateEvidenceCanonicalizerV1.TryParseCanonical(await File.ReadAllBytesAsync(Path.Combine(directory,name),ct),out var reread)||!AuditAggregateEvidenceCanonicalizerV1.IsCanonical(reread,DateTimeOffset.UtcNow))throw new InvalidOperationException("Persisted Audit evidence is invalid: "+requirement);files.Add(new{name,artifact.RequirementId,artifact.CanonicalSha256,artifact.ObservedAtUtc,outputs=7,handoffs=6});}
        }
        catch(OperationCanceledException)when(ct.IsCancellationRequested){throw;}catch(Exception ex){errors.Add("audit-aggregate-acceptance.failed:"+ex.GetType().Name+":"+SensitiveDataRedactor.ForLog(ex.Message,180));}
        finally{SqliteConnection.ClearAllPools();try{Directory.Delete(temp,true);}catch(IOException){}}
        var manifest=JsonSerializer.SerializeToUtf8Bytes(new{schema="wpe.audit-aggregate-acceptance-run/1.0",candidateVersion=candidate.Version,candidateSha256=candidate.Sha256,provider="binance-futures",environment="Testnet",mainnetEnabled=false,mutationEnabled=false,completedAtUtc=DateTimeOffset.UtcNow,success=errors.Count==0,files,errors});await AtomicWrite(Path.Combine(directory,"manifest.json"),manifest,CancellationToken.None);await AtomicWrite(Path.Combine(directory,"manifest.sha256"),Encoding.ASCII.GetBytes(Hash(manifest)),CancellationToken.None);return new(errors.Count==0,directory,errors);
    }

    private static ModelOffProductionInputV1[] Inputs(string cycle,DateTimeOffset now,string liveHash)
    {
        var result=new List<ModelOffProductionInputV1>();ModelOffCanonicalDocumentV1? previous=null;foreach(var role in new[]{ModelOffAgentV1.Market,ModelOffAgentV1.Research,ModelOffAgentV1.Strategy,ModelOffAgentV1.Risk}){var source=previous is null?new ModelOffSourceV1("binance-testnet-BTCUSDT",ModelOffSourceKindV1.Market,now,now,ModelOffSourceStatusV1.Available,"sha256:"+liveHash):new ModelOffSourceV1(result[^1].Output.OutputId,ModelOffSourceKindV1.Audit,now,now,ModelOffSourceStatusV1.Available,"sha256:"+previous.Sha256);var output=new ModelOffAgentOutputV1(role,$"{cycle}-audit-input-{role.ToString().ToLowerInvariant()}",cycle,now,now,ModelOffProductionCycleOrchestratorV1.InputSchema,new("wpe.audit-acceptance-input","1.0"),[source],ModelOffOutputStatusV1.Succeeded,new(ModelOffUncertaintyLevelV1.None,[],[]),JsonSerializer.SerializeToElement(new{auditAcceptance=true,symbol="BTCUSDT",mutationAttempted=false}),[],new("continue_audit_chain",true,[]),[],ModelOffFixedTemplatesV1.SummaryVersion);var document=ModelOffCanonicalSerializerV1.Serialize(output);result.Add(new(output,document));previous=document;}return result.ToArray();
    }
    private static bool PersistedComplete(IReadOnlyList<PersistedModelOffAudit> outputs,IReadOnlyList<PersistedModelOffHandoff> handoffs,string cycle)=>outputs.Count==7&&outputs.Select(x=>x.OutputKind).Distinct(StringComparer.Ordinal).Count()==7&&outputs.All(x=>x.CycleId==cycle&&Hash(x.CanonicalBytes)==x.CanonicalSha256)&&handoffs.Count==6&&handoffs.All(x=>x.CycleId==cycle&&Hash(x.CanonicalBytes)==x.HandoffSha256);
    private static bool Same(IEnumerable<string> first,IEnumerable<string> second)=>first.Order(StringComparer.Ordinal).SequenceEqual(second.Order(StringComparer.Ordinal),StringComparer.Ordinal);private static int RoleIndex(string role)=>Array.FindIndex(Enum.GetNames<ModelOffAgentV1>(),x=>x.Equals(role,StringComparison.OrdinalIgnoreCase));private static string Hash(byte[] bytes)=>Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();private static async Task<MarketAcceptanceCandidateV1> Candidate(CancellationToken ct){var assembly=Assembly.GetExecutingAssembly();return new(assembly.GetName().Version?.ToString()??"unknown",Hash(await File.ReadAllBytesAsync(assembly.Location,ct)));}private static async Task AtomicWrite(string path,byte[] bytes,CancellationToken ct){var temp=path+"."+Guid.NewGuid().ToString("N")+".tmp";await File.WriteAllBytesAsync(temp,bytes,ct);File.Move(temp,path,false);}
}
