using System.Diagnostics;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace 币安量化机器人.Services.Agent;

public sealed record AutonomyTestCase(string Name,string Status,long DurationMs,string Detail);
public sealed class AutonomyTestReport
{
    public DateTime StartedAtUtc { get; init; }=DateTime.UtcNow;public DateTime CompletedAtUtc { get; set; }public bool Success { get; set; }public List<AutonomyTestCase> Cases { get; }=[];
}

public static class AutonomyTestRunner
{
    public static async Task<SmokeRunResult> RunAsync(CancellationToken ct=default)
    {
        var report=new AutonomyTestReport();var dir=Path.Combine(AppContext.BaseDirectory,"Data","autonomy-tests");Directory.CreateDirectory(dir);var reportPath=Path.Combine(dir,$"autonomy-{DateTime.UtcNow:yyyyMMdd-HHmmss}.json");var dbPath=Path.Combine(dir,$"autonomy-{Guid.NewGuid():N}.db");
        try
        {
            await Case(report,"确定性计划补齐入场、保护与收益风险比",async()=>{var market=Market();var source=new DecisionPlan{Action=DecisionAction.OpenLong,Instrument="BTCUSDT",Confidence=.9,TargetTier=1};var plan=new DeterministicPlanSkill().Complete(source,market,null,new());Require(plan.EntryPrice>0&&plan.StopLossPrice<plan.EntryPrice&&plan.TakeProfitPrice>plan.EntryPrice,"计划保护参数无效");Require(plan.RiskRewardRatio>=1.8,"收益风险比未达到硬限制");return await Task.FromResult($"entry={plan.EntryPrice} stop={plan.StopLossPrice} take={plan.TakeProfitPrice} RR={plan.RiskRewardRatio:F2} type={plan.OrderType}");});
            await Case(report,"仓位由单笔风险和敞口共同限制",async()=>{var evidence=Evidence(Market());var plan=new DecisionPlan{Action=DecisionAction.OpenLong,Instrument="BTCUSDT",Confidence=.9,TargetTier=3,EntryPrice=100,StopLossPrice=98,TakeProfitPrice=104,RiskRewardRatio=2,OrderType=ExecutionOrderType.Limit};var result=new RiskAndPositionPlanner().Plan(plan,evidence,new("BTCUSDT",.001m,.1m,.001m,5,50),new(),1000);Require(result.Intents.Count==1,result.Result);var intent=result.Intents[0];Require(intent.Quantity*Math.Abs(intent.ExpectedPrice-intent.StopLoss)<=10.01m,"单笔风险超过账户权益 1%");Require(intent.Quantity*intent.ExpectedPrice<=250.01m,"单品种敞口超过 25%");return await Task.FromResult($"qty={intent.Quantity} risk={intent.Quantity*Math.Abs(intent.ExpectedPrice-intent.StopLoss):F2} notional={intent.Quantity*intent.ExpectedPrice:F2}");});
            await Case(report,"独立风控否决低质量与状态不确定订单",async()=>{var bad=Market() with{Quality=new(){QualityScore=30,LiquidityScore=.2,SpreadBps=30,AtrPercent=.08}};var evidence=Evidence(bad);var plan=new DecisionPlan{Action=DecisionAction.OpenLong,Instrument="BTCUSDT",EntryPrice=100,StopLossPrice=98,TakeProfitPrice=104,RiskRewardRatio=2};var intent=new ExecutionIntent("BTCUSDT",PositionSide.Long,1,false,98,104,"risk-test","test",DecisionAction.OpenLong,ExpectedPrice:100);var review=new IndependentRiskManagerSkill().Review(plan,evidence,null,[intent],new(),new(0,0,0,true),null);Require(!review.Approved&&review.BlockingReasons.Count>=4,"独立风控未完整拦截");return await Task.FromResult(string.Join("; ",review.BlockingReasons));});
            await Case(report,"研究模块输出样本外、Walk-forward 与 Monte Carlo 指标",async()=>{var market=Market(320);var result=new StrategyResearchSkill().Evaluate(market);Require(result.SampleSize==320,"样本数量错误");Require(result.Trades>=3,"研究样本未形成足够的策略交易");Require(double.IsFinite(result.QualityScore)&&double.IsFinite(result.WalkForwardScore)&&double.IsFinite(result.MonteCarloLossProbability),"研究指标非有限值");Require(result.MonteCarloLossProbability is >=0 and <=1,"Monte Carlo 概率越界");return await Task.FromResult(result.Summary);});
            var db=new AgentSqliteStore(dbPath);
            await Case(report,"限价未成交安全撤销且不创建保护单",async()=>{await using var exchange=new FakeExchange(FakeFill.None);var executor=new ReliableOrderExecutor(exchange,db);var intent=Intent("NOFILL");var result=await executor.ExecuteAsync("C-NOFILL",intent,5,true,ct);Require(exchange.CancelCount==0,"终态撤单不应再次取消");Require(exchange.ProtectionCount==0,"未成交不得创建保护单");Require(result.Length>0,"必须返回审计结果");return result;});
            await Case(report,"部分成交按实际数量记录并立即挂保护",async()=>{await using var exchange=new FakeExchange(FakeFill.Partial);var executor=new ReliableOrderExecutor(exchange,db);var intent=Intent("PARTIAL");var result=await executor.ExecuteAsync("C-PARTIAL",intent,5,true,ct);Require(exchange.ProtectionCount==1,"部分成交未创建保护单");Require(result.Length>0,"缺少部分成交结果");return result;});
            await Case(report,"执行前质量与滑点复核具有最终否决权",async()=>{await using var exchange=new FakeExchange(FakeFill.Full){MarketQuality=new(){QualityScore=25,LiquidityScore=.1,SpreadBps=40,AtrPercent=.10}};var executor=new ReliableOrderExecutor(exchange,db);try{await executor.ExecuteAsync("C-BAD",Intent("BAD"),5,true,ct);throw new InvalidOperationException("低质量订单被错误执行");}catch(InvalidOperationException ex)when(ex.Message.Contains("Execution.PreflightBlocked")||ex.Message.Contains("执行预检")||ex.Message.Contains("preflight",StringComparison.OrdinalIgnoreCase)){Require(exchange.PlaceCount==0,"预检后仍提交订单");return ex.Message;}});
            await Case(report,"未知订单状态进入冻结并可由恢复流程识别",async()=>{await using var exchange=new FakeExchange(FakeFill.Unknown);var executor=new ReliableOrderExecutor(exchange,db);try{await executor.ExecuteAsync("C-UNKNOWN",Intent("UNKNOWN"),5,true,ct);}catch{}var recovery=await executor.RecoverPendingAsync(ct);Require(!recovery.SafeToIncreaseRisk,"未知订单状态未冻结新增风险");return string.Join("; ",recovery.Messages);});
            await Case(report,"18项技能均具备权限、超时、重试与健康定义",async()=>{Require(AgentSkillRegistry.Skills.Count>=18,"技能数量不足");Require(AgentSkillRegistry.Skills.All(x=>x.TimeoutSeconds>0&&x.Retries>=0&&!string.IsNullOrWhiteSpace(x.Permission)&&!string.IsNullOrWhiteSpace(x.HealthCheck)),"技能元数据不完整");return await Task.FromResult($"skills={AgentSkillRegistry.Skills.Count}");});
            await Case(report,"Brain 列表字段兼容单字符串但拒绝非字符串内容",async()=>{var options=new JsonSerializerOptions{PropertyNameCaseInsensitive=true};options.Converters.Add(new JsonStringEnumConverter());options.Converters.Add(new FlexibleStringListConverter());var plan=JsonSerializer.Deserialize<DecisionPlan>("{\"action\":\"Hold\",\"missingConditions\":\"等待流动性\",\"evidenceReferences\":null}",options);Require(plan?.MissingConditions.SequenceEqual(["等待流动性"])==true&&plan.EvidenceReferences.Count==0,"Brain 列表规范化失败");try{JsonSerializer.Deserialize<DecisionPlan>("{\"missingConditions\":[1]}",options);throw new InvalidOperationException("非字符串证据被错误接受");}catch(JsonException){}return await Task.FromResult("string→[string], null→[], non-string rejected");});
            report.Success=report.Cases.All(x=>x.Status=="PASSED");
        }
        catch(Exception ex){report.Cases.Add(new("测试运行中止","FAILED",0,ex.ToString()));report.Success=false;}
        report.CompletedAtUtc=DateTime.UtcNow;await File.WriteAllTextAsync(reportPath,JsonSerializer.Serialize(report,new JsonSerializerOptions{WriteIndented=true}),ct);return new(report.Success,reportPath);
    }

    private static async Task Case(AutonomyTestReport report,string name,Func<Task<string>> test){var sw=Stopwatch.StartNew();try{var detail=await test();report.Cases.Add(new(name,"PASSED",sw.ElapsedMilliseconds,detail));}catch(Exception ex){report.Cases.Add(new(name,"FAILED",sw.ElapsedMilliseconds,ex.Message));throw;}}
    private static void Require(bool condition,string message){if(!condition)throw new InvalidOperationException(message);}
    private static EvidencePack Evidence(MarketEvidence market)=>new(){Account=new(1000,1000,1000,DateTime.UtcNow),Markets=new Dictionary<string,MarketEvidence>{{market.Symbol,market}},Completeness=100};
    private static MarketEvidence Market(int candles=0)
    {
        var list=new List<CandleEvidence>();decimal price=90;for(var i=0;i<candles;i++){price+=i%80<40?.8m:-.8m;list.Add(new(DateTime.UtcNow.AddMinutes((i-candles)*15),price-.1m,price+.5m,price-.5m,price,100+i,price*(100+i),100+i,55+i/2));}
        var current=candles>0?list[^1].Close:100;return new("BTCUSDT",current,current*.96m,current*1.06m,62,.006,.012,.02,new(-.0001m,100000,.8m,.8m,.8m,1.15m,.002m),DateTime.UtcNow){Quality=new(){BestBid=current-.05m,BestAsk=current+.05m,SpreadBps=1,OrderBookImbalance=.2,AtrPercent=.01,RealizedVolatility=.012,RelativeVolume=1.2,LiquidityScore=.9,SourceCount=6,QualityScore=95},Candles=list};
    }
    private static ExecutionIntent Intent(string suffix)=>new("BTCUSDT",PositionSide.Long,1,false,98,104,$"WPE-TEST-{suffix}","autonomy-test",DecisionAction.OpenLong,ExecutionOrderType.Limit,100,100);

    private enum FakeFill { None,Partial,Full,Unknown }
    private sealed class FakeExchange(FakeFill fill):IExchangeAdapter
    {
        private readonly Dictionary<string,ExchangeOrder> _orders=[];private long _id=1;public ExchangeEnvironment Environment=>ExchangeEnvironment.Testnet;public int PlaceCount {get;private set;}public int CancelCount {get;private set;}public int ProtectionCount {get;private set;}public MarketQualityEvidence MarketQuality {get;set;}=Market().Quality;
        public Task<AccountSnapshot> GetAccountAsync(CancellationToken ct)=>Task.FromResult(new AccountSnapshot(1000,1000,1000,DateTime.UtcNow));public Task<IReadOnlyList<ManagedPosition>> GetPositionsAsync(CancellationToken ct)=>Task.FromResult<IReadOnlyList<ManagedPosition>>([]);public Task<IReadOnlyList<ExchangeOrder>> GetOpenOrdersAsync(string? symbol,CancellationToken ct)=>Task.FromResult<IReadOnlyList<ExchangeOrder>>([]);public Task<TradingRule> GetRulesAsync(string symbol,CancellationToken ct)=>Task.FromResult(new TradingRule(symbol,.001m,.1m,.001m,5,50));
        public Task<MarketEvidence> GetMarketAsync(string symbol,CancellationToken ct)=>Task.FromResult(Market() with{Quality=MarketQuality});public Task<IReadOnlyList<DerivativesSnapshot>> GetDerivativeHistoryAsync(string symbol,CancellationToken ct)=>Task.FromResult<IReadOnlyList<DerivativesSnapshot>>([]);public Task<IReadOnlyList<CandleEvidence>> GetCandlesAsync(string symbol,string interval,int limit,CancellationToken ct)=>Task.FromResult<IReadOnlyList<CandleEvidence>>([]);public Task<IReadOnlyList<CandleEvidence>> GetCandlesRangeAsync(string symbol,string interval,DateTime start,DateTime end,int limit,CancellationToken ct)=>Task.FromResult<IReadOnlyList<CandleEvidence>>([]);
        public Task SetLeverageAsync(string symbol,int leverage,CancellationToken ct)=>Task.CompletedTask;public Task SetMarginModeAsync(string symbol,bool isolated,CancellationToken ct)=>Task.CompletedTask;public Task SetHedgeModeAsync(bool enabled,CancellationToken ct)=>Task.CompletedTask;
        public Task<ExchangeOrder> PlaceMarketAsync(string symbol,PositionSide side,decimal quantity,string clientOrderId,bool reduceOnly,CancellationToken ct)=>Place(symbol,side,quantity,clientOrderId,"MARKET");public Task<ExchangeOrder> PlaceLimitAsync(string symbol,PositionSide side,decimal quantity,decimal price,string clientOrderId,bool reduceOnly,CancellationToken ct)=>Place(symbol,side,quantity,clientOrderId,"LIMIT");
        private Task<ExchangeOrder> Place(string symbol,PositionSide side,decimal quantity,string clientOrderId,string type){PlaceCount++;if(fill==FakeFill.Unknown)throw new TimeoutException("injected unknown state");var executed=fill switch{FakeFill.None=>0,FakeFill.Partial=>quantity/2,_=>quantity};var status=fill==FakeFill.Full?"FILLED":"CANCELED";var order=new ExchangeOrder(symbol,(_id++).ToString(),clientOrderId,status,executed,100,type,side,false,DateTime.UtcNow);_orders[clientOrderId]=order;return Task.FromResult(order);}
        public Task<ExchangeOrder> PlaceProtectionAsync(string symbol,PositionSide sideToClose,decimal stopLoss,decimal takeProfit,string groupId,CancellationToken ct){ProtectionCount++;return Task.FromResult(new ExchangeOrder(symbol,(_id++).ToString(),groupId+"-SL","NEW",0,0,"STOP_MARKET",sideToClose,true,DateTime.UtcNow));}
        public Task<ExchangeOrder?> FindOrderAsync(string symbol,string clientOrderId,CancellationToken ct)=>Task.FromResult(_orders.GetValueOrDefault(clientOrderId));public Task CancelOrderAsync(string symbol,string orderId,CancellationToken ct){CancelCount++;return Task.CompletedTask;}public ValueTask DisposeAsync()=>ValueTask.CompletedTask;
    }
}
