using System.Globalization;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.IO;
using WpeAgent.RuntimeContracts;
using WpeAgent.TradingAuthorization;
using 币安量化机器人.Core.Models;
using 币安量化机器人.Services;
using 币安量化机器人.Services.Access;
using 币安量化机器人.Services.Agent;
using 币安量化机器人.Services.Exchange;

namespace WpeAgent.ModelOff;

public sealed record RecoveryAggregateAcceptanceRunResult(bool Success,string ArtifactDirectory,IReadOnlyList<string> Errors);

public static class RecoveryAggregateAcceptanceRunnerV1
{
    private const string Symbol="BTCUSDT";
    public static async Task<RecoveryAggregateAcceptanceRunResult> RunAsync(CancellationToken ct=default)
    {
        var directory=Path.Combine(AppDataPaths.TestArtifactsDirectory,"recovery-aggregate-acceptance",DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(directory);var errors=new List<string>();var files=new List<object>();var candidate=await Candidate(ct);IExchangeProvider? provider=null;ReliableOrderExecutor? executor=null;var originalStatus=ServiceLocator.SystemState.Status;
        try
        {
            var settingsStore=new AgentSettingsStore();var settings=settingsStore.Load();if(settingsStore.LastLoadDiagnostic is not null||settings.Environment!=ExchangeEnvironment.Testnet)throw new InvalidOperationException("Recovery acceptance requires valid Testnet settings.");var configured=settingsStore.GetActiveExchange(settings);if(!configured.IsTestnet||!configured.Enabled||!configured.ExecutionEnabled||!configured.ProviderId.Equals("binance-futures",StringComparison.OrdinalIgnoreCase)||!ProviderEndpointPolicy.IsOfficialHttpsOrigin(configured.Endpoint,"testnet.binancefuture.com"))throw new InvalidOperationException("Recovery acceptance requires the enabled official Binance Futures Testnet execution profile.");var credentials=settingsStore.GetExchangeCredentials(configured);if(!credentials.TryGetValue("apiKey",out var key)||!credentials.TryGetValue("secret",out var secret)||string.IsNullOrWhiteSpace(key)||string.IsNullOrWhiteSpace(secret))throw new InvalidOperationException("Recovery acceptance Testnet credentials are unavailable.");var profile=new ExchangeConnectionProfile{Id="recovery-acceptance",ProviderId="binance-futures",DisplayName="Binance Futures Testnet recovery acceptance",Enabled=true,ExecutionEnabled=true,IsTestnet=true,Endpoint=configured.Endpoint,UseProxy=configured.UseProxy,ProxyUrl=configured.ProxyUrl,ReceiveWindow=configured.ReceiveWindow,TimeoutSeconds=configured.TimeoutSeconds};provider=new BinanceFuturesAdapter(profile,key,secret);key=string.Empty;secret=string.Empty;
            var permission=await provider.CheckPermissionsAsync(ct);var account=await provider.GetAccountAsync(ct);var initialPositions=await provider.GetPositionsAsync(ct);var initialOrders=await provider.GetOpenOrdersAsync(Symbol,ct);if(!permission.CanRead||!permission.CanTrade||permission.CanWithdraw||account.Equity<=0)throw new InvalidOperationException("Recovery acceptance permission or account authority is ineligible.");if(initialPositions.Any(x=>x.Symbol==Symbol&&x.Quantity>0)||initialOrders.Any(x=>x.Symbol==Symbol&&!x.ClientOrderId.StartsWith("WPE-RECACC-",StringComparison.Ordinal)))throw new InvalidOperationException("Recovery acceptance requires an isolated flat BTCUSDT starting state.");var capabilities=await new ProviderCapabilityProbe().ProbeAsync(provider,[Symbol],true,ct);if(!capabilities.TryGetValue(Symbol,out var capability)||capability.Status!=CapabilityStatus.Available||!capability.CanRead||!capability.CanTrade||!capability.TestnetAvailable)throw new InvalidOperationException("Recovery acceptance provider capability is unavailable.");
            if(initialOrders.Any(x=>x.Symbol==Symbol)){foreach(var oldDatabase in Directory.GetDirectories(Path.GetTempPath(),"wpe-recovery-acceptance-*").Select(x=>Path.Combine(x,"agent.db")).Where(File.Exists).OrderByDescending(File.GetLastWriteTimeUtc)){var oldStore=new AgentSqliteStore(oldDatabase);var oldExecutor=new ReliableOrderExecutor(provider,oldStore,settings.Risk,SystemOrderPollScheduler.Instance,capabilities,true);await oldExecutor.RecoverPendingAsync(ct);}if((await provider.GetOpenOrdersAsync(Symbol,ct)).Any(x=>x.Symbol==Symbol))throw new InvalidOperationException("Recovery acceptance could not clear its prior Testnet residue through persisted recovery state.");}
            var rule=await provider.GetRulesAsync(Symbol,ct);var market=await provider.GetMarketAsync(Symbol,ct);if(rule.StepSize<=0||rule.TickSize<=0||rule.MinQuantity<=0||rule.MinNotional<=0||market.Price<=0)throw new InvalidOperationException("Recovery acceptance rule or market evidence is invalid.");capabilities=await new ProviderCapabilityProbe().ProbeAsync(provider,[Symbol],true,ct);if(!capabilities.TryGetValue(Symbol,out capability)||capability.Status!=CapabilityStatus.Available||!capability.CanTrade)throw new InvalidOperationException("Recovery acceptance mutation capability refresh failed.");
            var temp=Path.Combine(Path.GetTempPath(),"wpe-recovery-acceptance-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(temp);var database=Path.Combine(temp,"agent.db");var store=new AgentSqliteStore(database);executor=new ReliableOrderExecutor(provider,store,settings.Risk,SystemOrderPollScheduler.Instance,capabilities,true);var gateway=new TradingExecutionGateway(executor,store);var created=DateTimeOffset.UtcNow;var correlation="recovery-acceptance-"+Guid.NewGuid().ToString("N");var clientId=ClientId();var limit=rule.RoundPrice(market.Price*.95m);var quantity=Ceiling(Math.Max(rule.MinQuantity,rule.MinNotional*1.10m/limit),rule.StepSize);var intent=new ExecutionIntent(Symbol,PositionSide.Long,quantity,false,rule.RoundPrice(limit*.98m),rule.RoundPrice(market.Price*1.02m),clientId,"formal recovery timeout acceptance",DecisionAction.OpenLong,ExecutionOrderType.Limit,limit,market.Price);var leverage=Math.Min(5,rule.MaxLeverage);var intentHash=TradingExecutionGateway.ComputeIntentHash([intent],leverage,true);var request=new TradingApprovalRequest("recovery-request-"+Guid.NewGuid().ToString("N"),TradingAuthorizationMode.Review,correlation,intentHash,"recovery-acceptance",DeviceLicenseService.GetCurrentDeviceCode(),"recovery-session-"+Guid.NewGuid().ToString("N"),created,created.AddMinutes(2));var receipt=new TradingApprovalReceipt("recovery-receipt-"+Guid.NewGuid().ToString("N"),correlation,intentHash,request.UserId,request.DeviceId,request.SessionId,true,created,request.ExpiresAtUtc);if(!(await store.SaveTradingApprovalRequestAsync(request,ct)).Succeeded||!(await store.SaveTradingApprovalReceiptAsync(request.RequestId,receipt,ct)).Succeeded)throw new InvalidOperationException("Recovery acceptance approval persistence failed.");var risk=new DeterministicRiskReceipt("recovery-risk-"+Guid.NewGuid().ToString("N"),correlation,intentHash,true,created,created.AddMinutes(1));var authorization=new TradingAuthorizationRequest(TradingAuthorizationMode.Review,true,correlation,intentHash,request.UserId,request.DeviceId,request.SessionId,risk,receipt);ServiceLocator.SystemState.Status=AgentStatus.Running;
            var timedOut=false;var timeoutDiagnostic="none";try{var result=await gateway.ExecutePlanAsync(new(request.RequestId,authorization,[intent],leverage,true),ct);if(result.Executed)throw new InvalidDataException("Recovery timeout acceptance unexpectedly reported execution success.");timeoutDiagnostic=result.Code;}catch(InvalidOperationException ex){timedOut=true;timeoutDiagnostic=SensitiveDataRedactor.ForLog(ex.Message,120);}if(!timedOut)throw new InvalidOperationException("Recovery acceptance did not traverse the expected timeout failure path: "+timeoutDiagnostic);
            var terminal=await provider.FindOrderAsync(Symbol,clientId,ct);if(terminal is null||terminal.ClientOrderId!=clientId||terminal.ExecutedQuantity!=0||terminal.Status is not ("CANCELED" or "EXPIRED" or "REJECTED"))throw new InvalidOperationException("Recovery acceptance did not observe a zero-fill terminal timeout order: "+timeoutDiagnostic);
            var snapshot=new DurableExecutionIntentSnapshotV1(0,intent.Symbol,intent.Side.ToString(),intent.Quantity,intent.ReduceOnly,intent.StopLoss,intent.TakeProfit,intent.ClientOrderId,"recovery.timeout",intent.Action.ToString(),intent.OrderType.ToString(),intent.LimitPrice,intent.ExpectedPrice);var artifact=new DurableReviewExecutionArtifactV1(DurableReviewExecutionArtifactV1.Version,[snapshot],leverage,true,"binance-futures","Testnet","recovery-acceptance","v1",new DateTimeOffset(market.CollectedAt.ToUniversalTime()),"recovery-market-"+Hash(MarketFact(market))[..16],created,created.AddMinutes(5));
            var restartedStore=new AgentSqliteStore(database);var restartedExecutor=new ReliableOrderExecutor(provider,restartedStore,settings.Risk,SystemOrderPollScheduler.Instance,capabilities,true);var first=await restartedExecutor.ReconcileAsync(artifact,ct);var firstOrder=await provider.FindOrderAsync(Symbol,clientId,ct);var second=await restartedExecutor.ReconcileAsync(artifact,ct);var secondOrder=await provider.FindOrderAsync(Symbol,clientId,ct);
            if(first.State!=DurableReviewReconciliationState.Failed||second.State!=DurableReviewReconciliationState.Failed||first.Code!="review.reconcile-order-terminal"||second.Code!=first.Code||firstOrder is null||secondOrder is null||OrderHash(firstOrder)!=OrderHash(secondOrder))throw new InvalidOperationException($"Recovery restart reconciliation mismatch: first={first.State}/{first.Code}; second={second.State}/{second.Code}; orders={(firstOrder is not null&&secondOrder is not null?"present":"missing")}; stable={(firstOrder is not null&&secondOrder is not null&&OrderHash(firstOrder)==OrderHash(secondOrder))}.");
            var finalPositions=await provider.GetPositionsAsync(ct);var finalOrders=await provider.GetOpenOrdersAsync(Symbol,ct);var flat=!finalPositions.Any(x=>x.Symbol==Symbol&&x.Quantity>0);var noOpen=!finalOrders.Any(x=>x.Symbol==Symbol);if(!flat||!noOpen)throw new InvalidOperationException("Recovery acceptance left Testnet position or order residue.");var observed=DateTimeOffset.UtcNow;var submission=Hash(string.Join('|',correlation,clientId,intentHash));var terminalHash=OrderHash(terminal);var firstHash=Hash(string.Join('|',first.State,first.Code,OrderHash(firstOrder)));var secondHash=Hash(string.Join('|',second.State,second.Code,OrderHash(secondOrder)));
            foreach(var requirement in new[]{RecoveryAggregateEvidenceCanonicalizerV1.TimeoutRequirement,RecoveryAggregateEvidenceCanonicalizerV1.NoResubmitRequirement}){var evidence=RecoveryAggregateEvidenceCanonicalizerV1.Create(requirement,candidate,observed,submission,terminalHash,firstHash,secondHash,first.Code,second.Code,true,true,false,flat,noOpen);if(!RecoveryAggregateEvidenceCanonicalizerV1.IsCanonical(evidence,DateTimeOffset.UtcNow))throw new InvalidOperationException("Generated Recovery evidence is ineligible: "+requirement);var name=requirement+".json";await AtomicWrite(Path.Combine(directory,name),evidence.CanonicalBytes,ct);if(!RecoveryAggregateEvidenceCanonicalizerV1.TryParseCanonical(await File.ReadAllBytesAsync(Path.Combine(directory,name),ct),out var reread)||!RecoveryAggregateEvidenceCanonicalizerV1.IsCanonical(reread,DateTimeOffset.UtcNow))throw new InvalidOperationException("Persisted Recovery evidence is invalid: "+requirement);files.Add(new{name,evidence.RequirementId,evidence.CanonicalSha256,evidence.ObservedAtUtc});}
        }
        catch(OperationCanceledException)when(ct.IsCancellationRequested){throw;}
        catch(Exception ex){errors.Add("recovery-aggregate-acceptance.failed:"+ex.GetType().Name+":"+SensitiveDataRedactor.ForLog(ex.Message,180));}
        finally
        {
            if(executor is not null&&provider is not null)try{using var cleanup=new CancellationTokenSource(TimeSpan.FromSeconds(60));var hasResidue=(await provider.GetOpenOrdersAsync(Symbol,cleanup.Token)).Any(x=>x.Symbol==Symbol)||(await provider.GetPositionsAsync(cleanup.Token)).Any(x=>x.Symbol==Symbol&&x.Quantity>0);if(hasResidue)await executor.RecoverPendingAsync(cleanup.Token);var remains=(await provider.GetOpenOrdersAsync(Symbol,cleanup.Token)).Any(x=>x.Symbol==Symbol)||(await provider.GetPositionsAsync(cleanup.Token)).Any(x=>x.Symbol==Symbol&&x.Quantity>0);if(remains)errors.Add("recovery-aggregate-acceptance.cleanup-residual");}catch(Exception){errors.Add("recovery-aggregate-acceptance.cleanup-failed");}ServiceLocator.SystemState.Status=originalStatus;if(provider is not null)await provider.DisposeAsync();
        }
        var manifest=JsonSerializer.SerializeToUtf8Bytes(new{schema="wpe.recovery-aggregate-acceptance-run/1.0",candidateVersion=candidate.Version,candidateSha256=candidate.Sha256,completedAtUtc=DateTimeOffset.UtcNow,success=errors.Count==0,files,errors});await AtomicWrite(Path.Combine(directory,"manifest.json"),manifest,CancellationToken.None);await AtomicWrite(Path.Combine(directory,"manifest.sha256"),Encoding.ASCII.GetBytes(Hash(manifest)),CancellationToken.None);return new(errors.Count==0,directory,errors);
    }
    private static decimal Ceiling(decimal value,decimal step)=>step<=0?value:Math.Ceiling(value/step)*step;private static string ClientId(){var raw=$"WPE-RECACC-{DateTime.UtcNow:HHmmss}-{Guid.NewGuid():N}";return raw[..Math.Min(36,raw.Length)];}
    private static string MarketFact(MarketEvidence x)=>string.Join('|',x.Symbol,x.Price.ToString(CultureInfo.InvariantCulture),x.CollectedAt.ToUniversalTime().ToString("O",CultureInfo.InvariantCulture));private static string OrderHash(ExchangeOrder x)=>Hash(string.Join('|',x.Symbol,x.OrderId,x.ClientOrderId,x.Status,x.ExecutedQuantity.ToString(CultureInfo.InvariantCulture),x.AvgPrice.ToString(CultureInfo.InvariantCulture),x.Type,x.PositionSide));private static string Hash(string text)=>Hash(Encoding.UTF8.GetBytes(text));private static string Hash(byte[] bytes)=>Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();private static async Task<MarketAcceptanceCandidateV1> Candidate(CancellationToken ct){var a=Assembly.GetExecutingAssembly();return new(a.GetName().Version?.ToString()??"unknown",Hash(await File.ReadAllBytesAsync(a.Location,ct)));}private static async Task AtomicWrite(string path,byte[] bytes,CancellationToken ct){var temp=path+"."+Guid.NewGuid().ToString("N")+".tmp";await File.WriteAllBytesAsync(temp,bytes,ct);File.Move(temp,path,false);}
}
