using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.IO;
using System.Net.Http;
using WpeAgent.AgentServices;
using 币安量化机器人.Services;
using 币安量化机器人.Services.Agent;
using 币安量化机器人.Services.Exchange;

namespace WpeAgent.ModelOff;

public sealed record ResearchAggregateAcceptanceRunResult(bool Success,string ArtifactDirectory,IReadOnlyList<string> Errors);

public static class ResearchAggregateAcceptanceRunnerV1
{
    private static readonly IReadOnlyDictionary<string,string[]> NewsHosts=new Dictionary<string,string[]>(StringComparer.OrdinalIgnoreCase){["SEC"]=["sec.gov"],["CFTC"]=["cftc.gov"],["Federal Reserve"]=["federalreserve.gov"],["ECB"]=["ecb.europa.eu"],["CoinDesk"]=["coindesk.com"],["Cointelegraph"]=["cointelegraph.com"],["Google News"]=["news.google.com"]};

    public static async Task<ResearchAggregateAcceptanceRunResult> RunAsync(CancellationToken ct=default)
    {
        var directory=Path.Combine(AppDataPaths.TestArtifactsDirectory,"research-aggregate-acceptance",DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(directory);var errors=new List<string>();var files=new List<object>();var assembly=Assembly.GetExecutingAssembly();var candidateBytes=await File.ReadAllBytesAsync(assembly.Location,ct);var candidate=new MarketAcceptanceCandidateV1(assembly.GetName().Version?.ToString()??"unknown",Hash(candidateBytes));
        try
        {
            var now=DateTimeOffset.UtcNow;await using var marketSource=new BinanceTestnetMarketAcceptanceSourceV1();var market=await marketSource.ReadAsync("BTCUSDT",ct);if(!MarketEvidenceProvenanceCanonicalizerV1.IsCanonical(market))throw new InvalidOperationException("Research Market source is noncanonical.");
            await using var adapter=new BinanceFuturesAdapter(new ExchangeConnectionProfile{Id="research-acceptance",ProviderId="binance-futures",DisplayName="Binance Futures Testnet research read-only",IsTestnet=true,ExecutionEnabled=false,Endpoint="https://testnet.binancefuture.com",TimeoutSeconds=20},string.Empty,string.Empty);market=BindFreshTechnicalMarket(market,await adapter.GetCandlesAsync("BTCUSDT","1m",240,ct),DateTime.UtcNow);var fundamentals=await adapter.GetInstrumentFundamentalsAsync(["BTCUSDT"],ct);var fundamental=fundamentals.SingleOrDefault()??throw new InvalidOperationException("Research Fundamental source is unavailable.");if(!CryptoInstrumentFundamentalCanonicalizerV1.IsCanonical(fundamental,DateTimeOffset.UtcNow))throw new InvalidOperationException("Research Fundamental source is noncanonical.");
            using var blsHttp=new HttpClient{Timeout=TimeSpan.FromSeconds(20)};var bls=new BlsMacroDataClient(new HttpBlsMacroDataTransport(blsHttp));var macros=new List<BlsMacroObservationV1>();foreach(var id in new[]{"CUUR0000SA0","LNS14000000"}){var fetchedAt=DateTimeOffset.UtcNow;var result=await bls.FetchLatestAsync(id,fetchedAt.Year-1,fetchedAt.Year,fetchedAt,ct);if(result.Status!=BlsMacroFetchStatus.Available||result.Observation is null)throw new InvalidOperationException($"Research Macro source unavailable: {id}:{result.ReasonCode}");macros.Add(result.Observation);}
            var newsResult=await new NewsResearchService().CollectAsync(["BTCUSDT"],ct);now=DateTimeOffset.UtcNow;var news=newsResult.Items.Where(x=>ValidNews(x,now)).OrderByDescending(x=>x.PublishedAt??x.CollectedAt).Take(12).ToArray();if(news.Length==0)throw new InvalidOperationException("Research News sources are unavailable or invalid.");
            var sources=Sources(market,fundamental,macros,news,now);var outputs=Outputs(market,fundamental,macros[0],news,now);var artifacts=new[]{ResearchAggregateEvidenceCanonicalizerV1.Create(ResearchAggregateEvidenceCanonicalizerV1.LiveSourceRequirement,"BTCUSDT",candidate,now,sources),ResearchAggregateEvidenceCanonicalizerV1.Create(ResearchAggregateEvidenceCanonicalizerV1.ModelOffCycleRequirement,"BTCUSDT",candidate,now,sources,outputs)};
            foreach(var artifact in artifacts){if(!ResearchAggregateEvidenceCanonicalizerV1.IsCanonical(artifact,DateTimeOffset.UtcNow))throw new InvalidOperationException($"Research evidence is ineligible: {artifact.RequirementId}");var name=artifact.RequirementId+".json";var path=Path.Combine(directory,name);await AtomicWriteAsync(path,artifact.CanonicalBytes,ct);var persisted=await File.ReadAllBytesAsync(path,ct);if(!ResearchAggregateEvidenceCanonicalizerV1.TryParseCanonical(persisted,out var reread)||!ResearchAggregateEvidenceCanonicalizerV1.IsCanonical(reread,DateTimeOffset.UtcNow))throw new InvalidOperationException($"Persisted Research evidence is invalid: {artifact.RequirementId}");files.Add(new{name,artifact.RequirementId,artifact.CanonicalSha256,artifact.ObservedAtUtc,sources=artifact.Sources.Count,outputs=artifact.Outputs.Count});}
        }
        catch(OperationCanceledException)when(ct.IsCancellationRequested){throw;}
        catch(Exception ex){errors.Add("research-aggregate-acceptance.failed:"+SensitiveDataRedactor.ForLog(ex.Message,220));}
        var manifest=JsonSerializer.SerializeToUtf8Bytes(new{schema="wpe.research-aggregate-acceptance-run/1.0",candidateVersion=candidate.Version,candidateSha256=candidate.Sha256,provider="multi-source-research",environment="Target",symbol="BTCUSDT",mainnetEnabled=false,mutationEnabled=false,completedAtUtc=DateTimeOffset.UtcNow,success=errors.Count==0,files,errors});await AtomicWriteAsync(Path.Combine(directory,"manifest.json"),manifest,ct);await AtomicWriteAsync(Path.Combine(directory,"manifest.sha256"),Encoding.ASCII.GetBytes(Hash(manifest)),ct);return new(errors.Count==0,directory,errors);
    }

    private static ResearchAcceptanceSourceV1[] Sources(MarketEvidence market,CryptoInstrumentFundamentalV1 fundamental,IReadOnlyList<BlsMacroObservationV1> macros,IReadOnlyList<NewsEvidence> news,DateTimeOffset now)
    {
        var result=new List<ResearchAcceptanceSourceV1>{new("Market","BTCUSDT","binance-futures",new DateTimeOffset(market.CollectedAt),market.Provenance!.CanonicalSha256),new("Fundamental","exchange-info-BTCUSDT","binance-futures",fundamental.ObservedAtUtc,fundamental.CanonicalSha256)};result.AddRange(macros.Select(x=>new ResearchAcceptanceSourceV1("Macro",x.Facts.GetProperty("indicatorId").GetString()!,"bls-public-api-v2",x.Source.AsOfUtc!.Value,NormalizeHash(x.Source.ArtifactHash!))));result.AddRange(news.GroupBy(x=>x.Source,StringComparer.OrdinalIgnoreCase).Select(group=>{var id=group.Key.ToLowerInvariant().Replace(' ','-');var hash=Hash(Encoding.UTF8.GetBytes(string.Join('\n',group.Select(NewsHash).Order(StringComparer.Ordinal))));return new ResearchAcceptanceSourceV1("News",id,id,group.Max(x=>Utc(x.PublishedAt??x.CollectedAt)),hash);}));return result.ToArray();
    }

    private static ResearchAcceptanceOutputV1[] Outputs(MarketEvidence market,CryptoInstrumentFundamentalV1 fundamental,BlsMacroObservationV1 macro,IReadOnlyList<NewsEvidence> news,DateTimeOffset now)
    {
        var newsHash=Hash(Encoding.UTF8.GetBytes(string.Join('\n',news.Select(NewsHash).Order(StringComparer.Ordinal))));var newsSource=new ModelOffSourceV1("news-live-set",ModelOffSourceKindV1.News,news.Max(x=>Utc(x.PublishedAt??x.CollectedAt)),now,ModelOffSourceStatusV1.Available,"sha256:"+newsHash);var newsFacts=JsonSerializer.SerializeToElement(new{schema="wpe.news-live-set/1.0",symbol="BTCUSDT",itemCount=news.Count,artifactSha256=newsHash});
        var technicalFacts=JsonSerializer.SerializeToElement(new{schema="wpe.technical-assessment/1.0",symbol="BTCUSDT",marketSymbol="BTCUSDT",observedAtUtc=new DateTimeOffset(market.CollectedAt),marketEvidenceSha256=market.Provenance!.CanonicalSha256,rsi=market.Rsi,trend15m=market.Trend15m,trend1h=market.Trend1h,trend4h=market.Trend4h});var technicalSource=new ModelOffSourceV1("market:BTCUSDT",ModelOffSourceKindV1.Market,new DateTimeOffset(market.CollectedAt),now,ModelOffSourceStatusV1.Available,"sha256:"+market.Provenance.CanonicalSha256);
        var fundamentalFacts=JsonSerializer.SerializeToElement(new{schema=fundamental.Schema,providerId=fundamental.ProviderId,environment=fundamental.Environment,symbol=fundamental.Symbol,nativeSymbol=fundamental.NativeSymbol,baseAsset=fundamental.BaseAsset,quoteAsset=fundamental.QuoteAsset,marginAsset=fundamental.MarginAsset,contractType=fundamental.ContractType,tradingStatus=fundamental.TradingStatus,onboardAtUtc=fundamental.OnboardAtUtc,observedAtUtc=fundamental.ObservedAtUtc,sourceArtifactSha256=fundamental.SourceArtifactSha256,canonicalSha256=fundamental.CanonicalSha256});var fundamentalSource=new ModelOffSourceV1("fundamental:BTCUSDT",ModelOffSourceKindV1.Fundamental,fundamental.ObservedAtUtc,now,ModelOffSourceStatusV1.Available,"sha256:"+fundamental.CanonicalSha256);
        var backtest=Backtest(market,now);var backtestFacts=JsonSerializer.SerializeToElement(new{schema=backtest.Schema,symbol=backtest.Symbol,strategyId=backtest.StrategyId,strategyVersion=backtest.StrategyVersion,validatedAtUtc=backtest.ValidatedAtUtc,sampleSize=backtest.SampleSize,trades=backtest.Trades,outOfSampleTrades=backtest.OutOfSampleTrades,coverageDays=backtest.CoverageDays,winRate=backtest.WinRate,profitFactor=backtest.ProfitFactor,expectancy=backtest.Expectancy,maxDrawdown=backtest.MaxDrawdown,sharpe=backtest.Sharpe,outOfSampleReturn=backtest.OutOfSampleReturn,walkForwardScore=backtest.WalkForwardScore,monteCarloLossProbability=backtest.MonteCarloLossProbability,qualityScore=backtest.QualityScore,approved=backtest.Approved,promoted=backtest.Promoted,canonicalSha256=backtest.CanonicalSha256});var backtestSource=new ModelOffSourceV1("backtest:BTCUSDT:acceptance-baseline:acceptance-baseline-v1",ModelOffSourceKindV1.Strategy,now,now,ModelOffSourceStatusV1.Available,"sha256:"+backtest.CanonicalSha256);
        var inputs=new[]{new ModelOffResearchInputV1(ModelOffResearchCapabilityV1.News,"research-news","research-acceptance",now,DeterministicResearchCapabilityProducerV1.InputSchema,"wpe.news-method","1.0",[newsSource],newsFacts,[]),new ModelOffResearchInputV1(ModelOffResearchCapabilityV1.Macro,"research-macro","research-acceptance",now,DeterministicResearchCapabilityProducerV1.InputSchema,"wpe.macro-method","1.0",[macro.Source],macro.Facts,[]),new ModelOffResearchInputV1(ModelOffResearchCapabilityV1.Technical,"research-technical","research-acceptance",now,DeterministicResearchCapabilityProducerV1.InputSchema,"wpe.technical-method","1.0",[technicalSource],technicalFacts,[]),new ModelOffResearchInputV1(ModelOffResearchCapabilityV1.Fundamental,"research-fundamental","research-acceptance",now,DeterministicResearchCapabilityProducerV1.InputSchema,"wpe.fundamental-method","1.0",[fundamentalSource],fundamentalFacts,[]),new ModelOffResearchInputV1(ModelOffResearchCapabilityV1.Backtest,"research-backtest","research-acceptance",now,DeterministicResearchCapabilityProducerV1.InputSchema,"wpe.backtest-method","1.0",[backtestSource],backtestFacts,[])};return inputs.Select(x=>{var output=DeterministicResearchCapabilityProducerV1.Produce(x);if(!ModelOffEligibilityV1.IsEligibleForDownstream(output))throw new InvalidOperationException($"Research capability abstained: {x.Capability}:{string.Join(',',output.Uncertainty.ReasonCodes)}");var document=ModelOffCanonicalSerializerV1.Serialize(output);return new ResearchAcceptanceOutputV1(x.Capability.ToString(),document.Sha256,document.Utf8Bytes);}).ToArray();
    }

    private static BacktestValidationFactV1 Backtest(MarketEvidence market,DateTimeOffset now)
    {
        var closes=market.Candles.OrderBy(x=>x.OpenTime).Select(x=>(double)x.Close).Where(x=>double.IsFinite(x)&&x>0).ToArray();if(closes.Length<31)throw new InvalidOperationException("Research Backtest requires confirmed history.");var returns=closes.Zip(closes.Skip(1),(a,b)=>b/a-1).ToArray();var gains=returns.Where(x=>x>0).Sum();var losses=-returns.Where(x=>x<0).Sum();var mean=returns.Average();var variance=returns.Select(x=>(x-mean)*(x-mean)).Average();var equity=1d;var peak=1d;var maxDrawdown=0d;foreach(var value in returns){equity*=1+value;peak=Math.Max(peak,equity);maxDrawdown=Math.Max(maxDrawdown,peak<=0?1:(peak-equity)/peak);}var oos=Math.Max(1,returns.Length/5);var first=returns.Take(returns.Length-oos).DefaultIfEmpty().Average();var second=returns.TakeLast(oos).Average();return BacktestValidationCanonicalizerV1.Create("BTCUSDT","acceptance-baseline","acceptance-baseline-v1",now,returns.Length,returns.Length,oos,Math.Max(1,(int)Math.Ceiling((market.Candles[^1].OpenTime-market.Candles[0].OpenTime).TotalDays)),returns.Count(x=>x>0)/(double)returns.Length,losses==0?999:gains/losses,mean,Math.Clamp(maxDrawdown,0,1),variance==0?0:mean/Math.Sqrt(variance)*Math.Sqrt(252),returns.TakeLast(oos).Aggregate(1d,(a,x)=>a*(1+x))-1,Math.Clamp(1-Math.Abs(first-second)*100,0,1),returns.Count(x=>x<0)/(double)returns.Length,Math.Clamp(market.Quality.QualityScore/100d,0,1),false,false);
    }

    internal static MarketEvidence BindFreshTechnicalMarket(MarketEvidence baseMarket,IReadOnlyList<CandleEvidence> oneMinuteCandles,DateTime observedAtUtc)
    {
        var confirmed=ConfirmedMarketCandlesV1.Select(oneMinuteCandles,"1m",observedAtUtc);var snapshot=ConfirmedMarketCandlesV1.Analyze(baseMarket.Symbol,"1m",confirmed,observedAtUtc);var value=new MarketEvidence(baseMarket.Symbol,snapshot.Price,snapshot.Support,snapshot.Resistance,snapshot.Rsi,baseMarket.Trend15m,baseMarket.Trend1h,baseMarket.Trend4h,baseMarket.Derivatives,snapshot.Timestamp){Candles=confirmed,Quality=baseMarket.Quality};return value with{Provenance=MarketEvidenceProvenanceCanonicalizerV1.Create(value,"binance-futures","Testnet")};
    }

    private static bool ValidNews(NewsEvidence value,DateTimeOffset now){if(!NewsHosts.TryGetValue(value.Source,out var hosts)||!Uri.TryCreate(value.Url,UriKind.Absolute,out var uri)||uri.Scheme!=Uri.UriSchemeHttps||!hosts.Any(x=>uri.Host.Equals(x,StringComparison.OrdinalIgnoreCase)||uri.Host.EndsWith("."+x,StringComparison.OrdinalIgnoreCase)))return false;var at=Utc(value.PublishedAt??value.CollectedAt);return at<=now&&now-at<=TimeSpan.FromDays(7)&&!string.IsNullOrWhiteSpace(value.Title)&&value.Confidence is>=0 and<=1&&double.IsFinite(value.Sentiment);}
    private static DateTimeOffset Utc(DateTime value)=>new(DateTime.SpecifyKind(value.ToUniversalTime(),DateTimeKind.Utc));private static string NewsHash(NewsEvidence value)=>Hash(Encoding.UTF8.GetBytes(string.Join('|',value.Source,value.Title,value.Url,Utc(value.PublishedAt??value.CollectedAt).ToString("O"),value.DuplicateGroup,value.EventType,value.Confidence,value.Sentiment)));
    private static string NormalizeHash(string value)=>value.StartsWith("sha256:",StringComparison.Ordinal)?value[7..]:value;private static string Hash(byte[] bytes)=>Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();private static async Task AtomicWriteAsync(string path,byte[] bytes,CancellationToken ct){var temporary=path+"."+Guid.NewGuid().ToString("N")+".tmp";await File.WriteAllBytesAsync(temporary,bytes,ct);File.Move(temporary,path,false);}
}
