using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.IO;
using Microsoft.Data.Sqlite;
using WpeAgent.TradingAuthorization;
using 币安量化机器人.Services.Agent;
using 币安量化机器人.Services.Exchange;

namespace WpeAgent.ModelOff;

public sealed record RiskAggregateAcceptanceRunResult(bool Success,string ArtifactDirectory,IReadOnlyList<string> Errors);

public static class RiskAggregateAcceptanceRunnerV1
{
    private sealed record LiveFacts(DateTimeOffset ObservedAtUtc,string PermissionHash,string AccountHash,string PositionsHash,string MarketHash,string RuleHash,AccountSnapshot Account,IReadOnlyList<ManagedPosition> Positions,MarketEvidence Market,TradingRule Rule);

    public static async Task<RiskAggregateAcceptanceRunResult> RunAsync(CancellationToken ct=default)
    {
        var root=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"WPE Agent","Runtime","TestArtifacts");var directory=Path.Combine(root,"risk-aggregate-acceptance",DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(directory);var errors=new List<string>();var files=new List<object>();var assembly=Assembly.GetExecutingAssembly();var candidate=new MarketAcceptanceCandidateV1(assembly.GetName().Version?.ToString()??"unknown",Hash(await File.ReadAllBytesAsync(assembly.Location,ct)));
        try
        {
            var settingsStore=new AgentSettingsStore();var settings=settingsStore.Load();if(settingsStore.LastLoadDiagnostic is not null||settings.Environment!=ExchangeEnvironment.Testnet)throw new InvalidOperationException("Risk acceptance requires valid Testnet settings.");var configured=settingsStore.GetActiveExchange(settings);if(!configured.IsTestnet||!configured.ProviderId.Equals("binance-futures",StringComparison.OrdinalIgnoreCase)||!ProviderEndpointPolicy.IsOfficialHttpsOrigin(configured.Endpoint,"testnet.binancefuture.com"))throw new InvalidOperationException("Risk acceptance requires the official Binance Futures Testnet profile.");var credentials=settingsStore.GetExchangeCredentials(configured);if(!credentials.TryGetValue("apiKey",out var key)||!credentials.TryGetValue("secret",out var secret)||string.IsNullOrWhiteSpace(key)||string.IsNullOrWhiteSpace(secret))throw new InvalidOperationException("Risk acceptance Testnet credentials are unavailable.");var profile=new ExchangeConnectionProfile{Id="risk-acceptance",ProviderId="binance-futures",DisplayName="Binance Futures Testnet risk read-only",Enabled=true,ExecutionEnabled=false,IsTestnet=true,Endpoint=configured.Endpoint,UseProxy=configured.UseProxy,ProxyUrl=configured.ProxyUrl,ReceiveWindow=configured.ReceiveWindow,TimeoutSeconds=configured.TimeoutSeconds};
            await using var adapter=new BinanceFuturesAdapter(profile,key,secret);key=string.Empty;secret=string.Empty;var first=await ReadFacts(adapter,ct);if(first.Account.Equity<=0)throw new InvalidOperationException("Risk acceptance requires positive Testnet equity.");var inputFacts=new[]{Fact("permission",first.PermissionHash,first.ObservedAtUtc),Fact("account",first.AccountHash,first.ObservedAtUtc),Fact("positions",first.PositionsHash,first.ObservedAtUtc),Fact("market",first.MarketHash,first.ObservedAtUtc),Fact("rule",first.RuleHash,first.ObservedAtUtc)};var contract=new RiskAndPositionPlanner().EvaluateModelOffIntent(new(DecisionAction.OpenLong,"BTCUSDT",first.ObservedAtUtc,TimeSpan.FromMinutes(5),false,inputFacts));if(!contract.EligibleForRiskIncrease)throw new InvalidOperationException("Deterministic Risk contract rejected current Testnet facts.");var entry=first.Market.Price;var decision=new DecisionPlan{Action=DecisionAction.OpenLong,Instrument="BTCUSDT",TargetTier=1,EntryPrice=entry,StopLossPrice=entry*.99m,TakeProfitPrice=entry*1.021m,RiskRewardRatio=2.1,StrategyVersion="risk-acceptance-v1",Reason="risk acceptance"};var planned=new RiskAndPositionPlanner().Plan(decision,new EvidencePack{CollectedAt=first.ObservedAtUtc.UtcDateTime,Completeness=100,Account=first.Account,Positions=first.Positions,Markets=new Dictionary<string,MarketEvidence>(StringComparer.OrdinalIgnoreCase){{"BTCUSDT",first.Market}}},first.Rule,settings.Risk);if(planned.Intents.Count!=1||planned.Intents[0].ReduceOnly)throw new InvalidOperationException("Current Testnet account did not produce one bounded risk-increasing intent.");var intent=planned.Intents[0];var created=DateTimeOffset.UtcNow;var artifact=new DurableExecutionArtifactV2(DurableExecutionArtifactV2.Version,"risk-acceptance-"+Guid.NewGuid().ToString("N"),[Snapshot(intent)],Math.Max(1,Math.Min(settings.Risk.Leverage,first.Rule.MaxLeverage)),settings.Risk.Isolated,"binance-futures","Testnet","risk-acceptance","v1",new DateTimeOffset(first.Market.CollectedAt.ToUniversalTime()),"risk-live-"+first.MarketHash[..16],created,created.AddMinutes(2));var hashes=DurableExecutionArtifactCanonicalizerV2.ComputeHashes(artifact);var intentHash=Raw(contract.IntentSha256);var ledgerHash=Raw(contract.LedgerSha256);var pre=RiskAggregateEvidenceCanonicalizerV1.Create(RiskAggregateEvidenceCanonicalizerV1.PreauthorizationRequirement,candidate,first.ObservedAtUtc,first.PermissionHash,first.AccountHash,first.PositionsHash,first.MarketHash,first.RuleHash,intentHash,ledgerHash,hashes.IntentHash,true);
            var second=await ReadFacts(adapter,ct);var temp=Path.Combine(Path.GetTempPath(),"wpe-risk-acceptance-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(temp);try{var clock=second.ObservedAtUtc;var store=new AgentSqliteStore(Path.Combine(temp,"agent.db"),()=>clock);var receipt=new DeterministicRiskReceipt("risk-live-receipt",artifact.CorrelationId,hashes.IntentHash,true,clock.AddSeconds(-1),clock.AddMinutes(1),null,hashes.ArtifactHash);if(!(await store.SaveAutomaticExecutionAsync(artifact.CorrelationId,artifact,ct)).Succeeded||!(await store.RecordAutomaticRiskDecisionAsync(artifact.CorrelationId,receipt,ct)).Succeeded||!(await store.TryClaimAutomaticExecutionAsync(artifact.CorrelationId,"risk-acceptance",TimeSpan.FromSeconds(30),ct)).Claimed||!(await store.TryTransitionAutomaticExecutionAsync(artifact.CorrelationId,AutomaticExecutionQueueStatus.Claimed,AutomaticExecutionQueueStatus.Executing,"risk-acceptance","automatic.executing",ct)).Succeeded)throw new InvalidOperationException("Risk authority persistence chain failed.");var authority=new PersistedAutomaticPreMutationAuthority(store,()=>clock);var current=await authority.RecheckAsync(artifact,receipt,AutomaticMutationPolicyV1.Hash,ct);var allowed=AutomaticPreMutationAuthorityContractV1.Evaluate(current,artifact,hashes,receipt,clock);var stale=AutomaticPreMutationAuthorityContractV1.Evaluate(current with{AsOfUtc=clock.AddSeconds(-6)},artifact,hashes,receipt,clock);var conflicting=AutomaticPreMutationAuthorityContractV1.Evaluate(current with{PolicyHash=new string('0',64)},artifact,hashes,receipt,clock);var toctou=RiskAggregateEvidenceCanonicalizerV1.Create(RiskAggregateEvidenceCanonicalizerV1.ToctouRequirement,candidate,first.ObservedAtUtc,first.PermissionHash,first.AccountHash,first.PositionsHash,first.MarketHash,first.RuleHash,intentHash,ledgerHash,hashes.IntentHash,true,second.ObservedAtUtc,second.AccountHash,second.PositionsHash,second.MarketHash,allowed,stale,conflicting,false);foreach(var evidence in new[]{pre,toctou}){if(!RiskAggregateEvidenceCanonicalizerV1.IsCanonical(evidence,DateTimeOffset.UtcNow))throw new InvalidOperationException($"Risk evidence is ineligible: {evidence.RequirementId}");var name=evidence.RequirementId+".json";var path=Path.Combine(directory,name);await AtomicWrite(path,evidence.CanonicalBytes,ct);if(!RiskAggregateEvidenceCanonicalizerV1.TryParseCanonical(await File.ReadAllBytesAsync(path,ct),out var reread)||!RiskAggregateEvidenceCanonicalizerV1.IsCanonical(reread,DateTimeOffset.UtcNow))throw new InvalidOperationException($"Persisted Risk evidence is invalid: {evidence.RequirementId}");files.Add(new{name,evidence.RequirementId,evidence.CanonicalSha256,evidence.ObservedAtUtc});}}
            finally{SqliteConnection.ClearAllPools();try{Directory.Delete(temp,true);}catch(IOException){}}
        }
        catch(OperationCanceledException)when(ct.IsCancellationRequested){throw;}
        catch(Exception ex){errors.Add("risk-aggregate-acceptance.failed:"+ex.GetType().Name+":"+Safe(ex.Message));}
        var manifest=JsonSerializer.SerializeToUtf8Bytes(new{schema="wpe.risk-aggregate-acceptance-run/1.0",candidateVersion=candidate.Version,candidateSha256=candidate.Sha256,provider="binance-futures",environment="Testnet",symbol="BTCUSDT",mainnetEnabled=false,mutationEnabled=false,completedAtUtc=DateTimeOffset.UtcNow,success=errors.Count==0,files,errors});await AtomicWrite(Path.Combine(directory,"manifest.json"),manifest,ct);await AtomicWrite(Path.Combine(directory,"manifest.sha256"),Encoding.ASCII.GetBytes(Hash(manifest)),ct);return new(errors.Count==0,directory,errors);
    }

    private static async Task<LiveFacts> ReadFacts(BinanceFuturesAdapter adapter,CancellationToken ct)
    {
        var health=await adapter.HealthCheckAsync(ct);var permission=await adapter.CheckPermissionsAsync(ct);var account=await adapter.GetAccountAsync(ct);var positions=await adapter.GetPositionsAsync(ct);var market=await adapter.GetMarketAsync("BTCUSDT",ct);var rule=await adapter.GetRulesAsync("BTCUSDT",ct);var observed=DateTimeOffset.UtcNow;if(!health.Healthy)throw new InvalidOperationException("risk.live.health-unavailable");if(!permission.CanRead)throw new InvalidOperationException("risk.live.read-permission-missing");if(!permission.CanTrade)throw new InvalidOperationException("risk.live.trade-permission-missing");if(permission.CanWithdraw)throw new InvalidOperationException("risk.live.withdraw-permission-unsafe");if(account.Timestamp.Kind!=DateTimeKind.Utc||DateTime.UtcNow-account.Timestamp>TimeSpan.FromMinutes(2))throw new InvalidOperationException("risk.live.account-stale");if(market.Price<=0||market.CollectedAt.Kind!=DateTimeKind.Utc||DateTime.UtcNow-market.CollectedAt>MarketAggregateEvidenceCanonicalizerV1.MaximumSourceAge)throw new InvalidOperationException("risk.live.market-stale");market=market with{Provenance=MarketEvidenceProvenanceCanonicalizerV1.Create(market,"binance-futures","Testnet")};if(!MarketEvidenceProvenanceCanonicalizerV1.IsCanonical(market))throw new InvalidOperationException("risk.live.market-noncanonical");var permissionHash=Hash(JsonSerializer.SerializeToUtf8Bytes(new{permission.CanRead,permission.CanTrade,permission.CanWithdraw,accountIdentitySha256=Hash(Encoding.UTF8.GetBytes(permission.AccountId??string.Empty))}));var accountHash=Hash(JsonSerializer.SerializeToUtf8Bytes(new{account.WalletBalance,account.AvailableBalance,account.Equity,timestamp=new DateTimeOffset(account.Timestamp.ToUniversalTime())}));var positionHash=Hash(JsonSerializer.SerializeToUtf8Bytes(positions.OrderBy(x=>x.Symbol,StringComparer.Ordinal).ThenBy(x=>x.Side).Select(x=>new{x.Symbol,side=x.Side.ToString(),x.Quantity,x.EntryPrice,x.MarkPrice,x.UnrealizedPnl,x.Leverage,x.Isolated,x.LiquidationPrice})));var ruleHash=Hash(JsonSerializer.SerializeToUtf8Bytes(rule));return new(observed,permissionHash,accountHash,positionHash,market.Provenance!.CanonicalSha256,ruleHash,account,positions,market,rule);
    }
    private static ModelOffInputFactV1 Fact(string id,string hash,DateTimeOffset at)=>new(id,ModelOffInputStateV1.Available,"sha256:"+hash,at);
    private static DurableExecutionIntentSnapshotV1 Snapshot(ExecutionIntent x)=>new(0,x.Symbol,x.Side.ToString(),x.Quantity,x.ReduceOnly,x.StopLoss,x.TakeProfit,x.ClientOrderId,"risk.live-preauthorization",x.Action.ToString(),x.OrderType.ToString(),x.LimitPrice,x.ExpectedPrice);
    private static string Raw(string value)=>value.StartsWith("sha256:",StringComparison.Ordinal)?value[7..]:value;
    private static string Safe(string value)=>new(value.Where(x=>char.IsAsciiLetterOrDigit(x)||x is ' ' or '-' or '_' or '.' or ':').Take(180).ToArray());
    private static string Hash(byte[] bytes)=>Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
    private static async Task AtomicWrite(string path,byte[] bytes,CancellationToken ct){var temp=path+"."+Guid.NewGuid().ToString("N")+".tmp";await File.WriteAllBytesAsync(temp,bytes,ct);File.Move(temp,path,false);}
}
