using System.Globalization;

namespace 币安量化机器人.Services.Agent;

public sealed record TeacherRecommendationOutcomeV2(string OutcomeId,string Schema,string RecommendationId,int RecommendationVersion,string Instrument,string Benchmark,string Horizon,DateTimeOffset IssuedAtUtc,DateTimeOffset EvaluatedAtUtc,decimal EntryPrice,decimal ExitPrice,decimal InstrumentReturnPct,decimal BenchmarkReturnPct,decimal RelativeReturnPct,decimal MaximumFavorableExcursionPct,decimal MaximumAdverseExcursionPct,bool InvalidatedBeforeHorizon,string EntryEvidenceHash,string ExitEvidenceHash,string BenchmarkEntryEvidenceHash,string BenchmarkExitEvidenceHash,string ProcessState,string CanonicalSha256);

public static class TeacherRecommendationOutcomeEvaluatorV2
{
    public static TeacherRecommendationOutcomeV2 Evaluate(TeacherRecommendationV2 recommendation,TeacherCryptoMarketFactV2 entry,TeacherCryptoMarketFactV2 exit,string benchmark,TeacherCryptoMarketFactV2 benchmarkEntry,TeacherCryptoMarketFactV2 benchmarkExit,IReadOnlyList<TeacherCryptoMarketFactV2> path,bool invalidatedBeforeHorizon,DateTimeOffset evaluatedAtUtc)
    {
        if(recommendation.ExecutionAuthority||recommendation.AssetClass!="crypto"||recommendation.State==TeacherRecommendationStateV2.Unavailable||!TeacherCryptoMarketFactCanonicalizerV2.IsCanonical(entry)||!TeacherCryptoMarketFactCanonicalizerV2.IsCanonical(exit)||!TeacherCryptoMarketFactCanonicalizerV2.IsCanonical(benchmarkEntry)||!TeacherCryptoMarketFactCanonicalizerV2.IsCanonical(benchmarkExit)||entry.Symbol!=recommendation.Instrument||exit.Symbol!=entry.Symbol||benchmarkEntry.Symbol!=benchmark||benchmarkExit.Symbol!=benchmark||entry.RetrievedAtUtc>recommendation.IssuedAtUtc||exit.RetrievedAtUtc>evaluatedAtUtc||benchmarkEntry.RetrievedAtUtc>recommendation.IssuedAtUtc||benchmarkExit.RetrievedAtUtc>evaluatedAtUtc||!recommendation.EvidenceHashes.Contains(entry.CanonicalSha256,StringComparer.Ordinal))throw new InvalidOperationException("Recommendation outcome evidence is ineligible or look-ahead contaminated.");
        var eligible=path.Where(x=>TeacherCryptoMarketFactCanonicalizerV2.IsCanonical(x)&&x.Symbol==entry.Symbol&&x.ObservedAtUtc>=entry.ObservedAtUtc&&x.ObservedAtUtc<=exit.ObservedAtUtc&&x.RetrievedAtUtc<=evaluatedAtUtc).OrderBy(x=>x.ObservedAtUtc).ToArray();if(eligible.Length==0)throw new InvalidOperationException("Recommendation outcome path is unavailable.");var returns=eligible.Select(x=>Pct(entry.MarkPrice,x.MarkPrice)).ToArray();var instrument=Pct(entry.MarkPrice,exit.MarkPrice);var benchmarkReturn=Pct(benchmarkEntry.MarkPrice,benchmarkExit.MarkPrice);var draft=new TeacherRecommendationOutcomeV2($"outcome-{recommendation.RecommendationId}-{recommendation.Version}-{evaluatedAtUtc:yyyyMMddHHmm}","wpe.teacher-recommendation-outcome/2.0",recommendation.RecommendationId,recommendation.Version,recommendation.Instrument,benchmark,recommendation.Horizon,recommendation.IssuedAtUtc,evaluatedAtUtc.ToUniversalTime(),entry.MarkPrice,exit.MarkPrice,instrument,benchmarkReturn,instrument-benchmarkReturn,returns.Max(),returns.Min(),invalidatedBeforeHorizon,entry.CanonicalSha256,exit.CanonicalSha256,benchmarkEntry.CanonicalSha256,benchmarkExit.CanonicalSha256,invalidatedBeforeHorizon?"invalidated":"conditions-followed",string.Empty);return draft with{CanonicalSha256=MarketTeacherComposerV2.Hash(Serialize(draft))};
    }
    private static decimal Pct(decimal before,decimal after)=>decimal.Round((after-before)/before*100m,6,MidpointRounding.ToEven);
    private static string Serialize(TeacherRecommendationOutcomeV2 x)=>string.Join('|',x.Schema,x.RecommendationId,x.RecommendationVersion,x.Instrument,x.Benchmark,x.Horizon,x.IssuedAtUtc.ToString("O",CultureInfo.InvariantCulture),x.EvaluatedAtUtc.ToString("O",CultureInfo.InvariantCulture),x.EntryPrice.ToString(CultureInfo.InvariantCulture),x.ExitPrice.ToString(CultureInfo.InvariantCulture),x.InstrumentReturnPct.ToString(CultureInfo.InvariantCulture),x.BenchmarkReturnPct.ToString(CultureInfo.InvariantCulture),x.RelativeReturnPct.ToString(CultureInfo.InvariantCulture),x.MaximumFavorableExcursionPct.ToString(CultureInfo.InvariantCulture),x.MaximumAdverseExcursionPct.ToString(CultureInfo.InvariantCulture),x.InvalidatedBeforeHorizon,x.EntryEvidenceHash,x.ExitEvidenceHash,x.BenchmarkEntryEvidenceHash,x.BenchmarkExitEvidenceHash,x.ProcessState);
}
