'use client'

import {postRuntimeHostCommand,useWpeRuntime,type RuntimeAgentHandoff,type RuntimeAgentOperation} from '@/components/runtime-bridge'
import {RuntimeMetric,RuntimeUnavailable} from '@/components/runtime-state'
import {PageHeader} from '@/components/shell/page-header'
import {Panel,PanelBody,PanelHeader} from '@/components/ui/panel'
import {getRoleDirectory,validateRoleRegistry,type RoleDefinition} from '@/lib/agents/roles'
import {useI18n} from '@/lib/i18n/context'

export default function AgentsPage(){
 const runtime=useWpeRuntime(),{t,formatDate,locale}=useI18n(),roles=getRoleDirectory(),errors=validateRoleRegistry(),operations=new Map(runtime.agentOperations?.map(item=>[item.roleId,item])),handoffs=runtime.agentHandoffs??[],control=agentControlCopy(locale),stopping=runtime.agentIsRunning===true,controlAllowed=stopping?runtime.agentStopAllowed===true:runtime.agentStartAllowed===true
 const requestAgentControl=()=>{const action=stopping?'agent-stop':'agent-start';if(!controlAllowed)return;if(!window.confirm(stopping?control.confirmStop:control.confirmStart))return;if(!postRuntimeHostCommand(action))window.alert(t('settings.desktopOnly'))}
 return <div className="flex flex-col gap-6 p-6">
  <PageHeader title={t('agents.title')} description={t('agents.description')} actions={<button type="button" disabled={!controlAllowed} onClick={requestAgentControl} className={`rounded-md border px-3 py-1.5 text-xs disabled:cursor-not-allowed disabled:opacity-50 ${stopping?'border-danger/30 bg-danger/10 text-danger':'border-info/30 bg-info/10 text-info'}`}>{stopping?control.stop:control.start}</button>}/>
  {runtime.runtimeFresh?<Panel><PanelBody className="grid gap-3 md:grid-cols-3"><RuntimeMetric label={t('agents.coreStatus')} value={runtime.status}/><RuntimeMetric label={t('dashboard.workflow')} value={runtime.workflowNode}/><RuntimeMetric label="Brain" value={runtime.brainConnected?t('common.connected'):t('common.notConnected')}/><RuntimeMetric label={t('dashboard.progress')} value={runtime.thinkingProgress===undefined?undefined:`${runtime.thinkingProgress}%`}/><RuntimeMetric label={t('dashboard.reviewer')} value={runtime.reviewerStatus}/><RuntimeMetric label={t('dashboard.lastDecision')} value={runtime.lastDecision}/></PanelBody></Panel>:<RuntimeUnavailable stale={Boolean(runtime.lastUpdated)} subject="Agent runtime"/>}
  <Panel><PanelHeader title={t('agents.operations')} action={<span className="text-xs text-muted-foreground">{runtime.previewMode?t('common.preview'):runtime.collectionStates?.agentOperations??t('common.unsupported')}</span>}/><PanelBody className="space-y-4">{runtime.collectionStates?.agentOperations!=='available'?<Empty text={t(runtime.collectionStates?.agentOperations==='stale'?'agents.operationsStale':'agents.operationsUnavailable')}/>:<><div className="grid gap-3 sm:grid-cols-5"><RuntimeMetric label={t('agents.running')} value={runtime.agentOperations?.filter(x=>x.status==='running').length??0}/><RuntimeMetric label={t('agents.monitoring')} value={runtime.agentOperations?.filter(x=>x.status==='monitoring').length??0}/><RuntimeMetric label={t('agents.waiting')} value={runtime.agentOperations?.filter(x=>x.status==='waiting').length??0}/><RuntimeMetric label={t('agents.degraded')} value={runtime.agentOperations?.filter(x=>x.status==='degraded').length??0}/><RuntimeMetric label={t('agents.stopped')} value={runtime.agentOperations?.filter(x=>x.status==='stopped').length??0}/></div><div className="border-t border-border pt-4"><h3 className="mb-3 text-xs font-medium">{t('agents.recentHandoffs')}</h3>{runtime.collectionStates?.agentHandoffs!=='available'?<Empty text={t('agents.handoffUnsupported')}/>:!handoffs.length?<Empty text={t('agents.noHandoffs')}/>:<div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="text-muted-foreground"><tr>{[t('common.time'),t('agents.source'),t('agents.target'),t('agents.result')].map(x=><th key={x} className="pb-2 font-normal">{x}</th>)}</tr></thead><tbody>{handoffs.slice(0,8).map(row=><tr key={row.id} className="border-t border-border"><td className="py-3">{formatDate(row.occurredAtUtc)}</td><td>{row.sourceRoleId}</td><td>{row.targetRoleId}</td><td>{row.result}</td></tr>)}</tbody></table></div>}</div></>}</PanelBody></Panel>
  <Panel><PanelHeader title={t('agents.skills')} action={<span className="text-xs text-muted-foreground">{runtime.previewMode?t('common.preview'):runtime.collectionStates?.skillCalls??t('common.unsupported')}</span>}/><PanelBody>{runtime.collectionStates?.skillCalls!=='available'?<Empty text={t(runtime.collectionStates?.skillCalls==='stale'?'agents.skillsStale':'agents.skillsUnavailable')}/>:!runtime.skillCalls?.length?<Empty text={t('agents.noSkills')}/>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="text-muted-foreground"><tr>{[t('common.time'),t('agents.skill'),t('common.status'),t('agents.duration'),t('common.mode'),t('agents.remoteLlm'),t('agents.tokensCost')].map(x=><th key={x} className="pb-2 font-normal">{x}</th>)}</tr></thead><tbody>{runtime.skillCalls.map(call=><tr key={call.id} className="border-t border-border"><td className="py-3">{formatDate(call.occurredAtUtc)}</td><td>{call.skill}</td><td>{call.status}</td><td>{call.durationMs} ms</td><td>{call.mode??t('common.unknown')}</td><td>{call.remoteLlmUsed===null?t('common.unknown'):call.remoteLlmUsed?t('agents.used'):t('agents.local')}</td><td>{call.tokens??t('common.unknown')}{call.costUsd===null?'':` / $${call.costUsd.toFixed(4)}`}</td></tr>)}</tbody></table></div>}</PanelBody></Panel>
  <Panel><PanelHeader title={t('agents.memory')} action={<span className="text-xs text-muted-foreground">{runtime.previewMode?t('common.preview'):runtime.memoryStatus?.state??t('common.unsupported')}</span>}/><PanelBody>{runtime.memoryStatus?.state!=='available'||!runtime.memoryStatus.value?<Empty text={runtime.memoryStatus?.state==='stale'?t('agents.memoryStale'):runtime.memoryStatus?.message||t('agents.memoryUnavailable')}/>:<div className="grid gap-3 sm:grid-cols-3"><RuntimeMetric label="Working / 24h" value={runtime.memoryStatus.value.workingCount}/><RuntimeMetric label="Episodic / 30d" value={runtime.memoryStatus.value.episodicCount}/><RuntimeMetric label="Long-term / 365d" value={runtime.memoryStatus.value.longTermCount}/></div>}</PanelBody></Panel>
  <Panel><PanelBody className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-sm font-semibold">{t('agents.directory')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('agents.directoryHelp')}</p></div><span className={errors.length?'text-xs text-warning':'text-xs text-success'}>{errors.length?t('agents.contractIssues',{count:errors.length}):t('agents.contractValid')}</span></div>{errors.length>0&&<div className="border border-warning/30 p-3 text-xs text-warning">{errors.join(' | ')}</div>}<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{roles.map(role=><RoleCard key={role.id} role={role} operation={operations.get(role.id)} handoff={handoffs.find(x=>x.sourceRoleId===role.id||x.targetRoleId===role.id)}/>)}</div></PanelBody></Panel>
 </div>
}

function Empty({text}:{text:string}){return <div className="py-8 text-center text-sm text-muted-foreground">{text}</div>}

function RoleCard({role,operation,handoff}:{role:RoleDefinition;operation?:RuntimeAgentOperation;handoff?:RuntimeAgentHandoff}){
 const{t,formatDate,locale}=useI18n(),modes=role.optionalLlm?'Local Only / Hybrid / AI Research':'Local Only',authorization=role.typedAuthorization,status=operation?.status??'stopped',isWorkflowAvailable=operation!==undefined&&status!=='degraded'&&status!=='stopped',hasOrderAuthority=authorization.machineExecutionEligibility.length>0,copy=agentAccessCopy(locale)
 return <section className="min-w-0 border border-border bg-card/60 p-3 text-xs"><div className="flex items-center justify-between gap-2"><h3 className="break-words font-medium">{role.name}</h3><span className="shrink-0 text-muted-foreground">{t(`agents.${status}` as 'agents.stopped')}</span></div><dl className="mt-3 space-y-2 text-muted-foreground"><Row label={copy.workflowAvailability} value={isWorkflowAvailable?copy.workflowAvailable:t(`agents.${status}` as 'agents.stopped')}/><Row label={copy.tradingAuthority} value={hasOrderAuthority?copy.controlledOrderAuthority:copy.noOrderAuthority}/><Row label={t('agents.responsibility')} value={role.outputs.join(', ')}/><Row label={t('common.mode')} value={`${operation?.mode??'Local Only'} / ${t('agents.supports')} ${modes}`}/><Row label={t('common.activity')} value={`${operation?.activity??t('agents.noActivity')}${operation?.lastActivityAtUtc?` / ${formatDate(operation.lastActivityAtUtc)}`:''}`}/><Row label={t('common.handoff')} value={handoff?`${handoff.sourceRoleId} -> ${handoff.targetRoleId} / ${handoff.result}`:t('agents.noHandoffs')}/><Row label={t('agents.fallback')} value={role.deterministicFallback}/><Row label={t('common.allowed')} value={role.allowedActions.join(', ')}/></dl><details className="mt-3 border-t border-border pt-3"><summary className="cursor-pointer text-muted-foreground">{copy.authorizationDetails}</summary><dl className="mt-3 space-y-2 text-muted-foreground"><Row label={t('agents.machineEvidenceGate')} value={authorization.machineEvidenceGate.join(', ')||t('common.none')}/><Row label={t('agents.machineRiskAuthorization')} value={authorization.machineRiskAuthorization.join(', ')||t('common.none')}/><Row label={t('agents.machineExecutionEligibility')} value={authorization.machineExecutionEligibility.join(', ')||t('common.none')}/><Row label={t('agents.automaticSafetyAction')} value={authorization.automaticSafetyAction.join(', ')||t('common.none')}/><Row label={t('agents.humanLifecycleGovernance')} value={authorization.humanLifecycleGovernance.join(', ')||t('common.none')}/><Row label={t('agents.humanExternalPublicationReview')} value={authorization.humanExternalPublicationReview.join(', ')||t('common.none')}/><Row label={t('common.forbidden')} value={role.forbiddenActions.join(', ')}/></dl></details></section>
}

function agentControlCopy(locale:string){
 if(locale==='zh_CN')return{start:'启动 Agent',stop:'停止 Agent',confirmStart:'确认请求启动七 Agent Testnet 运行？宿主仍会重新执行就绪与权限检查。',confirmStop:'确认停止当前 Agent 运行？'}
 if(locale==='zh_TW')return{start:'啟動 Agent',stop:'停止 Agent',confirmStart:'確認要求啟動七 Agent Testnet 執行？宿主仍會重新執行就緒與權限檢查。',confirmStop:'確認停止目前 Agent 執行？'}
 if(locale==='ja_JP')return{start:'Agent を開始',stop:'Agent を停止',confirmStart:'7 Agent の Testnet 実行開始を要求しますか？ホストは準備状況と権限を再検証します。',confirmStop:'現在の Agent 実行を停止しますか？'}
 if(locale==='ko_KR')return{start:'Agent 시작',stop:'Agent 중지',confirmStart:'7개 Agent의 Testnet 실행 시작을 요청하시겠습니까? 호스트가 준비 상태와 권한을 다시 검사합니다.',confirmStop:'현재 Agent 실행을 중지하시겠습니까?'}
 if(locale==='it_IT')return{start:'Avvia Agent',stop:'Arresta Agent',confirmStart:'Richiedere l’avvio dei sette Agent in Testnet? L’host ricontrollerà disponibilità e autorizzazioni.',confirmStop:'Arrestare l’esecuzione corrente degli Agent?'}
 return{start:'Start Agents',stop:'Stop Agents',confirmStart:'Request the seven-Agent Testnet runtime to start? The host will re-check readiness and authorization.',confirmStop:'Stop the current Agent runtime?'}
}

function agentAccessCopy(locale:string){
 if(locale==='zh_CN')return{workflowAvailability:'\u5de5\u4f5c\u6d41\u53ef\u7528\u6027',workflowAvailable:'\u53ef\u53c2\u4e0e\u5de5\u4f5c\u6d41',tradingAuthority:'\u4e0b\u5355\u6743\u9650',noOrderAuthority:'\u65e0\u4e0b\u5355\u6743\u9650\uff08\u8be5\u89d2\u8272\u6b63\u5e38\u72b6\u6001\uff09',controlledOrderAuthority:'\u53d7\u63a7 Testnet \u4e0b\u5355\u6743\u9650',authorizationDetails:'\u9ad8\u7ea7\u6743\u9650\u660e\u7ec6'}
 if(locale==='zh_TW')return{workflowAvailability:'\u5de5\u4f5c\u6d41\u53ef\u7528\u6027',workflowAvailable:'\u53ef\u53c3\u8207\u5de5\u4f5c\u6d41',tradingAuthority:'\u4e0b\u55ae\u6b0a\u9650',noOrderAuthority:'\u7121\u4e0b\u55ae\u6b0a\u9650\uff08\u8a72\u89d2\u8272\u6b63\u5e38\u72c0\u614b\uff09',controlledOrderAuthority:'\u53d7\u63a7 Testnet \u4e0b\u55ae\u6b0a\u9650',authorizationDetails:'\u9032\u968e\u6b0a\u9650\u660e\u7d30'}
 return{workflowAvailability:'Workflow availability',workflowAvailable:'Available for workflow',tradingAuthority:'Order authority',noOrderAuthority:'No order authority (normal for this role)',controlledOrderAuthority:'Controlled Testnet order authority',authorizationDetails:'Advanced authorization details'}
}

function Row({label,value}:{label:string;value:string}){return <div><dt className="text-[10px] uppercase">{label}</dt><dd className="mt-0.5 break-words text-foreground">{value}</dd></div>}
