import type { WpeRuntimeState } from '@/components/runtime-bridge'

export const browserPreviewEnabled = true
export const previewState: WpeRuntimeState = {
  previewMode: true,
  runtimeFresh: true,
  runtimeAgeSeconds: 0,
  environment: 'PREVIEW - TESTNET',
  status: 'Running',
  aiRuntimeMode: 'Hybrid',
  aiRuntimeEffectiveMode: 'LocalOnly',
  brainRemoteAllowed: false,
  brainFallbackReason: 'Preview mode uses the built-in deterministic provider.',
  activeBrainProvider: 'WPE Local Brain',
  activeBrainModel: 'local-deterministic',
  loggedInUser: 'Preview',
  exchangeConnected: true,
  brainConnected: true,
  apiTradePermission: false,
  riskReady: true,
  btcPrice: 118420.5,
  ethPrice: 3648.2,
  btcTrend: 1.28,
  ethTrend: -0.42,
  marketRegime: 'Trend / Moderate Volatility',
  walletBalance: 25000,
  availableBalance: 21750,
  positionQuantity: 0.08,
  brainConfidence: 78,
  decisionScore: 72,
  riskLoad: 24,
  conflictRate: 8,
  workflowNode: 'RISK_REVIEW',
  thinkingProgress: 68,
  reflectionStatus: 'READY',
  reviewerStatus: 'APPROVED',
  riskApprovalStatus: 'APPROVED',
  executionApprovalStatus: 'WAITING',
  dataQualityScore: 91,
  liquidityScore: 88,
  volatilityPercent: 2.1,
  researchScore: 84,
  historicalCoverageDays: 180,
  missingConditions: 'None',
  riskSummary: 'Risk budget healthy. Execution remains disabled in preview mode.',
  lastUpdated: new Date().toISOString(),
  lastDecision: 'HOLD',
  lastReason: 'Waiting for price confirmation above the planned entry zone.',
  decisionAuditSummary: 'Preview decision passed evidence and risk review.',
  strategyStatus: 'Shadow',
  strategySummary: 'BTC trend-following candidate under shadow evaluation',
  strategyCandidates: 3,
  plannedEntry: 118900,
  plannedStop: 116700,
  plannedTakeProfit: 123300,
  plannedQuantity: 0.04,
  riskRewardRatio: 2,
  realtimeStatus: 'Preview feed active',
  runtimeRecoveryStatus: 'Healthy',
  newsFullTextDocuments: 18,
  newsCorroboratingSources: 4,
  positionsSummary: 'BTCUSDT Long | 0.08 | Entry 116,850 | uPnL +125.64',
  ordersSummary: 'No live orders. Preview execution is disabled.',
  marketSummary: 'BTCUSDT 118,420.50 | ETHUSDT 3,648.20',
  newsSummary: 'Preview: macro and exchange-flow evidence available.',
  decisionDiagnostics: 'Preview data only. No exchange mutation is possible.',
  dailyPnl: 186.42,
  maxDrawdown: 1.4,
  runtimeEventSequence: 128,
  runtimeHeartbeatAtUtc: new Date().toISOString(),
  diagnostic:{state:'available',value:{code:'PREVIEW-0001',timeUtc:new Date().toISOString(),summary:'PREVIEW DATA - illustrative diagnostic only.'}},
  contractVersion: '1.0',
  freshness: { fresh: true, ageSeconds: 0, staleAfterSeconds: 15 },
  collectionStates: { account: 'available', positions: 'available', orders: 'available', risk: 'available', strategies: 'available', backtests: 'available', telemetry: 'available', markets: 'available', capabilities: 'available', llmGovernance: 'available', plugins: 'available', auditEvents: 'available', equityHistory: 'available', connectionStatus: 'available', strategyRegistry:'available', strategyLifecycleEvents:'available',skillCalls:'available',memoryStatus:'available',recentMemoryRetrievals:'available',agentOperations:'available',agentHandoffs:'available',notificationStatus:'available',notificationOutbox:'available',authorizationMode:'available',pendingApprovals:'available' },
  authorizationMode:{state:'available',message:'PREVIEW DATA - illustrative authorization state only.',value:{mode:'Review'}},
  pendingApprovals:{state:'available',message:'PREVIEW DATA - illustrative approval queue only.',items:[{approvalId:'approval#A1B2C3D4E5F6',symbol:'BTCUSDT',side:'Long',orderType:'Limit',quantity:.04,entryPrice:118900,stopLoss:116700,takeProfit:123300,createdAtUtc:new Date(Date.now()-60_000).toISOString(),expiresAtUtc:new Date(Date.now()+240_000).toISOString(),status:'Pending',reasonCode:'approval.awaiting-user'}]},
  notificationStatus:{
    state:'available',
    message:'PREVIEW DATA - illustrative delivery state only; no message was sent.',
    value:{
      enabled:true,
      telegramStored:true,
      telegramReady:true,
      whatsAppStored:true,
      whatsAppReady:false,
      legacyMigrationPending:false,
      legacyMigrationDiagnosticCode:null,
      eventKinds:['OrderFilled','PositionOpened','PositionClosed','ProtectionUpdated','RiskBlocked'],
      quietHoursEnabled:true,
      quietHoursStart:'22:00',
      quietHoursEnd:'07:00',
      quietHoursTimeZone:'Asia/Tokyo',
      pendingCount:1,
      retryingCount:1,
      sentCount:12,
      deadLetterCount:1,
    },
  },
  notificationOutbox:[
    {id:1003,channel:'WhatsApp',kind:'RiskBlocked',uiState:'DeadLetter',inFlight:false,attempts:5,maxAttempts:5,occurredAtUtc:new Date(Date.now()-90_000).toISOString(),nextAttemptAtUtc:new Date(Date.now()-60_000).toISOString(),updatedAtUtc:new Date(Date.now()-30_000).toISOString(),diagnosticCode:'PREVIEW-WPE-003'},
    {id:1002,channel:'Telegram',kind:'ProtectionUpdated',uiState:'Retrying',inFlight:false,attempts:2,maxAttempts:5,occurredAtUtc:new Date(Date.now()-60_000).toISOString(),nextAttemptAtUtc:new Date(Date.now()+30_000).toISOString(),updatedAtUtc:new Date().toISOString(),diagnosticCode:'PREVIEW-WPE-002'},
    {id:1001,channel:'Telegram',kind:'PositionOpened',uiState:'Sent',inFlight:false,attempts:1,maxAttempts:5,occurredAtUtc:new Date(Date.now()-120_000).toISOString(),nextAttemptAtUtc:new Date(Date.now()-120_000).toISOString(),updatedAtUtc:new Date(Date.now()-110_000).toISOString(),diagnosticCode:null},
  ],
  agentOperations:[
    {roleId:'market',status:'monitoring',lastActivityAtUtc:new Date().toISOString(),activity:'PREVIEW DATA - market streams monitored',mode:'Local Only'},
    {roleId:'research',status:'running',lastActivityAtUtc:new Date().toISOString(),activity:'PREVIEW DATA - evidence cycle active',mode:'Local Only'},
    {roleId:'strategy',status:'monitoring',lastActivityAtUtc:new Date().toISOString(),activity:'PREVIEW DATA - active and shadow strategies monitored',mode:'Local Only'},
    {roleId:'risk',status:'monitoring',lastActivityAtUtc:new Date().toISOString(),activity:'PREVIEW DATA - risk gates monitored',mode:'Local Only'},
    {roleId:'execution',status:'waiting',lastActivityAtUtc:new Date().toISOString(),activity:'PREVIEW DATA - no approved order pending',mode:'Local Only'},
    {roleId:'recovery',status:'monitoring',lastActivityAtUtc:new Date().toISOString(),activity:'PREVIEW DATA - no unresolved order',mode:'Local Only'},
    {roleId:'audit',status:'monitoring',lastActivityAtUtc:new Date().toISOString(),activity:'PREVIEW DATA - append-only audit monitored',mode:'Local Only'},
  ],
  agentHandoffs:[{id:'preview-handoff-1',occurredAtUtc:new Date(Date.now()-20000).toISOString(),sourceRoleId:'research',targetRoleId:'strategy',result:'PREVIEW DATA - evidence accepted'}],
  memoryStatus:{state:'available',message:'PREVIEW DATA - illustrative local memory counts only.',value:{workingCount:12,episodicCount:48,longTermCount:7,lastRetrievedAtUtc:new Date().toISOString()}},
  recentMemoryRetrievals:[{id:1,tier:'episodic',symbol:'SOLUSDT',providerId:'preview-provider',strategyId:'preview-sol-trend',occurredAtUtc:new Date().toISOString(),result:'SUCCESS',source:'PREVIEW DATA - deterministic-sqlite-query',resultCount:3}],
  skillCalls:[
    {id:'preview:2',occurredAtUtc:new Date().toISOString(),skill:'BrainPlanner',status:'SUCCESS',durationMs:184,mode:'Hybrid',remoteLlmUsed:true,tokens:312,costUsd:.0021},
    {id:'preview:1',occurredAtUtc:new Date(Date.now()-60000).toISOString(),skill:'RiskAndPositionPlanner',status:'SUCCESS',durationMs:7,mode:'LocalOnly',remoteLlmUsed:false,tokens:null,costUsd:null},
  ],
  strategyRegistry:[
    {id:'preview-sol-trend',version:'v2',symbol:'SOLUSDT',family:'TrendBreakout',lifecycle:'Shadow',lastReason:'PREVIEW DATA - shadow quality gate',stateChangedAtUtc:new Date(Date.now()-3600000).toISOString(),qualityScore:.82},
    {id:'preview-btc-core',version:'v4',symbol:'BTCUSDT',family:'TrendBreakout',lifecycle:'Active',lastReason:'PREVIEW DATA - deterministic activation gate passed',stateChangedAtUtc:new Date(Date.now()-7200000).toISOString(),qualityScore:.88},
  ],
  strategyLifecycleEvents:[
    {id:2,strategyId:'preview-sol-trend',fromState:'Backtested',toState:'Shadow',occurredAtUtc:new Date(Date.now()-3600000).toISOString(),reason:'PREVIEW DATA - shadow quality gate'},
    {id:1,strategyId:'preview-btc-core',fromState:'Shadow',toState:'Active',occurredAtUtc:new Date(Date.now()-7200000).toISOString(),reason:'PREVIEW DATA - deterministic activation gate passed'},
  ],
  connectionStatus: {
    state: 'available',
    message: 'PREVIEW DATA - illustrative Testnet connection status only; no exchange check was performed.',
    value: {
      connectionId: 'preview-testnet-demo',
      displayName: 'Preview Exchange Connection',
      providerId: 'preview-provider',
      environment: 'PREVIEW - TESTNET',
      credentialStatus: 'configured',
      adapterStatus: 'ready',
      lastCheckedAtUtc: new Date().toISOString(),
      ready: true,
      exchangeConnected: true,
      tradePermission: false,
      withdrawPermission: false,
      withdrawalWarning: null,
    },
  },
  llmGovernance: {
    state: 'available',
    message: 'PREVIEW DATA - illustrative governance metrics only.',
    value: {
      mode: 'Hybrid',
      remoteAllowed: false,
      calls: 42,
      tokens: 28560,
      costUsd: 0.34,
      cacheHits: 19,
      budgetBlocks: 3,
      fallbacks: 7,
      privacyBlocks: 2,
      offlineCompletions: 16,
      topProvider: 'WPE Local Brain',
      topPurpose: 'Strategy review',
      topAgent: 'Research Analyst',
      topTool: 'Local Retrieval',
      lastCallAtUtc: new Date().toISOString(),
    },
  },
  plugins: {
    state: 'available',
    message: 'PREVIEW DATA - illustrative local registry only.',
    items: [
      {
        id: 'wpe.market-depth.local',
        name: 'Local Market Depth',
        type: 'data-source',
        version: '0.3.0',
        publisherId: 'wpe-labs',
        publisherName: 'WPE Labs',
        entryKind: 'wpe-contract',
        permissions: ['market.read', 'data.read'],
        enabled: true,
        defaultEnabled: false,
        active: false,
        runtimeStatus: 'not-configured',
        testnetOnly: false,
        compatibilityStatus: 'compatible',
        signatureStatus: 'metadataPresent',
        riskLevel: 'low',
        statusMessage: 'Preview-only local data source.',
      },
      {
        id: 'wpe.notification.webhook',
        name: 'Risk Alert Webhook',
        type: 'notification',
        version: '0.2.1',
        publisherId: 'wpe-labs',
        publisherName: 'WPE Labs',
        entryKind: 'wpe-contract',
        permissions: ['notify.emit', 'notify.webhook'],
        enabled: false,
        defaultEnabled: false,
        active: false,
        runtimeStatus: 'not-configured',
        testnetOnly: false,
        compatibilityStatus: 'compatible',
        signatureStatus: 'metadataPresent',
        riskLevel: 'medium',
        statusMessage: 'Disabled until an allowlisted endpoint is configured.',
      },
      {
        id: 'wpe.exchange.sandbox',
        name: 'Sandbox Exchange Adapter',
        type: 'exchange-adapter',
        version: '0.1.0',
        publisherId: 'wpe-labs',
        publisherName: 'WPE Labs',
        entryKind: 'wpe-contract',
        permissions: ['exchange.testnet.read', 'exchange.testnet.trade'],
        enabled: false,
        defaultEnabled: false,
        active: true,
        runtimeStatus: 'running',
        testnetOnly: true,
        compatibilityStatus: 'compatible',
        signatureStatus: 'metadataPresent',
        riskLevel: 'high',
        statusMessage: 'Testnet only. Trading remains behind Risk Gate and ReliableOrderExecutor.',
      },
    ],
  },
  auditEvents: {
    state: 'available',
    message: 'PREVIEW DATA - illustrative audit events only.',
    items: [
      {
        id: 'preview-audit-003',
        timeUtc: new Date().toISOString(),
        category: 'risk',
        source: 'Preview Risk Gate',
        correlationId: 'preview-correlation-42',
        status: 'APPROVED',
        summary: 'PREVIEW DATA - illustrative risk review passed within the configured Testnet budget.',
      },
      {
        id: 'preview-audit-002',
        timeUtc: new Date(Date.now() - 45_000).toISOString(),
        category: 'decision',
        source: 'Preview Decision Agent',
        correlationId: 'preview-correlation-42',
        status: 'HOLD',
        summary: 'PREVIEW DATA - illustrative decision is waiting for entry confirmation.',
      },
      {
        id: 'preview-audit-001',
        timeUtc: new Date(Date.now() - 90_000).toISOString(),
        category: 'system',
        source: 'Preview Runtime',
        correlationId: null,
        status: 'READY',
        summary: 'PREVIEW DATA - browser preview initialized without exchange mutation access.',
      },
    ],
  },
  markets: [
    { exchangeId: 'binance', providerId: 'binance-testnet', symbol: 'BTCUSDT', nativeSymbol: 'BTCUSDT', price: 118420.5, changePercent: 1.28, trend: 1.28, regime: 'Trend / Moderate Volatility', state: 'available' },
    { exchangeId: 'binance', providerId: 'binance-testnet', symbol: 'ETHUSDT', nativeSymbol: 'ETHUSDT', price: 3648.2, changePercent: -0.42, trend: -0.42, regime: 'Trend / Moderate Volatility', state: 'available' },
    { exchangeId: 'okx', providerId: 'okx-testnet', symbol: 'SOLUSDT', nativeSymbol: 'SOL-USDT-SWAP', price: 182.4, changePercent: 2.04, trend: 2.04, regime: 'Trend / Moderate Volatility', state: 'available' },
  ],
  capabilities: [
    { exchangeId: 'binance', providerId: 'binance-testnet', canonicalSymbol: 'BTCUSDT', nativeSymbol: 'BTCUSDT', marketType: 'perpetual', status: 'available', canTrade: true, testnetAvailable: true },
    { exchangeId: 'binance', providerId: 'binance-testnet', canonicalSymbol: 'ETHUSDT', nativeSymbol: 'ETHUSDT', marketType: 'perpetual', status: 'available', canTrade: true, testnetAvailable: true },
    { exchangeId: 'okx', providerId: 'okx-testnet', canonicalSymbol: 'SOLUSDT', nativeSymbol: 'SOL-USDT-SWAP', marketType: 'perpetual', status: 'available', canTrade: false, testnetAvailable: true },
  ],
  positions: [
    { symbol: 'BTCUSDT', side: 'Long', quantity: 0.08, entryPrice: 116850, unrealizedPnl: 125.64 },
    { symbol: 'SOLUSDT', side: 'Short', quantity: 12, entryPrice: 184.2, unrealizedPnl: 21.6 },
  ],
  orders: [
    { orderId: 'preview-10428', symbol: 'BTCUSDT', side: 'Long', type: 'STOP_MARKET', status: 'NEW', quantity: 0.08, price: 116700 },
    { orderId: 'preview-10429', symbol: 'SOLUSDT', side: 'Short', type: 'TAKE_PROFIT', status: 'NEW', quantity: 12, price: 176.5 },
  ],
  equityHistory: [
    { timeUtc: new Date(Date.now() - 6 * 60 * 60_000).toISOString(), equity: 24280, availableBalance: 21120, environment: 'PREVIEW - TESTNET', providerId: 'preview-portfolio' },
    { timeUtc: new Date(Date.now() - 5 * 60 * 60_000).toISOString(), equity: 24410, availableBalance: 21240, environment: 'PREVIEW - TESTNET', providerId: 'preview-portfolio' },
    { timeUtc: new Date(Date.now() - 4 * 60 * 60_000).toISOString(), equity: 24340, availableBalance: 21080, environment: 'PREVIEW - TESTNET', providerId: 'preview-portfolio' },
    { timeUtc: new Date(Date.now() - 3 * 60 * 60_000).toISOString(), equity: 24690, availableBalance: 21420, environment: 'PREVIEW - TESTNET', providerId: 'preview-portfolio' },
    { timeUtc: new Date(Date.now() - 2 * 60 * 60_000).toISOString(), equity: 24820, availableBalance: 21590, environment: 'PREVIEW - TESTNET', providerId: 'preview-portfolio' },
    { timeUtc: new Date(Date.now() - 1 * 60 * 60_000).toISOString(), equity: 24740, availableBalance: 21480, environment: 'PREVIEW - TESTNET', providerId: 'preview-portfolio' },
    { timeUtc: new Date().toISOString(), equity: 25000, availableBalance: 21750, environment: 'PREVIEW - TESTNET', providerId: 'preview-portfolio' },
  ],
  collectionMessages: { backtests: 'PREVIEW DATA - illustrative deterministic research result only.', equityHistory: 'PREVIEW DATA - illustrative Testnet equity history only.' },
  backtests: [
    {
      backtestId: 'preview-sol-trend-001',
      strategyId: 'SOLUSDT-TrendBreakout-0',
      strategyVersion: 'trendbreakout-1',
      symbol: 'SOLUSDT',
      completedAtUtc: new Date().toISOString(),
      status: 'PASSED',
      coverageDays: 365,
      trades: 84,
      outOfSampleReturn: 0.087,
      maxDrawdown: 0.116,
      sharpe: 1.34,
    },
  ],
}
