using 币安量化机器人.Core.Models;
using 币安量化机器人.Services.Agent;

namespace 币安量化机器人.Services;

public static class AutoTradingAgent
{
    private static CancellationTokenSource? _cts;private static Task? _run;private static readonly AgentSettingsStore SettingsStore=new();private static readonly AgentSqliteStore Db=new();private static readonly SemaphoreSlim ExecutionGate=new(1,1);private static IExchangeAdapter? _activeExchange;private static decimal _dayHigh;private static bool _paused;
    public static bool IsRunning=>_run is{IsCompleted:false};public static bool CanEmergencyClose=>_activeExchange is not null;public static event Action? StateChanged;
    public static void StartDefault(){if(IsRunning)return;_paused=false;_cts=new();_run=Task.Run(async()=>{try{await Run(_cts.Token);}catch(OperationCanceledException)when(_cts?.IsCancellationRequested==true){}catch(Exception ex){await Db.RecordErrorAsync("启动/主循环",ex,CancellationToken.None);ServiceLocator.SystemState.LastError=ex.Message;Set(AgentStatus.Degraded,$"智能体停止：{ex.Message}");}finally{_activeExchange=null;}});}
    public static void Pause(){_paused=true;Set(AgentStatus.Paused,"已暂停，不发起新周期");}
    public static void Resume(){_paused=false;Set(AgentStatus.Running,"继续运行");}
    public static async Task StopAsync(){if(_cts is null)return;_cts.Cancel();try{if(_run is not null)await _run;}catch(OperationCanceledException){} _cts.Dispose();_cts=null;_run=null;Set(AgentStatus.Stopped,"智能体已停止");}
    public static async Task<string> EmergencyCloseAllAsync()
    {
        _paused=true;Set(AgentStatus.Paused,"紧急全平已请求，等待当前下单步骤结束");await ExecutionGate.WaitAsync();try
        {
            var exchange=_activeExchange??throw new InvalidOperationException("智能体尚未连接交易所，无法执行紧急全平");using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(90));var ct=timeout.Token;var positions=await exchange.GetPositionsAsync(ct);if(positions.Count==0){Set(AgentStatus.Paused,"紧急检查完成：当前无持仓");return"当前无持仓";}var cycle="EMERGENCY-"+Guid.NewGuid().ToString("N");var closed=new List<string>();
            foreach(var p in positions)
            {
                var raw=$"WPE-EMG-{DateTime.UtcNow:yyMMddHHmmss}-{Guid.NewGuid():N}";var id=raw[..Math.Min(36,raw.Length)];var action=p.Side==PositionSide.Long?DecisionAction.CloseLong:DecisionAction.CloseShort;var intent=new ExecutionIntent(p.Symbol,p.Side,p.Quantity,true,0,0,id,"用户在控制台确认紧急全平",action);await Db.SaveIntentAsync(cycle,intent,"INTENT",null,ct);
                var order=await exchange.FindOrderAsync(p.Symbol,id,ct)??await exchange.PlaceMarketAsync(p.Symbol,p.Side,p.Quantity,id,true,ct);await Db.SaveIntentAsync(cycle,intent,order.Status,order.OrderId,ct);for(var n=0;n<20&&order.Status is not("FILLED" or "CANCELED" or "REJECTED" or "EXPIRED");n++){await Task.Delay(500,ct);order=await exchange.FindOrderAsync(p.Symbol,id,ct)??order;}
                if(order.Status!="FILLED"){await Db.SaveIntentAsync(cycle,intent,"EMERGENCY_UNKNOWN",order.OrderId,ct);throw new InvalidOperationException($"{p.Symbol} {p.Side} 紧急平仓状态未确认：{order.Status}");}await Db.SaveIntentAsync(cycle,intent,"COMPLETED",order.OrderId,ct);foreach(var protection in (await exchange.GetOpenOrdersAsync(p.Symbol,ct)).Where(x=>x.IsProtection&&x.PositionSide==p.Side))await exchange.CancelOrderAsync(p.Symbol,protection.OrderId,ct);await Db.ClearLockedSideIfMatchesAsync(p.Symbol,p.Side,ct);closed.Add($"{p.Symbol} {p.Side} {p.Quantity}");
            }
            var account=await exchange.GetAccountAsync(ct);var remaining=await exchange.GetPositionsAsync(ct);var orders=await exchange.GetOpenOrdersAsync(null,ct);UpdateAccount(account,remaining,orders);var result="已确认全平："+string.Join("；",closed);Set(AgentStatus.Paused,result);return result;
        }
        catch(Exception ex){await Db.RecordErrorAsync("紧急全平",ex,CancellationToken.None);ServiceLocator.SystemState.LastError=ex.Message;Set(AgentStatus.Degraded,$"紧急全平未完全确认：{ex.Message}");throw;}
        finally{ExecutionGate.Release();}
    }
    private static async Task Run(CancellationToken ct)
    {
        var settings=SettingsStore.Load();SettingsStore.ImportDesktopTestnetIfEmpty(settings);SettingsStore.ImportDesktopDeepSeekIfEmpty(settings);if(settings.Environment==ExchangeEnvironment.Mainnet&&(!settings.MainnetTradingConfirmed||settings.MainnetConfirmedAtUtc is null))throw new InvalidOperationException("主网交易尚未完成独立显式确认，已拒绝启动");var (key,secret)=SettingsStore.GetCredentials(settings);if(string.IsNullOrWhiteSpace(key))throw new InvalidOperationException("当前环境尚未配置币安 API");
        await using IExchangeAdapter exchange=new BinanceFuturesAdapter(settings.Environment,key,secret);_activeExchange=exchange;var collector=new EvidenceCollector(exchange);var executor=new ReliableOrderExecutor(exchange,Db);var planner=new RiskAndPositionPlanner();
        if(!settings.Brains.TryGetValue(settings.ActiveBrain,out var brainSlot))throw new InvalidOperationException("未配置当前大脑");var brainKey=SecretVaultService.Decrypt(brainSlot.EncryptedKey);IBrainProvider brain=new HttpBrainProvider(brainSlot,brainKey);
        ServiceLocator.SystemState.Mode=settings.Environment==ExchangeEnvironment.Testnet?TradingMode.Testnet:TradingMode.Live;ServiceLocator.SystemState.BrainName=brain.Name;Set(AgentStatus.Running,$"{settings.Environment} · {brain.Name} · 正在接管账户状态");var startupHealth=await brain.HealthCheckAsync(ct);if(!startupHealth.Healthy)Set(AgentStatus.Degraded,$"大脑启动检查失败，交易周期将自动HOLD：{startupHealth.Message}");
        while(!ct.IsCancellationRequested)
        {
            if(_paused){await Task.Delay(1000,ct);continue;}var cycle=Guid.NewGuid().ToString("N");try{
            {
                Stage("账户、仓位与订单同步");var account=await exchange.GetAccountAsync(ct);var positions=await exchange.GetPositionsAsync(ct);var orders=await exchange.GetOpenOrdersAsync(null,ct);await Db.SaveSnapshotAsync(account,positions,orders,ct);_dayHigh=await Db.GetOrUpdateDailyHighAsync(DateOnly.FromDateTime(DateTime.UtcNow),account.Equity,ct);UpdateAccount(account,positions,orders);
                Stage("恢复中断订单并核对保护状态");var pendingRecovery=await executor.RecoverPendingAsync(ct);orders=await exchange.GetOpenOrdersAsync(null,ct);var protection=await executor.AuditAndRepairProtectionAsync(positions,orders,ct);var safeToIncreaseRisk=pendingRecovery.SafeToIncreaseRisk&&protection.SafeToIncreaseRisk;var safetyMessage=string.Join("；",pendingRecovery.Messages.Concat(protection.Messages));if(!safeToIncreaseRisk)ServiceLocator.SystemState.LastMessage=string.IsNullOrWhiteSpace(safetyMessage)?"账户恢复状态未确认，本轮禁止增加风险":safetyMessage;
                Stage("BTC/ETH 市场、衍生品与新闻证据");var evidence=await collector.CollectAsync(ct);UpdateEvidence(evidence);await Db.SaveNewsAsync(evidence.News,ct);await Db.StartCycleAsync(cycle,evidence,brain.Name,ct);
                Stage("当前唯一大脑决策");DecisionPlan decision;string? brainRequest=null,brainResponse=null;try{var activeSymbols=positions.Select(x=>x.Symbol).Distinct().ToArray();var brainResult=await brain.DecideAsync(evidence,new(brain.Name,_dayHigh>0&&(_dayHigh-account.Equity)/_dayHigh>=settings.Risk.DailyDrawdownLimit,activeSymbols.Length==1?activeSymbols[0]:null,await Db.RecentOutcomesAsync(ct)),ct);decision=brainResult.Decision;brainRequest=brainResult.Request;brainResponse=brainResult.Response;}catch(BrainCallException ex){brainRequest=ex.Request;brainResponse=ex.Response;await Db.RecordErrorAsync("大脑",ex,ct);decision=new(){Action=DecisionAction.Hold,Reason=$"大脑调用失败，本轮自动HOLD：{ex.Message}"};}catch(Exception ex){await Db.RecordErrorAsync("大脑",ex,ct);decision=new(){Action=DecisionAction.Hold,Reason="大脑调用失败，本轮自动HOLD"};}
                ServiceLocator.SystemState.LastDecision=decision.Action.ToString();ServiceLocator.SystemState.LastReason=decision.Reason;Stage("决策校验、仓位规划与风险审批");string result;IReadOnlyList<ExecutionIntent> intents=Array.Empty<ExecutionIntent>();TradingRule? rule=null;
                if(decision.Instrument is not("BTCUSDT" or "ETHUSDT")){result="品种无效";}else{rule=await exchange.GetRulesAsync(decision.Instrument,ct);var lockedSide=await Db.GetLockedSideAsync(decision.Instrument,ct);var planned=planner.Plan(decision,evidence,rule,settings.Risk,_dayHigh,safeToIncreaseRisk,safetyMessage,lockedSide);intents=planned.Intents;result=planned.Result;}
                if(intents.Count>0&&rule is not null){if(_paused)result="周期在执行前已暂停，未下单";else{await ExecutionGate.WaitAsync(ct);try{if(_paused)result="周期在执行前已暂停，未下单";else{Stage("幂等下单、成交核对与保护单");result=await executor.ExecutePlanAsync(cycle,intents,Math.Min(settings.Risk.Leverage,rule.MaxLeverage),settings.Risk.Isolated,ct);}}finally{ExecutionGate.Release();}}}await Db.CompleteCycleAsync(cycle,decision,result,brainRequest,brainResponse,ct);Set(_paused?AgentStatus.Paused:safeToIncreaseRisk?AgentStatus.Running:AgentStatus.Degraded,$"{decision.Action} · {result} · 证据 {evidence.Completeness}/100");Stage(_paused?"已暂停":"等待下一轮（15分钟）");
            }}catch(OperationCanceledException)when(ct.IsCancellationRequested){break;}catch(Exception ex){await Db.FailCycleAsync(cycle,ServiceLocator.SystemState.SkillStage,ex,ct);await Db.RecordErrorAsync(ServiceLocator.SystemState.SkillStage,ex,ct);ServiceLocator.SystemState.LastError=ex.Message;Set(AgentStatus.Degraded,$"本轮降级：{ex.Message}");}
            ServiceLocator.SystemState.NextCycleAtUtc=DateTime.UtcNow.AddMinutes(15);StateChanged?.Invoke();await Task.Delay(TimeSpan.FromMinutes(15),ct);
        }
    }
    private static void UpdateAccount(AccountSnapshot a,IReadOnlyList<ManagedPosition> p,IReadOnlyList<ExchangeOrder> o){var s=ServiceLocator.SystemState;s.WalletBalance=a.WalletBalance;s.AvailableBalance=a.AvailableBalance;s.PositionQuantity=p.Sum(x=>x.Side==PositionSide.Long?x.Quantity:-x.Quantity);s.EntryPrice=p.FirstOrDefault()?.EntryPrice??0;s.PositionsSummary=p.Count==0?"当前无持仓":string.Join("\n",p.Select(x=>$"{x.Symbol} {x.Side} · {x.Quantity} · 入场 {x.EntryPrice:F2} · 未实现 {x.UnrealizedPnl:F2}"));s.OrdersSummary=o.Count==0?"当前无挂单":string.Join("\n",o.Take(8).Select(x=>$"{x.Symbol} {x.Type} · {x.Status} · {x.PositionSide}"));}
    private static void UpdateEvidence(EvidencePack e){var s=ServiceLocator.SystemState;s.EvidenceCompleteness=e.Completeness;var markets=e.Markets.Values.OrderBy(x=>x.Symbol).ToArray();s.MarketSummary=markets.Length==0?"市场证据不可用":string.Join("\n",markets.Select(x=>$"{x.Symbol} {x.Price:F2} · 支撑 {x.Support:F2} · 压力 {x.Resistance:F2} · RSI {x.Rsi:F1} · 基差 {x.Derivatives.Basis:P3}"));s.NewsSummary=e.News.Count==0?"本轮没有可验证新闻":string.Join("\n",e.News.Take(6).Select(x=>$"[{x.Source}] {x.Title}"));var primary=markets.FirstOrDefault();if(primary is not null){s.Symbol=primary.Symbol;s.Timeframe="15m / 1h / 4h";s.CurrentPrice=primary.Price;s.Support=primary.Support;s.Resistance=primary.Resistance;}s.RiskSummary=$"证据完整度 {e.Completeness}/100 · 当日权益高点 {_dayHigh:F2}";}
    private static void Stage(string x){ServiceLocator.SystemState.SkillStage=x;ServiceLocator.SystemState.LastUpdated=DateTime.UtcNow;StateChanged?.Invoke();}
    private static void Set(AgentStatus st,string msg){var s=ServiceLocator.SystemState;s.Status=st;s.LastMessage=msg;s.LastUpdated=DateTime.UtcNow;StateChanged?.Invoke();}
}
