using 币安量化机器人.Core.Models;
using 币安量化机器人.Services.Agent;
using 币安量化机器人.Services.Localization;

namespace 币安量化机器人.Services;

public static class AutoTradingAgent
{
    private static CancellationTokenSource? _cts;private static Task? _run;private static readonly AgentSettingsStore SettingsStore=new();private static readonly AgentSqliteStore Db=new();private static readonly SemaphoreSlim ExecutionGate=new(1,1);private static IExchangeAdapter? _activeExchange;private static decimal _dayHigh;private static bool _paused;
    public static bool IsRunning=>_run is{IsCompleted:false};public static bool CanEmergencyClose=>_activeExchange is not null;public static event Action? StateChanged;
    public static void StartDefault(){if(IsRunning)return;_paused=false;_cts=new();_run=Task.Run(async()=>{try{await Run(_cts.Token);}catch(OperationCanceledException)when(_cts?.IsCancellationRequested==true){}catch(Exception ex){await Db.RecordErrorAsync("AGENT_LOOP",ex,CancellationToken.None);ServiceLocator.SystemState.LastError=ex.Message;Set(AgentStatus.Degraded,L("Agent.CycleDegraded",ex.Message));}finally{_activeExchange=null;}});}
    public static void Pause(){_paused=true;Set(AgentStatus.Paused,L("Agent.Paused"));}
    public static void Resume(){_paused=false;Set(AgentStatus.Running,L("Agent.Resumed"));}
    public static async Task StopAsync(){if(_cts is null)return;_cts.Cancel();try{if(_run is not null)await _run;}catch(OperationCanceledException){} _cts.Dispose();_cts=null;_run=null;Set(AgentStatus.Stopped,L("Agent.Stopped"));}
    public static async Task<string> EmergencyCloseAllAsync()
    {
        _paused=true;Set(AgentStatus.Paused,L("Agent.EmergencyRequested"));await ExecutionGate.WaitAsync();try
        {
            var exchange=_activeExchange??throw new InvalidOperationException(L("Agent.EmergencyUnavailable"));using var timeout=new CancellationTokenSource(TimeSpan.FromSeconds(90));var ct=timeout.Token;var positions=await exchange.GetPositionsAsync(ct);if(positions.Count==0){Set(AgentStatus.Paused,L("Agent.NoPositions"));return L("Agent.NoPositions");}var cycle="EMERGENCY-"+Guid.NewGuid().ToString("N");var closed=new List<string>();
            foreach(var p in positions)
            {
                var raw=$"WPE-EMG-{DateTime.UtcNow:yyMMddHHmmss}-{Guid.NewGuid():N}";var id=raw[..Math.Min(36,raw.Length)];var action=p.Side==PositionSide.Long?DecisionAction.CloseLong:DecisionAction.CloseShort;var intent=new ExecutionIntent(p.Symbol,p.Side,p.Quantity,true,0,0,id,L("Agent.EmergencyIntent"),action);await Db.SaveIntentAsync(cycle,intent,"INTENT",null,ct);
                var order=await exchange.FindOrderAsync(p.Symbol,id,ct)??await exchange.PlaceMarketAsync(p.Symbol,p.Side,p.Quantity,id,true,ct);await Db.SaveIntentAsync(cycle,intent,order.Status,order.OrderId,ct);for(var n=0;n<20&&order.Status is not("FILLED" or "CANCELED" or "REJECTED" or "EXPIRED");n++){await Task.Delay(500,ct);order=await exchange.FindOrderAsync(p.Symbol,id,ct)??order;}
                if(order.Status!="FILLED"){await Db.SaveIntentAsync(cycle,intent,"EMERGENCY_UNKNOWN",order.OrderId,ct);throw new InvalidOperationException(L("Agent.EmergencyUnconfirmed",p.Symbol,p.Side,order.Status));}await Db.SaveIntentAsync(cycle,intent,"COMPLETED",order.OrderId,ct);foreach(var protection in (await exchange.GetOpenOrdersAsync(p.Symbol,ct)).Where(x=>x.IsProtection&&x.PositionSide==p.Side))await exchange.CancelOrderAsync(p.Symbol,protection.OrderId,ct);await Db.ClearLockedSideIfMatchesAsync(p.Symbol,p.Side,ct);closed.Add($"{p.Symbol} {p.Side} {p.Quantity}");
            }
            var account=await exchange.GetAccountAsync(ct);var remaining=await exchange.GetPositionsAsync(ct);var orders=await exchange.GetOpenOrdersAsync(null,ct);UpdateAccount(account,remaining,orders);var result=L("Agent.EmergencyCompleted",string.Join("; ",closed));Set(AgentStatus.Paused,result);return result;
        }
        catch(Exception ex){await Db.RecordErrorAsync("EMERGENCY_CLOSE",ex,CancellationToken.None);ServiceLocator.SystemState.LastError=ex.Message;Set(AgentStatus.Degraded,L("Agent.EmergencyIncomplete",ex.Message));throw;}
        finally{ExecutionGate.Release();}
    }
    private static async Task Run(CancellationToken ct)
    {
        var settings=SettingsStore.Load();SettingsStore.ImportDesktopTestnetIfEmpty(settings);SettingsStore.ImportDesktopDeepSeekIfEmpty(settings);if(settings.Environment==ExchangeEnvironment.Mainnet&&(!settings.MainnetTradingConfirmed||settings.MainnetConfirmedAtUtc is null))throw new InvalidOperationException(L("Agent.MainnetConfirmationRequired"));var (key,secret)=SettingsStore.GetCredentials(settings);if(string.IsNullOrWhiteSpace(key))throw new InvalidOperationException(L("Agent.ApiMissing"));
        await using IExchangeAdapter exchange=new BinanceFuturesAdapter(settings.Environment,key,secret);_activeExchange=exchange;var collector=new EvidenceCollector(exchange);var executor=new ReliableOrderExecutor(exchange,Db);var planner=new RiskAndPositionPlanner();var aggregator=new SignalAggregationSkill();var governance=new DecisionGovernanceSkill();
        if(!settings.Brains.TryGetValue(settings.ActiveBrain,out var brainSlot))throw new InvalidOperationException(L("Agent.BrainMissing"));var brainKey=SecretVaultService.Decrypt(brainSlot.EncryptedKey);IBrainProvider brain=new HttpBrainProvider(brainSlot,brainKey);
        ServiceLocator.SystemState.Mode=settings.Environment==ExchangeEnvironment.Testnet?TradingMode.Testnet:TradingMode.Live;ServiceLocator.SystemState.BrainName=brain.Name;Set(AgentStatus.Running,L("Agent.Started",settings.Environment,brain.Name));var startupHealth=await brain.HealthCheckAsync(ct);if(!startupHealth.Healthy)Set(AgentStatus.Degraded,L("Agent.BrainFailure",startupHealth.Message));
        while(!ct.IsCancellationRequested)
        {
            if(_paused){await Task.Delay(1000,ct);continue;}var cycle=Guid.NewGuid().ToString("N");try{
            {
                Stage("Stage.AccountSync","OBSERVATION",18);var account=await exchange.GetAccountAsync(ct);var positions=await exchange.GetPositionsAsync(ct);var orders=await exchange.GetOpenOrdersAsync(null,ct);await Db.SaveSnapshotAsync(account,positions,orders,ct);_dayHigh=await Db.GetOrUpdateDailyHighAsync(DateOnly.FromDateTime(DateTime.UtcNow),account.Equity,ct);UpdateAccount(account,positions,orders);
                Stage("Stage.Recovery","OBSERVATION",25);var pendingRecovery=await executor.RecoverPendingAsync(ct);orders=await exchange.GetOpenOrdersAsync(null,ct);var protection=await executor.AuditAndRepairProtectionAsync(positions,orders,ct);var safeToIncreaseRisk=pendingRecovery.SafeToIncreaseRisk&&protection.SafeToIncreaseRisk;var safetyMessage=string.Join("；",pendingRecovery.Messages.Concat(protection.Messages));if(!safeToIncreaseRisk)ServiceLocator.SystemState.LastMessage=string.IsNullOrWhiteSpace(safetyMessage)?L("Agent.CycleDegraded",string.Empty):safetyMessage;
                Stage("Stage.Evidence","OBSERVATION",32);var evidence=await collector.CollectAsync(ct);Stage("Stage.Aggregation","OBSERVATION",38);var assessments=aggregator.Analyze(evidence,settings.Decision);UpdateEvidence(evidence,assessments);await Db.SaveNewsAsync(evidence.News,ct);await Db.StartCycleAsync(cycle,evidence,brain.Name,ct);
                Stage("Stage.Planner","PLANNER",48);DecisionPlan proposed;string? brainRequest=null,brainResponse=null;try{var activeSymbols=positions.Select(x=>x.Symbol).Distinct().ToArray();var outcomes=await Db.RecentOutcomesAsync(ct);var holdCount=await Db.ConsecutiveHoldCountAsync(ct);var brainResult=await brain.DecideAsync(evidence,new(brain.Name,_dayHigh>0&&(_dayHigh-account.Equity)/_dayHigh>=settings.Risk.DailyDrawdownLimit,activeSymbols.Length==1?activeSymbols[0]:null,outcomes,assessments,holdCount),ct);proposed=brainResult.Decision;brainRequest=brainResult.Request;brainResponse=brainResult.Response;}catch(BrainCallException ex){brainRequest=ex.Request;brainResponse=ex.Response;await Db.RecordErrorAsync("Brain",ex,ct);proposed=new(){Action=DecisionAction.Hold,Reason=L("Agent.BrainFailure",ex.Message)};}catch(Exception ex){await Db.RecordErrorAsync("Brain",ex,ct);proposed=new(){Action=DecisionAction.Hold,Reason=L("Agent.BrainFailureShort")};}
                Stage("Stage.Review","CRITIC",65);var review=governance.Review(proposed,assessments,evidence,settings.Decision);var decision=review.Decision;var selected=assessments.FirstOrDefault(x=>x.Symbol==decision.Instrument)??assessments.FirstOrDefault();var ui=ServiceLocator.SystemState;ui.LastDecision=decision.Action.ToString();ui.LastReason=review.Explanation;ui.DecisionDiagnostics=review.Explanation;ui.BrainConfidence=decision.Confidence*100;if(selected is not null){ui.DecisionScore=selected.NetScore*100;ui.ConflictRate=selected.ConflictRatio*100;ui.RiskLoad=Math.Clamp(selected.ConflictRatio*.60+(1-selected.Confidence)*.40,0,1)*100;ui.MarketRegime=selected.Regime.ToString().ToUpperInvariant();ui.SignalContributions=selected.Signals.ToDictionary(x=>x.Name,x=>x.WeightedScore);}Stage("Stage.Risk","RISK",78);string result;IReadOnlyList<ExecutionIntent> intents=Array.Empty<ExecutionIntent>();TradingRule? rule=null;
                if(decision.Instrument is not("BTCUSDT" or "ETHUSDT")){result=L("Agent.InvalidInstrument");}else{rule=await exchange.GetRulesAsync(decision.Instrument,ct);var lockedSide=await Db.GetLockedSideAsync(decision.Instrument,ct);var planned=planner.Plan(decision,evidence,rule,settings.Risk,_dayHigh,safeToIncreaseRisk,safetyMessage,lockedSide);intents=planned.Intents;result=planned.Result;}
                if(intents.Count>0&&rule is not null){if(_paused)result=L("Agent.PausedBeforeExecution");else{await ExecutionGate.WaitAsync(ct);try{if(_paused)result=L("Agent.PausedBeforeExecution");else{Stage("Stage.Execution","EXECUTION",91);result=await executor.ExecutePlanAsync(cycle,intents,Math.Min(settings.Risk.Leverage,rule.MaxLeverage),settings.Risk.Isolated,ct);}}finally{ExecutionGate.Release();}}}await Db.CompleteCycleAsync(cycle,decision,result,brainRequest,brainResponse,ct);await Db.RecordDecisionAuditAsync(cycle,assessments,review,ct);Set(_paused?AgentStatus.Paused:safeToIncreaseRisk?AgentStatus.Running:AgentStatus.Degraded,L("Agent.CycleResult",decision.Action,result,evidence.Completeness));Stage(_paused?"Stage.Paused":"Stage.Reflection",_paused?"SYSTEM":"REFLECTION",_paused?5:100);
            }}catch(OperationCanceledException)when(ct.IsCancellationRequested){break;}catch(Exception ex){await Db.FailCycleAsync(cycle,ServiceLocator.SystemState.SkillStage,ex,ct);await Db.RecordErrorAsync(ServiceLocator.SystemState.SkillStage,ex,ct);ServiceLocator.SystemState.LastError=ex.Message;Set(AgentStatus.Degraded,L("Agent.CycleDegraded",ex.Message));}
            ServiceLocator.SystemState.NextCycleAtUtc=DateTime.UtcNow.AddMinutes(15);StateChanged?.Invoke();await Task.Delay(TimeSpan.FromMinutes(15),ct);
        }
    }
    private static void UpdateAccount(AccountSnapshot a,IReadOnlyList<ManagedPosition> p,IReadOnlyList<ExchangeOrder> o){var s=ServiceLocator.SystemState;s.WalletBalance=a.WalletBalance;s.AvailableBalance=a.AvailableBalance;s.PositionQuantity=p.Sum(x=>x.Side==PositionSide.Long?x.Quantity:-x.Quantity);s.EntryPrice=p.FirstOrDefault()?.EntryPrice??0;s.PositionsSummary=p.Count==0?L("Agent.NoPositions"):string.Join("\n",p.Select(x=>$"{x.Symbol} {x.Side} · {x.Quantity} · {x.EntryPrice:F2} · {x.UnrealizedPnl:F2}"));s.OrdersSummary=o.Count==0?L("Agent.NoOrders"):string.Join("\n",o.Take(8).Select(x=>$"{x.Symbol} {x.Type} · {x.Status} · {x.PositionSide}"));}
    private static void UpdateEvidence(EvidencePack e,IReadOnlyList<MarketDecisionAssessment> assessments){var s=ServiceLocator.SystemState;s.EvidenceCompleteness=e.Completeness;var markets=e.Markets.Values.OrderBy(x=>x.Symbol).ToArray();s.MarketSummary=markets.Length==0?L("Agent.NoMarketEvidence"):string.Join("\n",markets.Select(x=>$"{x.Symbol} {x.Price:F2} · {x.Support:F2} · {x.Resistance:F2} · RSI {x.Rsi:F1} · {x.Derivatives.Basis:P3}"));s.NewsSummary=e.News.Count==0?L("Agent.NoNews"):string.Join("\n",e.News.Take(6).Select(x=>$"[{x.Source}] {x.Title}"));var btc=markets.FirstOrDefault(x=>x.Symbol=="BTCUSDT");var eth=markets.FirstOrDefault(x=>x.Symbol=="ETHUSDT");if(btc is not null){s.BtcPrice=btc.Price;s.BtcTrend=btc.Trend15m;s.BtcRsi=btc.Rsi;}if(eth is not null){s.EthPrice=eth.Price;s.EthTrend=eth.Trend15m;s.EthRsi=eth.Rsi;}var primary=assessments.FirstOrDefault();var market=primary is null?markets.FirstOrDefault():markets.FirstOrDefault(x=>x.Symbol==primary.Symbol);if(market is not null){s.Symbol=market.Symbol;s.Timeframe="15m / 1h / 4h";s.CurrentPrice=market.Price;s.Support=market.Support;s.Resistance=market.Resistance;}s.DecisionDiagnostics=assessments.Count==0?L("Agent.NoSignals"):string.Join("\n",assessments.Select(x=>x.Summary));s.RiskSummary=L("Agent.RiskSummary",e.Completeness,_dayHigh);}
    private static void Stage(string key,string node,int progress){var s=ServiceLocator.SystemState;s.SkillStageKey=key;s.SkillStage=L(key);s.WorkflowNode=node;s.ThinkingProgress=progress;if(node=="REFLECTION")s.ReflectionStatus="EXPERIENCE COMMITTED";s.LastUpdated=DateTime.UtcNow;StateChanged?.Invoke();}
    private static string L(string key,params object?[] args)=>LocalizationService.Current.T(key,args);
    private static void Set(AgentStatus st,string msg){var s=ServiceLocator.SystemState;s.Status=st;s.LastMessage=msg;s.LastUpdated=DateTime.UtcNow;StateChanged?.Invoke();}
}
