using Microsoft.Data.Sqlite;
using 币安量化机器人.Services.Agent;

namespace WPE.Tests;

public sealed class TeacherRecommendationOutcomeV2Tests:IDisposable
{
    private static readonly DateTimeOffset Start=new(2026,7,27,0,0,0,TimeSpan.Zero);private readonly string _dir=Path.Combine(Path.GetTempPath(),"teacher-outcome-"+Guid.NewGuid().ToString("N"));private string Db=>Path.Combine(_dir,"agent.db");public TeacherRecommendationOutcomeV2Tests()=>Directory.CreateDirectory(_dir);public void Dispose(){SqliteConnection.ClearAllPools();try{Directory.Delete(_dir,true);}catch(IOException){}}
    [Fact] public void OutcomeUsesPointInTimeFactsBenchmarkAndExcursions()
    {
        var entry=Fact("ETHUSDT",Start.AddMinutes(-1),Start,100m,"e");var mid=Fact("ETHUSDT",Start.AddHours(1),Start.AddHours(1),95m,"m");var exit=Fact("ETHUSDT",Start.AddHours(4),Start.AddHours(4),110m,"x");var b0=Fact("BTCUSDT",Start.AddMinutes(-1),Start,200m,"b0");var b1=Fact("BTCUSDT",Start.AddHours(4),Start.AddHours(4),210m,"b1");var recommendation=Recommendation(entry);var outcome=TeacherRecommendationOutcomeEvaluatorV2.Evaluate(recommendation,entry,exit,"BTCUSDT",b0,b1,[entry,mid,exit],false,Start.AddHours(4));Assert.Equal(10m,outcome.InstrumentReturnPct);Assert.Equal(5m,outcome.BenchmarkReturnPct);Assert.Equal(5m,outcome.RelativeReturnPct);Assert.Equal(-5m,outcome.MaximumAdverseExcursionPct);Assert.Equal(10m,outcome.MaximumFavorableExcursionPct);Assert.Equal("conditions-followed",outcome.ProcessState);Assert.Equal(64,outcome.CanonicalSha256.Length);
    }
    [Fact] public void LookAheadOrUnboundEntryEvidenceIsRejected()
    {
        var entry=Fact("ETHUSDT",Start.AddMinutes(-1),Start.AddMinutes(1),100m,"e");var exit=Fact("ETHUSDT",Start.AddHours(4),Start.AddHours(4),110m,"x");var b0=Fact("BTCUSDT",Start.AddMinutes(-1),Start,200m,"b0");var b1=Fact("BTCUSDT",Start.AddHours(4),Start.AddHours(4),210m,"b1");Assert.Throws<InvalidOperationException>(()=>TeacherRecommendationOutcomeEvaluatorV2.Evaluate(Recommendation(entry),entry,exit,"BTCUSDT",b0,b1,[entry,exit],false,Start.AddHours(4)));var valid=Fact("ETHUSDT",Start.AddMinutes(-1),Start,100m,"v");Assert.Throws<InvalidOperationException>(()=>TeacherRecommendationOutcomeEvaluatorV2.Evaluate(Recommendation(valid) with{EvidenceHashes=[]},valid,exit,"BTCUSDT",b0,b1,[valid,exit],false,Start.AddHours(4)));
    }
    [Fact] public async Task HistoricalQueryRejectsLateRetrievedFactsAndOutcomeIsAppendOnly()
    {
        var timely=Fact("ETHUSDT",Start.AddMinutes(-1),Start,100m,"t");var late=Fact("ETHUSDT",Start.AddMinutes(1),Start.AddMinutes(3),101m,"l");var store=new AgentSqliteStore(Db);await store.SaveTeacherCryptoEvidenceAsync(timely,default);await store.SaveTeacherCryptoEvidenceAsync(late,default);var replay=await store.GetTeacherCryptoEvidenceRangeAsync("ETHUSDT",Start.AddMinutes(-2),Start.AddMinutes(2),default);Assert.Single(replay);Assert.Equal(timely.CanonicalSha256,replay[0].CanonicalSha256);var exit=Fact("ETHUSDT",Start.AddHours(4),Start.AddHours(4),110m,"x");var b0=Fact("BTCUSDT",Start,Start,200m,"b0");var b1=Fact("BTCUSDT",Start.AddHours(4),Start.AddHours(4),210m,"b1");var outcome=TeacherRecommendationOutcomeEvaluatorV2.Evaluate(Recommendation(timely),timely,exit,"BTCUSDT",b0,b1,[timely,exit],false,Start.AddHours(4));Assert.True((await store.SaveTeacherRecommendationOutcomeAsync(outcome,default)).Succeeded);Assert.True((await new AgentSqliteStore(Db).SaveTeacherRecommendationOutcomeAsync(outcome,default)).Idempotent);await using var c=new SqliteConnection($"Data Source={Db}");await c.OpenAsync();await using var q=c.CreateCommand();q.CommandText="UPDATE teacher_recommendation_outcomes SET process_state='lucky'";await Assert.ThrowsAsync<SqliteException>(()=>q.ExecuteNonQueryAsync());
    }
    private static TeacherRecommendationV2 Recommendation(TeacherCryptoMarketFactV2 entry)=>new("rec","wpe.teacher-recommendation/2.0",1,"ETHUSDT","crypto",TeacherRecommendationStateV2.PriorityWatch,"4h",Start,Start.AddHours(4),"research only",[entry.CanonicalSha256],["confirm"],["invalidate"],["risk"],null,false);private static TeacherCryptoMarketFactV2 Fact(string symbol,DateTimeOffset observed,DateTimeOffset retrieved,decimal price,string salt)=>TeacherCryptoMarketFactCanonicalizerV2.Create("binance-futures-public",symbol,observed,retrieved,price,price-.1m,.0001m,retrieved.AddHours(2),1000m,1m,1000m,[Hash(salt+"1"),Hash(salt+"2"),Hash(salt+"3")]);private static string Hash(string value)=>Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
}
