'use client'
import {useEffect,useRef,useState} from 'react'
import {usePathname} from 'next/navigation'
import Link from 'next/link'
import {Search,Command,Menu,X,Languages,Check} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {CommandPalette} from '@/components/shell/command-palette'
import {flatNav,navGroups} from '@/lib/nav'
import {cn} from '@/lib/utils'
import {useWpeRuntime} from '@/components/runtime-bridge'
import {localeMeta,locales} from '@/lib/i18n/dictionaries'
import {useI18n} from '@/lib/i18n/context'
function MarketTicker(){const runtime=useWpeRuntime(),{t,formatNumber}=useI18n();const live=runtime.runtimeFresh===true?(runtime.markets??[]).filter(x=>(x.price??0)>0).map(x=>({symbol:x.symbol,price:x.price??0,change:x.changePercent??x.trend??0})):[];if(!live.length)return <div className="hidden flex-1 text-xs text-muted-foreground md:block">{t('shell.marketUnavailable')}</div>;return <div className="hidden max-w-md flex-1 overflow-hidden md:block"><div className="flex w-max animate-ticker gap-6">{[...live,...live].map((item,index)=><div key={`${item.symbol}-${index}`} className="flex items-center gap-1.5 whitespace-nowrap text-xs"><span className="font-medium">{item.symbol}</span><span className="tabular text-muted-foreground">${formatNumber(item.price,{maximumFractionDigits:8})}</span><span className={cn('tabular',item.change>=0?'text-success':'text-danger')}>{item.change>=0?'+':''}{formatNumber(item.change,{maximumFractionDigits:2})}%</span></div>)}</div></div>}
export function Topbar(){const runtime=useWpeRuntime(),pathname=usePathname(),{t,locale,setLocale}=useI18n();const[open,setOpen]=useState(false),[mobilePath,setMobilePath]=useState<string|null>(null),[languageOpen,setLanguageOpen]=useState(false);const menuRef=useRef<HTMLDivElement>(null),menuTriggerRef=useRef<HTMLButtonElement>(null),mobileDialogRef=useRef<HTMLDivElement>(null),mobileCloseRef=useRef<HTMLButtonElement>(null),mobileNav=mobilePath===pathname,current=flatNav.find(x=>x.href===pathname);useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setOpen(value=>!value)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);useEffect(()=>{const close=(event:MouseEvent)=>{if(!menuRef.current?.contains(event.target as Node))setLanguageOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);useEffect(()=>{if(!mobileNav)return;const dialog=mobileDialogRef.current,trigger=menuTriggerRef.current;if(!dialog)return;const background:Array<{element:HTMLElement;inert:boolean;ariaHidden:string|null}>=[];let branch:HTMLElement=dialog,parent=dialog.parentElement;while(parent&&parent!==document.body){for(const sibling of Array.from(parent.children)){if(sibling===branch||!(sibling instanceof HTMLElement))continue;background.push({element:sibling,inert:sibling.inert,ariaHidden:sibling.getAttribute('aria-hidden')});sibling.inert=true;sibling.setAttribute('aria-hidden','true')}branch=parent;parent=parent.parentElement}const focusable=()=>Array.from(dialog.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),[tabindex]:not([tabindex="-1"])')).filter(element=>!element.inert);const handleKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setMobilePath(null);return}if(event.key!=='Tab')return;const items=focusable();if(!items.length){event.preventDefault();return}const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener('keydown',handleKeyDown);mobileCloseRef.current?.focus();return()=>{document.removeEventListener('keydown',handleKeyDown);for(const {element,inert,ariaHidden} of background){element.inert=inert;if(ariaHidden===null)element.removeAttribute('aria-hidden');else element.setAttribute('aria-hidden',ariaHidden)}trigger?.focus()}},[mobileNav]);return <>
 <header className="glass sticky top-0 z-40 flex h-14 items-center gap-3 border-b border-border px-4"><button ref={menuTriggerRef} className="md:hidden" onClick={()=>setMobilePath(pathname)} aria-label={t('shell.openMenu')} aria-expanded={mobileNav} aria-controls="mobile-navigation"><Menu className="size-5"/></button><div className="flex min-w-0 items-center gap-2"><h1 className="truncate text-sm font-semibold">{current?t(current.labelKey):'WPE Agent'}</h1><span className="hidden font-mono text-[10px] text-muted-foreground sm:inline">/ {pathname}</span></div><div className="ml-2 hidden h-6 w-px bg-border lg:block"/><MarketTicker/><div className="ml-auto flex items-center gap-1.5"><div className="hidden items-center gap-1.5 rounded-md border border-border px-2 py-1 text-[10px] text-muted-foreground lg:flex"><span className={cn('size-1.5 rounded-full',runtime.runtimeFresh&&runtime.exchangeConnected?'bg-success':'bg-warning')}/>{runtime.runtimeFresh&&runtime.environment?runtime.environment:t('shell.environmentUnknown')}<span className="opacity-50">·</span>{runtime.runtimeFresh!==true?t('common.notConnected'):runtime.brainConnected?t('shell.brainOnline'):t('shell.brainPending')}</div>
 <div className="relative" ref={menuRef}><Button variant="ghost" size="icon" aria-label={t('shell.changeLanguage')} aria-expanded={languageOpen} onClick={()=>setLanguageOpen(value=>!value)}><Languages className="size-4"/></Button>{languageOpen&&<div className="absolute right-0 top-11 z-50 w-44 rounded-lg border border-border bg-popover p-1 shadow-xl"><div className="px-2 py-1.5 text-[10px] font-medium uppercase text-muted-foreground">{t('shell.language')}</div>{locales.map(item=><button key={item} type="button" lang={localeMeta[item].htmlLang} onClick={()=>{setLocale(item);setLanguageOpen(false)}} className="flex w-full items-center gap-2 rounded-md px-2 py-2 text-left text-xs hover:bg-accent"><span className="min-w-0 flex-1">{localeMeta[item].name}</span>{locale===item&&<Check className="size-3.5 text-info"/>}</button>)}</div>}</div>
 <button onClick={()=>setOpen(true)} className="hidden items-center gap-2 rounded-lg border border-border bg-muted/40 px-3 py-1.5 text-xs text-muted-foreground sm:flex"><Search className="size-3.5"/><span>{t('common.search')}</span><kbd className="flex items-center rounded border border-border px-1 font-mono text-[10px]"><Command className="size-2.5"/>K</kbd></button><Button variant="ghost" size="icon" className="sm:hidden" onClick={()=>setOpen(true)} aria-label={t('common.search')}><Search className="size-4"/></Button><div className="ml-1 flex size-8 items-center justify-center rounded-full bg-ai/15 text-xs font-semibold text-ai">{runtime.runtimeFresh&&runtime.loggedInUser?runtime.loggedInUser.slice(0,2).toUpperCase():'--'}</div></div></header>
 <CommandPalette open={open} onClose={()=>setOpen(false)}/>{mobileNav&&<div ref={mobileDialogRef} id="mobile-navigation" className="fixed inset-0 z-50 md:hidden" role="dialog" aria-modal="true" aria-label={t('shell.openMenu')}><div className="absolute inset-0 bg-background/70 backdrop-blur-sm" aria-hidden="true" onClick={()=>setMobilePath(null)}/><div className="glass absolute left-0 top-0 h-full w-[min(18rem,85vw)] overflow-y-auto border-r border-border p-4"><div className="mb-4 flex items-center justify-between"><span className="text-sm font-semibold">WPE Agent</span><button ref={mobileCloseRef} onClick={()=>setMobilePath(null)} aria-label={t('shell.closeMenu')}><X className="size-5"/></button></div>{navGroups.map(group=><div key={group.titleKey} className="mb-4"><div className="px-2 pb-1.5 text-[10px] uppercase text-muted-foreground">{t(group.titleKey)}</div>{group.items.map(item=>{const Icon=item.icon;return <Link key={item.href} href={item.href} onClick={()=>setMobilePath(null)} className={cn('flex items-center gap-2.5 rounded-lg px-2 py-2 text-sm',pathname===item.href?'bg-accent':'text-muted-foreground')}><Icon className="size-4.5"/><span className="break-words">{t(item.labelKey)}</span></Link>})}</div>)}</div></div>}</>}
