import assert from'node:assert/strict'
import test from'node:test'
import{normalizeRuntimeEvent,unavailableRuntimeState}from'./runtime-bridge'

const now=new Date(),source=new Date(now.getTime()-1000)
const snapshot=(overrides:Record<string,unknown>={})=>({contractVersion:'1.0',generatedAtUtc:now.toISOString(),sourceUpdatedAtUtc:source.toISOString(),freshness:{fresh:true,ageSeconds:1,staleAfterSeconds:15},environment:'Testnet',connectionStatus:{state:'Available',value:{connectionId:'primary',displayName:'Primary',providerId:'binance',environment:'Testnet',credentialStatus:'configured',adapterStatus:'ready',lastCheckedAtUtc:now.toISOString(),ready:true,exchangeConnected:true,tradePermission:true,withdrawPermission:false}},...overrides})

test('trusted Testnet snapshot exposes provenance and enables allowlisted controls',()=>{const value=normalizeRuntimeEvent(snapshot());assert.equal(value?.runtimeFresh,true);assert.equal(value?.runtimeProviderId,'binance');assert.equal(value?.environment,'Testnet');assert.equal(value?.sourceTimestampUtc,source.toISOString());assert.equal(value?.snapshotTimestampUtc,now.toISOString());assert.equal(value?.agentStartAllowed,true);assert.equal(value?.agentStopAllowed,true)})
test('stale idle Testnet snapshot permits host-revalidated start but remains untrusted for data',()=>{const normalized=normalizeRuntimeEvent(snapshot({freshness:{fresh:false,ageSeconds:20,staleAfterSeconds:15},legacyFields:{agentIsRunning:false}}));assert.equal(normalized?.runtimeFresh,false);assert.equal(normalized?.agentStartAllowed,true);assert.equal(normalized?.agentStopAllowed,false)})
test('stale running Testnet snapshot keeps stop available',()=>{const normalized=normalizeRuntimeEvent(snapshot({freshness:{fresh:false,ageSeconds:20,staleAfterSeconds:15},legacyFields:{agentIsRunning:true}}));assert.equal(normalized?.runtimeFresh,false);assert.equal(normalized?.agentStartAllowed,false);assert.equal(normalized?.agentStopAllowed,true)})
test('future unsupported malformed and Mainnet snapshots remain untrusted',()=>{const cases=[snapshot({sourceUpdatedAtUtc:new Date(now.getTime()+10000).toISOString()}),snapshot({connectionStatus:{state:'Unsupported'}}),snapshot({contractVersion:'2.0'}),snapshot({environment:'Mainnet'})];for(const value of cases){const normalized=normalizeRuntimeEvent(value);assert.notEqual(normalized?.runtimeFresh,true)}})
test('revoked authority is visibly unavailable while an idle host may revalidate start',()=>{const normalized=normalizeRuntimeEvent(snapshot({legacyFields:{agentIsRunning:false},connectionStatus:{state:'Available',value:{connectionId:'primary',displayName:'Primary',providerId:'binance',environment:'Testnet',credentialStatus:'configured',adapterStatus:'ready',lastCheckedAtUtc:now.toISOString(),ready:false,exchangeConnected:false,tradePermission:false,withdrawPermission:false}}}));assert.equal(normalized?.runtimeFresh,false);assert.equal(normalized?.agentStartAllowed,true);assert.equal(normalized?.agentStopAllowed,false);assert.match(normalized?.runtimeDiagnosticReason??'',/authority/)})
test('host disconnected is visibly unavailable with both controls disabled',()=>{const state=unavailableRuntimeState(false,'WPF runtime host is disconnected.');assert.equal(state.hostConnected,false);assert.equal(state.runtimeFresh,false);assert.equal(state.agentStartAllowed,false);assert.equal(state.agentStopAllowed,false);assert.match(state.runtimeDiagnosticReason??'',/disconnected/)})
test('automatic execution summaries survive the bridge without order inference',()=>{const updatedAtUtc=source.toISOString();const normalized=normalizeRuntimeEvent(snapshot({automaticExecutions:{state:'Available',items:[{executionId:'execution-1',status:'RiskApproved',code:'automatic.risk-approved',attemptCount:0,updatedAtUtc}]}}));assert.equal(normalized?.automaticExecutions?.state,'available');assert.deepEqual(normalized?.automaticExecutions?.items,[{executionId:'execution-1',status:'RiskApproved',code:'automatic.risk-approved',attemptCount:0,updatedAtUtc}])})
test('malformed automatic execution rows are withheld fail closed',()=>{const normalized=normalizeRuntimeEvent(snapshot({automaticExecutions:{state:'Available',items:[{executionId:'execution-1',status:'Succeeded',code:'automatic.succeeded',attemptCount:-1,updatedAtUtc:'not-a-date'}]}}));assert.equal(normalized?.automaticExecutions?.state,'error');assert.deepEqual(normalized?.automaticExecutions?.items,[])})
test('telegram subscriber projection exposes only masked identity and validated scope',()=>{const normalized=normalizeRuntimeEvent(snapshot({telegramSubscribers:{state:'Available',items:[{subscriberId:'tg#012345abcdef',chatType:'private',state:'Pending',eventKinds:[],firstSeenAtUtc:source.toISOString(),updatedAtUtc:source.toISOString()}]}}));assert.deepEqual(normalized?.telegramSubscribers,[{subscriberId:'tg#012345abcdef',chatType:'private',state:'Pending',eventKinds:[],firstSeenAtUtc:source.toISOString(),updatedAtUtc:source.toISOString()}]);assert.doesNotMatch(JSON.stringify(normalized?.telegramSubscribers),/-100\d{4,}/)})
test('telegram subscriber rows with raw chat identity fail closed',()=>{const normalized=normalizeRuntimeEvent(snapshot({telegramSubscribers:{state:'Available',items:[{subscriberId:'-100998877',chatType:'private',state:'Approved',eventKinds:['MarketBrief'],firstSeenAtUtc:source.toISOString(),updatedAtUtc:source.toISOString()}]}}));assert.equal(normalized?.collectionStates?.telegramSubscribers,'error');assert.deepEqual(normalized?.telegramSubscribers,[])})

test('historical PnL drift strips opaque identity and rejects inconsistent comparability',()=>{const secret='PNL-OPAQUE-MUST-NOT-SURVIVE';const row={sequence:1,comparedAtUtc:source.toISOString(),strategyId:'trend-alpha',strategyVersion:'v1',symbol:'BTCUSDT',side:'Long',closingQuantity:1,state:'GrossComparable',actualGrossPnl:10,simulatedGrossPnl:9,observedMinusSimulatedGrossPnl:1,feeAdjustedPnlComparable:false,observedMinusSimulatedFeeAdjustedPnl:null,netPnlComparable:false,reasonCode:'gross-pnl-comparable-fee-or-funding-unavailable',closeClientOrderId:secret,canonicalSha256:secret};const collection={state:'Available',items:[row],nextCursor:null,sourceUpdatedAtUtc:source.toISOString(),source:'local-agent-sqlite'};const normalized=normalizeRuntimeEvent(snapshot({historicalPostTradePnlDrift:collection}));assert.equal(normalized?.collectionStates?.historicalPostTradePnlDrift,'available');assert.equal(normalized?.historicalPostTradePnlDrift?.items[0]?.observedMinusSimulatedGrossPnl,1);assert.doesNotMatch(JSON.stringify(normalized?.historicalPostTradePnlDrift),new RegExp(secret));const inconsistent=normalizeRuntimeEvent(snapshot({historicalPostTradePnlDrift:{...collection,items:[{...row,state:'FeeAdjustedComparable'}]}}));assert.equal(inconsistent?.collectionStates?.historicalPostTradePnlDrift,'error');assert.deepEqual(inconsistent?.historicalPostTradePnlDrift?.items,[])})
