import assert from'node:assert/strict'
import test from'node:test'
import{normalizeRuntimeEvent,unavailableRuntimeState}from'./runtime-bridge'

const now=new Date(),source=new Date(now.getTime()-1000)
const snapshot=(overrides:Record<string,unknown>={})=>({contractVersion:'1.0',generatedAtUtc:now.toISOString(),sourceUpdatedAtUtc:source.toISOString(),freshness:{fresh:true,ageSeconds:1,staleAfterSeconds:15},environment:'Testnet',connectionStatus:{state:'Available',value:{connectionId:'primary',displayName:'Primary',providerId:'binance',environment:'Testnet',credentialStatus:'configured',adapterStatus:'ready',lastCheckedAtUtc:now.toISOString(),ready:true,exchangeConnected:true,tradePermission:true,withdrawPermission:false}},...overrides})

test('trusted Testnet snapshot exposes provenance and enables allowlisted controls',()=>{const value=normalizeRuntimeEvent(snapshot());assert.equal(value?.runtimeFresh,true);assert.equal(value?.runtimeProviderId,'binance');assert.equal(value?.environment,'Testnet');assert.equal(value?.sourceTimestampUtc,source.toISOString());assert.equal(value?.snapshotTimestampUtc,now.toISOString());assert.equal(value?.agentStartAllowed,true);assert.equal(value?.agentStopAllowed,true)})
test('stale future unsupported malformed and Mainnet snapshots fail closed',()=>{const cases=[snapshot({freshness:{fresh:false,ageSeconds:20,staleAfterSeconds:15}}),snapshot({sourceUpdatedAtUtc:new Date(now.getTime()+10000).toISOString()}),snapshot({connectionStatus:{state:'Unsupported'}}),snapshot({contractVersion:'2.0'}),snapshot({environment:'Mainnet'})];for(const value of cases){const normalized=normalizeRuntimeEvent(value);assert.notEqual(normalized?.agentStartAllowed,true);assert.notEqual(normalized?.runtimeFresh,true)}})
test('revoked authority is visibly unavailable with both controls disabled',()=>{const normalized=normalizeRuntimeEvent(snapshot({connectionStatus:{state:'Available',value:{connectionId:'primary',displayName:'Primary',providerId:'binance',environment:'Testnet',credentialStatus:'configured',adapterStatus:'ready',lastCheckedAtUtc:now.toISOString(),ready:false,exchangeConnected:false,tradePermission:false,withdrawPermission:false}}}));assert.equal(normalized?.runtimeFresh,false);assert.equal(normalized?.agentStartAllowed,false);assert.equal(normalized?.agentStopAllowed,false);assert.match(normalized?.runtimeDiagnosticReason??'',/authority/)})
test('host disconnected is visibly unavailable with both controls disabled',()=>{const state=unavailableRuntimeState(false,'WPF runtime host is disconnected.');assert.equal(state.hostConnected,false);assert.equal(state.runtimeFresh,false);assert.equal(state.agentStartAllowed,false);assert.equal(state.agentStopAllowed,false);assert.match(state.runtimeDiagnosticReason??'',/disconnected/)})
