import assert from'node:assert/strict'
import test from'node:test'
import{normalizeRuntimeEvent,unavailableRuntimeState}from'./runtime-bridge'

const now=new Date(),source=new Date(now.getTime()-1000)
const snapshot=(overrides:Record<string,unknown>={})=>({contractVersion:'1.0',generatedAtUtc:now.toISOString(),sourceUpdatedAtUtc:source.toISOString(),freshness:{fresh:true,ageSeconds:1,staleAfterSeconds:15},environment:'Testnet',connectionStatus:{state:'Available',value:{connectionId:'primary',displayName:'Primary',providerId:'binance',environment:'Testnet',credentialStatus:'configured',adapterStatus:'ready',lastCheckedAtUtc:now.toISOString(),ready:true,exchangeConnected:true,tradePermission:true,withdrawPermission:false}},...overrides})

test('trusted Testnet snapshot exposes provenance and enables allowlisted controls',()=>{const value=normalizeRuntimeEvent(snapshot());assert.equal(value?.runtimeFresh,true);assert.equal(value?.runtimeProviderId,'binance');assert.equal(value?.environment,'Testnet');assert.equal(value?.sourceTimestampUtc,source.toISOString());assert.equal(value?.snapshotTimestampUtc,now.toISOString());assert.equal(value?.agentStartAllowed,true);assert.equal(value?.agentStopAllowed,true)})
test('stale idle Testnet snapshot permits host-revalidated start but remains untrusted for data',()=>{const normalized=normalizeRuntimeEvent(snapshot({freshness:{fresh:false,ageSeconds:20,staleAfterSeconds:15},legacyFields:{agentIsRunning:false}}));assert.equal(normalized?.runtimeFresh,false);assert.equal(normalized?.agentStartAllowed,true);assert.equal(normalized?.agentStopAllowed,false)})
test('stale running Testnet snapshot keeps stop available',()=>{const normalized=normalizeRuntimeEvent(snapshot({freshness:{fresh:false,ageSeconds:20,staleAfterSeconds:15},legacyFields:{agentIsRunning:true}}));assert.equal(normalized?.runtimeFresh,false);assert.equal(normalized?.agentStartAllowed,false);assert.equal(normalized?.agentStopAllowed,true)})
test('future unsupported malformed and Mainnet snapshots remain untrusted',()=>{const cases=[snapshot({sourceUpdatedAtUtc:new Date(now.getTime()+10000).toISOString()}),snapshot({connectionStatus:{state:'Unsupported'}}),snapshot({contractVersion:'2.0'}),snapshot({environment:'Mainnet'})];for(const value of cases){const normalized=normalizeRuntimeEvent(value);assert.notEqual(normalized?.runtimeFresh,true)}})
test('revoked authority is visibly unavailable while an idle host may revalidate start',()=>{const normalized=normalizeRuntimeEvent(snapshot({legacyFields:{agentIsRunning:false},connectionStatus:{state:'Available',value:{connectionId:'primary',displayName:'Primary',providerId:'binance',environment:'Testnet',credentialStatus:'configured',adapterStatus:'ready',lastCheckedAtUtc:now.toISOString(),ready:false,exchangeConnected:false,tradePermission:false,withdrawPermission:false}}}));assert.equal(normalized?.runtimeFresh,false);assert.equal(normalized?.agentStartAllowed,true);assert.equal(normalized?.agentStopAllowed,false);assert.match(normalized?.runtimeDiagnosticReason??'',/authority/)})
test('host disconnected is visibly unavailable with both controls disabled',()=>{const state=unavailableRuntimeState(false,'WPF runtime host is disconnected.');assert.equal(state.hostConnected,false);assert.equal(state.runtimeFresh,false);assert.equal(state.agentStartAllowed,false);assert.equal(state.agentStopAllowed,false);assert.match(state.runtimeDiagnosticReason??'',/disconnected/)})
test('automatic execution summaries survive the bridge only with masked identity',()=>{const updatedAtUtc=source.toISOString();const normalized=normalizeRuntimeEvent(snapshot({automaticExecutions:{state:'Available',items:[{executionId:'execution#ABCDEF123456',status:'RiskApproved',code:'automatic.risk-approved',attemptCount:0,updatedAtUtc}]}}));assert.equal(normalized?.automaticExecutions?.state,'available');assert.deepEqual(normalized?.automaticExecutions?.items,[{executionId:'execution#ABCDEF123456',status:'RiskApproved',code:'automatic.risk-approved',attemptCount:0,updatedAtUtc}])})
test('malformed or raw automatic execution rows are withheld fail closed',()=>{for(const item of [{executionId:'execution#ABCDEF123456',status:'Succeeded',code:'automatic.succeeded',attemptCount:-1,updatedAtUtc:'not-a-date'},{executionId:'execution-private',status:'RiskApproved',code:'automatic.risk-approved',attemptCount:0,updatedAtUtc:source.toISOString()}]){const normalized=normalizeRuntimeEvent(snapshot({automaticExecutions:{state:'Available',items:[item]}}));assert.equal(normalized?.automaticExecutions?.state,'error');assert.deepEqual(normalized?.automaticExecutions?.items,[])}})
test('telegram subscriber projection exposes only masked identity and validated scope',()=>{const normalized=normalizeRuntimeEvent(snapshot({telegramSubscribers:{state:'Available',items:[{subscriberId:'tg#012345abcdef',chatType:'private',state:'Pending',eventKinds:[],firstSeenAtUtc:source.toISOString(),updatedAtUtc:source.toISOString()}]}}));assert.deepEqual(normalized?.telegramSubscribers,[{subscriberId:'tg#012345abcdef',chatType:'private',state:'Pending',eventKinds:[],firstSeenAtUtc:source.toISOString(),updatedAtUtc:source.toISOString()}]);assert.doesNotMatch(JSON.stringify(normalized?.telegramSubscribers),/-100\d{4,}/)})
test('telegram subscriber rows with raw chat identity fail closed',()=>{const normalized=normalizeRuntimeEvent(snapshot({telegramSubscribers:{state:'Available',items:[{subscriberId:'-100998877',chatType:'private',state:'Approved',eventKinds:['MarketBrief'],firstSeenAtUtc:source.toISOString(),updatedAtUtc:source.toISOString()}]}}));assert.equal(normalized?.collectionStates?.telegramSubscribers,'error');assert.deepEqual(normalized?.telegramSubscribers,[])})

test('post-trade review and reconciliation histories survive the bridge as read-only facts',()=>{const hash='a'.repeat(64),closedAtUtc=source.toISOString(),normalized=normalizeRuntimeEvent(snapshot({historicalPostTradeReviews:{state:'Available',items:[{traceId:'trade#ABCDEF123456',schema:'wpe.post-trade-review/1.4',symbol:'BTCUSDT',side:'Long',entryPrice:100,exitPrice:110,quantity:1,fees:.05,feeBasis:'exchange-reported-usdt',feeRate:0,entrySlippageAmount:.1,exitSlippageAmount:.2,totalSlippageAmount:.3,slippageBasis:'intent-expected-vs-fill',fundingAmount:1.25,fundingBasis:'exchange-reported-window',netPnl:11.2,returnPct:.112,outcome:'win',closedAtUtc,strategyId:'trend-alpha',strategyVersion:'2.1.0',attributionBasis:'automatic-artifact',traceState:'available',riskDecision:'Approved',executionStatus:'Succeeded',executionCode:'automatic.succeeded',executionAttempts:1,marketCollectedAtUtc:closedAtUtc,marketDataVersion:'provider-market-v1',evidenceState:'available',evidenceChain:[{stage:'market',status:'succeeded',canonicalSha256:'b'.repeat(64),asOfUtc:closedAtUtc},{stage:'research',status:'succeeded',canonicalSha256:'c'.repeat(64),asOfUtc:closedAtUtc},{stage:'strategy',status:'succeeded',canonicalSha256:'d'.repeat(64),asOfUtc:closedAtUtc},{stage:'risk',status:'succeeded',canonicalSha256:'e'.repeat(64),asOfUtc:closedAtUtc}]}],nextCursor:null,sourceUpdatedAtUtc:closedAtUtc,source:'local-agent-sqlite'},historicalReconciliations:{state:'Available',items:[{kind:'position',traceId:'reconciliation#ABCDEF123456',schema:'wpe.position-reconciliation/1.0',observedAtUtc:closedAtUtc,evaluatedAtUtc:closedAtUtc,state:'Confirmed',allowsRiskIncrease:true,canonicalSha256:hash}],nextCursor:null,sourceUpdatedAtUtc:closedAtUtc,source:'local-agent-sqlite'}}));assert.equal(normalized?.historicalPostTradeReviews?.state,'available');assert.equal(normalized?.historicalPostTradeReviews?.items[0]?.strategyId,'trend-alpha');assert.equal(normalized?.historicalPostTradeReviews?.items[0]?.netPnl,11.2);assert.equal(normalized?.historicalPostTradeReviews?.items[0]?.traceId,'trade#ABCDEF123456');assert.equal(normalized?.historicalPostTradeReviews?.items[0]?.riskDecision,'Approved');assert.equal(normalized?.historicalPostTradeReviews?.items[0]?.executionStatus,'Succeeded');assert.equal(normalized?.historicalPostTradeReviews?.items[0]?.evidenceState,'available');assert.equal(normalized?.historicalPostTradeReviews?.items[0]?.evidenceChain.length,4);assert.equal(normalized?.historicalReconciliations?.state,'available');assert.equal(normalized?.historicalReconciliations?.items[0]?.state,'Confirmed');assert.doesNotMatch(JSON.stringify(normalized?.historicalReconciliations),/canonicalBytes/)})
test('malformed settlement or reconciliation history fails closed',()=>{const badReview=normalizeRuntimeEvent(snapshot({historicalPostTradeReviews:{state:'Available',items:[{traceId:'trade#ABCDEF123456',schema:'wpe.post-trade-review/1.4',symbol:'BTCUSDT',side:'Long',entryPrice:100,exitPrice:110,quantity:1,fees:-1,feeBasis:'bad',feeRate:0,entrySlippageAmount:0,exitSlippageAmount:0,totalSlippageAmount:0,slippageBasis:'unavailable',fundingAmount:0,fundingBasis:'unavailable',netPnl:1,returnPct:.01,outcome:'win',closedAtUtc:source.toISOString(),strategyId:null,strategyVersion:'v1',attributionBasis:'legacy-version-only',traceState:'legacy',riskDecision:'Unavailable',executionStatus:'Unavailable',executionCode:'trace.execution-unavailable',executionAttempts:null,marketCollectedAtUtc:null,marketDataVersion:null,evidenceState:'unavailable',evidenceChain:[]}],nextCursor:null,sourceUpdatedAtUtc:source.toISOString(),source:'local-agent-sqlite'}}));assert.equal(badReview?.historicalPostTradeReviews?.state,'error');assert.deepEqual(badReview?.historicalPostTradeReviews?.items,[]);const badReconciliation=normalizeRuntimeEvent(snapshot({historicalReconciliations:{state:'Available',items:[{kind:'position',traceId:'reconciliation#ABCDEF123456',schema:'schema/1.0',observedAtUtc:source.toISOString(),evaluatedAtUtc:source.toISOString(),state:'Confirmed',allowsRiskIncrease:true,canonicalSha256:'bad'}],nextCursor:null,sourceUpdatedAtUtc:source.toISOString(),source:'local-agent-sqlite'}}));assert.equal(badReconciliation?.historicalReconciliations?.state,'error');assert.deepEqual(badReconciliation?.historicalReconciliations?.items,[])})

test('raw post-trade identities are rejected by the bridge',()=>{const normalized=normalizeRuntimeEvent(snapshot({historicalPostTradeReviews:{state:'Available',items:[{traceId:'trade#ABCDEF123456',schema:'wpe.post-trade-review/1.4',symbol:'BTCUSDT',side:'Long',entryPrice:100,exitPrice:110,quantity:1,fees:.05,feeBasis:'exchange-reported-usdt',feeRate:0,entrySlippageAmount:0,exitSlippageAmount:0,totalSlippageAmount:0,slippageBasis:'unavailable',fundingAmount:0,fundingBasis:'unavailable',netPnl:1,returnPct:.01,outcome:'win',closedAtUtc:source.toISOString(),strategyId:null,strategyVersion:'v1',attributionBasis:'legacy-version-only',traceState:'legacy',riskDecision:'Unavailable',executionStatus:'Unavailable',executionCode:'trace.execution-unavailable',executionAttempts:null,marketCollectedAtUtc:null,marketDataVersion:null,cycleId:'MUST-NOT-ENTER-WEB'}],nextCursor:null,sourceUpdatedAtUtc:source.toISOString(),source:'local-agent-sqlite'}}));assert.equal(normalized?.historicalPostTradeReviews?.state,'error');assert.deepEqual(normalized?.historicalPostTradeReviews?.items,[])})

test('raw reconciliation report identity is rejected by the bridge',()=>{const normalized=normalizeRuntimeEvent(snapshot({historicalReconciliations:{state:'Available',items:[{kind:'position',traceId:'reconciliation#ABCDEF123456',reportId:'MUST-NOT-ENTER-WEB',schema:'wpe.position-reconciliation/1.0',observedAtUtc:source.toISOString(),evaluatedAtUtc:source.toISOString(),state:'Confirmed',allowsRiskIncrease:true,canonicalSha256:'a'.repeat(64)}],nextCursor:null,sourceUpdatedAtUtc:source.toISOString(),source:'local-agent-sqlite'}}));assert.equal(normalized?.historicalReconciliations?.state,'error');assert.deepEqual(normalized?.historicalReconciliations?.items,[])})

test('canonical evidence payload fields are rejected by the bridge',()=>{const closedAtUtc=source.toISOString(),normalized=normalizeRuntimeEvent(snapshot({historicalPostTradeReviews:{state:'Available',items:[{traceId:'trade#ABCDEF123456',schema:'wpe.post-trade-review/1.4',symbol:'BTCUSDT',side:'Long',entryPrice:100,exitPrice:110,quantity:1,fees:.05,feeBasis:'exchange-reported-usdt',feeRate:0,entrySlippageAmount:0,exitSlippageAmount:0,totalSlippageAmount:0,slippageBasis:'unavailable',fundingAmount:0,fundingBasis:'unavailable',netPnl:1,returnPct:.01,outcome:'win',closedAtUtc,strategyId:'trend-alpha',strategyVersion:'v1',attributionBasis:'automatic-artifact',traceState:'available',riskDecision:'Approved',executionStatus:'Succeeded',executionCode:'automatic.succeeded',executionAttempts:1,marketCollectedAtUtc:closedAtUtc,marketDataVersion:'market-v1',evidenceState:'partial',evidenceChain:[{stage:'strategy',status:'succeeded',canonicalSha256:'a'.repeat(64),asOfUtc:closedAtUtc,canonicalBytes:'MUST-NOT-ENTER-WEB'}]}],nextCursor:null,sourceUpdatedAtUtc:closedAtUtc,source:'local-agent-sqlite'}}));assert.equal(normalized?.historicalPostTradeReviews?.state,'error');assert.deepEqual(normalized?.historicalPostTradeReviews?.items,[])})

test('reconciliation canonical payload fields are rejected by the bridge',()=>{const at=source.toISOString(),normalized=normalizeRuntimeEvent(snapshot({historicalReconciliations:{state:'Available',items:[{kind:'position',traceId:'reconciliation#ABCDEF123456',schema:'wpe.position-reconciliation/1.0',observedAtUtc:at,evaluatedAtUtc:at,state:'Confirmed',allowsRiskIncrease:true,canonicalSha256:'a'.repeat(64),canonicalBytes:'MUST-NOT-ENTER-WEB'}],nextCursor:null,sourceUpdatedAtUtc:at,source:'local-agent-sqlite'}}));assert.equal(normalized?.historicalReconciliations?.state,'error');assert.deepEqual(normalized?.historicalReconciliations?.items,[])})

test('historical execution ledger accepts masked identities and rejects raw ids',()=>{const at=source.toISOString(),good=normalizeRuntimeEvent(snapshot({historicalOrders:{state:'Available',items:[{sequence:1,occurredAtUtc:at,correlationId:'cycle#ABCDEF123456',clientOrderId:'order#ABCDEF123456',symbol:'BTCUSDT',side:'Long',action:'OPEN',reduceOnly:false,quantity:1,averagePrice:100,status:'FILLED'}],nextCursor:null,sourceUpdatedAtUtc:at,source:'local-agent-sqlite'}}));assert.equal(good?.historicalOrders?.state,'available');assert.equal(good?.historicalOrders?.items[0]?.correlationId,'cycle#ABCDEF123456');const bad=normalizeRuntimeEvent(snapshot({historicalOrders:{state:'Available',items:[{sequence:1,occurredAtUtc:at,correlationId:'cycle-secret',clientOrderId:'order-secret',symbol:'BTCUSDT',side:'Long',action:'OPEN',reduceOnly:false,quantity:1,averagePrice:100,status:'FILLED'}],nextCursor:null,sourceUpdatedAtUtc:at,source:'local-agent-sqlite'}}));assert.equal(bad?.historicalOrders?.state,'error');assert.deepEqual(bad?.historicalOrders?.items,[])})
