using System.Diagnostics;
using System.IO;
using System.Text.Json;
using System.Net.Http;
using System.Text;
using 币安量化机器人.Services.Agent;

namespace 币安量化机器人.Services.Exchange;

public sealed record ExchangeAdapterTestResult(bool Success,string ReportPath);
public sealed record ExchangeAdapterTestCase(string Name,string Status,long DurationMs,string Detail);
public sealed class ExchangeAdapterTestReport{public bool Success{get;set;}public DateTime CompletedAtUtc{get;set;}public List<ExchangeAdapterTestCase> Cases{get;}=[];}

public static class ExchangeAdapterTestRunner
{
    public static async Task<ExchangeAdapterTestResult> RunAsync(CancellationToken ct=default)
    {
        var report=new ExchangeAdapterTestReport();var dir=Path.Combine(AppDataPaths.TestArtifactsDirectory,"exchange-adapter-tests");Directory.CreateDirectory(dir);var path=Path.Combine(dir,$"exchange-adapters-{DateTime.UtcNow:yyyyMMdd-HHmmss}.json");
        try
        {
            await Test(report,"Symbol Mapping",()=>{Require(new ConventionSymbolMapper("okx").ToNative("BTCUSDT")=="BTC-USDT-SWAP","OKX mapping failed");Require(new ConventionSymbolMapper("bybit").ToNative("BTC-USDT")=="BTCUSDT","Bybit mapping failed");Require(new ConventionSymbolMapper("gate").ToNative("BTCUSDT")=="BTC_USDT","Gate mapping failed");Require(new ConventionSymbolMapper("kraken").ToCanonical("XBTUSDT")=="BTCUSDT","XBT mapping failed");var custom=new ConventionSymbolMapper("custom",new Dictionary<string,string>{{"BTCUSDT","BTCUSDTPERP"}});Require(custom.ToCanonical("BTCUSDTPERP")=="BTCUSDT","custom reverse mapping failed");return Task.FromResult("OKX, Bybit, Gate, Kraken/XBT and explicit mappings passed");});
            await Test(report,"Provider auto-discovery and planned catalog",()=>{var catalog=new ExchangeProviderCatalog();foreach(var id in new[]{"binance-futures","okx","okx-mcp","bybit","bitget","gate"})Require(catalog.IsInstalled(id),$"{id} plugin was not auto-discovered");Require(catalog.All.Any(x=>x.Id=="hyperliquid"&&x.AssetClass==ExchangeAssetClass.CryptoDex),"DEX provider reservation missing");Require(catalog.All.GroupBy(x=>x.Id,StringComparer.OrdinalIgnoreCase).All(x=>x.Count()==1),"provider catalog contains duplicate IDs");return Task.FromResult($"installed={catalog.Installed.Count}, discoverable={catalog.All.Count}");});
            await Test(report,"Multi-instance factory",async()=>{var catalog=new ExchangeProviderCatalog();var profile1=Profile("one");var profile2=Profile("two");await using var one=catalog.Create(profile1,Credentials());await using var two=catalog.Create(profile2,Credentials());Require(!ReferenceEquals(one,two),"provider factory returned a singleton");Require(one.ConnectionId!=two.ConnectionId,"connection identity was shared");return $"instances={one.ConnectionId},{two.ConnectionId}";});
            await Test(report,"Unified broker and market contract",async()=>{await using var fake=new FakeProvider();var account=await fake.GetAccountAsync(ct);var market=await fake.GetMarketAsync("BTCUSDT",ct);var order=await fake.PlaceMarketAsync("BTCUSDT",PositionSide.Long,.01m,"wpe-contract-1",false,ct);var found=await fake.FindOrderAsync("BTCUSDT","wpe-contract-1",ct);await fake.CancelOrderAsync("BTCUSDT",order.OrderId,ct);Require(account.AvailableBalance==900&&market.Symbol=="BTCUSDT"&&found?.ClientOrderId=="wpe-contract-1"&&fake.Cancelled,"contract lifecycle failed");return "balance, market, order, query and cancel passed through one interface";});
            await Test(report,"Retry policy",async()=>{var attempts=0;var policy=new ProviderCallPolicy(2,2);var result=await policy.ExecuteAsync<int>(_=>{attempts++;if(attempts<3)throw new HttpRequestException("transient");return Task.FromResult(42);},ct);Require(result==42&&attempts==3,"retry count is incorrect");return $"attempts={attempts}";});
            await Test(report,"Timeout policy",async()=>{var policy=new ProviderCallPolicy(1,0);var timedOut=false;try{await policy.ExecuteAsync<int>(async token=>{await Task.Delay(TimeSpan.FromSeconds(5),token);return 1;},ct);}catch(TaskCanceledException){timedOut=true;}Require(timedOut,"provider timeout was not enforced");return "timeout cancellation enforced";});
            await Test(report,"Private API signature vectors",()=>{var secret=Encoding.UTF8.GetBytes("test-secret");Require(BybitExchangeProvider.ComputeSignature(secret,"1700000000000","test-key",5000,"category=linear&symbol=BTCUSDT")=="9a7c8cfd6ba1a7c498aa4dd5a7f9cfbba01fcb6eebae734ffe0d775870a1a3fb","Bybit signature mismatch");Require(OkxExchangeProvider.ComputeSignature(secret,"2026-07-19T15:00:00.000Z","GET","/api/v5/account/config","")=="lWrfHGBeGs6r85WSUF27vHYZsGr7CKryWUYLN7U4YR0=","OKX signature mismatch");Require(BitgetExchangeProvider.ComputeSignature(secret,"1700000000000","POST","/api/v2/mix/order/place-order","{\"symbol\":\"BTCUSDT\"}")=="pNlgyERIDOtF30Q+OD8oSpMpXbtTTX0hM0kU8bW+UdA=","Bitget signature mismatch");Require(GateExchangeProvider.ComputeSignature(secret,"POST","/api/v4/futures/usdt/orders","","{\"contract\":\"BTC_USDT\",\"size\":\"1\"}","1700000000")=="16bef696a1406d0bafab07b6fd30a634729df43b459a7ebc81053ddf1c13f0a881494a414e9205997398209644ba8f4eec3ebecddef2b35bde9818af9c89ca9a","Gate signature mismatch");return Task.FromResult("Bybit, OKX, Bitget and Gate signature vectors passed");});
            await Test(report,"Provider client order IDs",()=>{var one=OkxExchangeProvider.ClientId("WPE-SMOKE-OPEN-1234567890-very-long-id");var two=OkxExchangeProvider.ClientId("WPE-SMOKE-OPEN-1234567890-very-long-id");Require(one.Length==32&&one.All(char.IsLetterOrDigit)&&one==two,"OKX client order ID is not deterministic or valid");return Task.FromResult($"OKX id={one}, length={one.Length}");});
            report.Success=true;
        }
        catch(Exception ex){report.Cases.Add(new("Test run","FAILED",0,ex.Message));report.Success=false;}
        report.CompletedAtUtc=DateTime.UtcNow;await global::币安量化机器人.Services.SensitiveDataRedactor.WriteRedactedJsonAsync(path,report,CancellationToken.None);return new(report.Success,path);
    }
    private static ExchangeConnectionProfile Profile(string id)=>new(){Id=id,ProviderId="binance-futures",DisplayName=id,IsTestnet=true,Endpoint="https://testnet.binancefuture.com"};
    private static IReadOnlyDictionary<string,string> Credentials()=>new Dictionary<string,string>{{"apiKey","test-api-key"},{"secret","test-secret"}};
    private static async Task Test(ExchangeAdapterTestReport report,string name,Func<Task<string>> body){var sw=Stopwatch.StartNew();try{report.Cases.Add(new(name,"PASSED",sw.ElapsedMilliseconds,await body()));}catch(Exception ex){report.Cases.Add(new(name,"FAILED",sw.ElapsedMilliseconds,ex.Message));throw;}}
    private static void Require(bool value,string message){if(!value)throw new InvalidOperationException(message);}

    private sealed class FakeProvider:IExchangeProvider,IMarketDataProvider,IBrokerProvider
    {
        private ExchangeOrder? _order;public bool Cancelled{get;private set;}public ExchangeEnvironment Environment=>ExchangeEnvironment.Testnet;public string ConnectionId=>"fake-1";public string ProviderId=>"fake";public ExchangeProviderDescriptor Descriptor=>new("fake","Fake",ExchangeAssetClass.CryptoCex,true,false,[],new HashSet<string>());public ISymbolMapper Symbols{get;}=new ConventionSymbolMapper("fake");public IMarketDataProvider MarketData=>this;public IBrokerProvider Broker=>this;
        public Task<bool> PingAsync(CancellationToken ct)=>Task.FromResult(true);public Task<DateTime> GetServerTimeAsync(CancellationToken ct)=>Task.FromResult(DateTime.UtcNow);public Task<ExchangePermissionSnapshot> CheckPermissionsAsync(CancellationToken ct)=>Task.FromResult(new ExchangePermissionSnapshot(true,true,false,"fake",[]));public Task<ExchangeHealthSnapshot> HealthCheckAsync(CancellationToken ct)=>Task.FromResult(new ExchangeHealthSnapshot(true,1,0,"ok",DateTime.UtcNow));public IRealtimeMarketFeed? CreateRealtimeFeed(IEnumerable<string> symbols,AgentSqliteStore db)=>null;
        public Task<AccountSnapshot> GetAccountAsync(CancellationToken ct)=>Task.FromResult(new AccountSnapshot(1000,900,1000,DateTime.UtcNow));public Task<MarginSnapshot> GetMarginAsync(CancellationToken ct)=>Task.FromResult(new MarginSnapshot(1000,900,100,0,.1m));public Task<IReadOnlyList<ManagedPosition>> GetPositionsAsync(CancellationToken ct)=>Task.FromResult<IReadOnlyList<ManagedPosition>>([]);public Task<IReadOnlyList<ExchangeOrder>> GetOpenOrdersAsync(string? symbol,CancellationToken ct)=>Task.FromResult<IReadOnlyList<ExchangeOrder>>(_order is null||Cancelled?[]:[_order]);public Task<TradingRule> GetRulesAsync(string symbol,CancellationToken ct)=>Task.FromResult(new TradingRule(symbol,.001m,.1m,.001m,5,20));public Task<MarketEvidence> GetMarketAsync(string symbol,CancellationToken ct)=>Task.FromResult(new MarketEvidence(symbol,100000,98000,102000,55,.1,.2,.3,new(0,100,1,1,1,1,0),DateTime.UtcNow));public Task<IReadOnlyList<DerivativesSnapshot>> GetDerivativeHistoryAsync(string symbol,CancellationToken ct)=>Task.FromResult<IReadOnlyList<DerivativesSnapshot>>([]);public Task<IReadOnlyList<CandleEvidence>> GetCandlesAsync(string symbol,string interval,int limit,CancellationToken ct)=>Task.FromResult<IReadOnlyList<CandleEvidence>>([]);public Task<IReadOnlyList<CandleEvidence>> GetCandlesRangeAsync(string symbol,string interval,DateTime start,DateTime end,int limit,CancellationToken ct)=>Task.FromResult<IReadOnlyList<CandleEvidence>>([]);public Task SetLeverageAsync(string symbol,int leverage,CancellationToken ct)=>Task.CompletedTask;public Task SetMarginModeAsync(string symbol,bool isolated,CancellationToken ct)=>Task.CompletedTask;public Task SetHedgeModeAsync(bool enabled,CancellationToken ct)=>Task.CompletedTask;
        public Task<ExchangeOrder> PlaceMarketAsync(string symbol,PositionSide side,decimal quantity,string clientOrderId,bool reduceOnly,CancellationToken ct){_order=new(symbol,"provider-order-7",clientOrderId,"NEW",0,0,"MARKET",side,false,DateTime.UtcNow);return Task.FromResult(_order);}public Task<ExchangeOrder> PlaceLimitAsync(string symbol,PositionSide side,decimal quantity,decimal price,string clientOrderId,bool reduceOnly,CancellationToken ct)=>PlaceMarketAsync(symbol,side,quantity,clientOrderId,reduceOnly,ct);public Task<ExchangeOrder> PlaceProtectionAsync(string symbol,PositionSide sideToClose,decimal stopLoss,decimal takeProfit,string groupId,CancellationToken ct)=>PlaceMarketAsync(symbol,sideToClose,0,groupId,false,ct);public Task<ExchangeOrder?> FindOrderAsync(string symbol,string clientOrderId,CancellationToken ct)=>Task.FromResult(_order?.ClientOrderId==clientOrderId?_order:null);public Task CancelOrderAsync(string symbol,string orderId,CancellationToken ct){Cancelled=true;return Task.CompletedTask;}public ValueTask DisposeAsync()=>ValueTask.CompletedTask;
    }
}
