using System.Collections.Concurrent;
using System.Globalization;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using 币安量化机器人.Services.Agent;

namespace 币安量化机器人.Services.Exchange;

public sealed class GateProviderPlugin:IExchangeProviderPlugin
{
    public static ExchangeProviderDescriptor ProviderDescriptor{get;}=new("gate","Gate.io",ExchangeAssetClass.CryptoCex,true,true,[new("apiKey","API Key",ExchangeCredentialKind.ApiKey),new("secret","API Secret",ExchangeCredentialKind.Secret)],new HashSet<string>(["account","balance","positions","margin","candles","funding","open-interest","index-price","mark-price","place-order","cancel-order","query-order","protection-orders","health"]));
    public ExchangeProviderDescriptor Descriptor=>ProviderDescriptor;
    public IExchangeProvider Create(ExchangeConnectionProfile profile,IReadOnlyDictionary<string,string> credentials)=>new GateExchangeProvider(profile,Required(credentials,"apiKey"),Required(credentials,"secret"));
    private static string Required(IReadOnlyDictionary<string,string> values,string key)=>values.TryGetValue(key,out var value)&&!string.IsNullOrWhiteSpace(value)?value:throw new InvalidOperationException($"Gate credential '{key}' is incomplete.");
}

public sealed class GateExchangeProvider:RestExchangeProviderBase
{
    private readonly string _key,_apiPrefix;private readonly byte[] _secret;private readonly ConcurrentDictionary<string,decimal> _multipliers=new(StringComparer.OrdinalIgnoreCase);private readonly ConcurrentDictionary<string,byte> _protectionIds=new();private readonly Dictionary<string,int> _leverages=new(StringComparer.OrdinalIgnoreCase);private readonly Dictionary<string,bool> _isolated=new(StringComparer.OrdinalIgnoreCase);
    public override string ProviderId=>"gate";public override ExchangeProviderDescriptor Descriptor=>GateProviderPlugin.ProviderDescriptor;
    public GateExchangeProvider(ExchangeConnectionProfile profile,string key,string secret):base(NormalizeProfile(profile)){_key=key;_secret=Encoding.UTF8.GetBytes(secret);_apiPrefix="/api/v4";}
    public override async Task<DateTime> GetServerTimeAsync(CancellationToken ct){using var d=await Public(HttpMethod.Get,"/spot/time",null,ct);return Millis(Str(d.RootElement,"server_time"));}
    public override async Task<ExchangePermissionSnapshot> CheckPermissionsAsync(CancellationToken ct){_ =await GetAccountAsync(ct);return new(true,true,false,"Gate Futures",["Gate APIv4 does not return the complete key permission matrix on the futures account endpoint; trading permission is verified by a Testnet order lifecycle."]);}
    public override async Task<AccountSnapshot> GetAccountAsync(CancellationToken ct){using var d=await Private(HttpMethod.Get,"/futures/usdt/accounts",null,null,ct);var x=d.RootElement;return new(Dec(x,"total"),Dec(x,"available"),Dec(x,"total"),DateTime.UtcNow);}
    public override async Task<IReadOnlyList<ManagedPosition>> GetPositionsAsync(CancellationToken ct)
    {
        using var d=await Private(HttpMethod.Get,"/futures/usdt/positions",null,null,ct);var result=new List<ManagedPosition>();foreach(var x in d.RootElement.EnumerateArray()){var size=Dec(x,"size");if(size==0)continue;var native=Str(x,"contract");var multiplier=await Multiplier(native,ct);var mode=Str(x,"mode");var side=mode=="dual_short"||size<0?PositionSide.Short:PositionSide.Long;var leverage=Dec(x,"lever");if(leverage<=0)leverage=Dec(x,"leverage");if(leverage<=0)leverage=Dec(x,"cross_leverage_limit");result.Add(new(Symbols.ToCanonical(native),side,Math.Abs(size)*multiplier,Dec(x,"entry_price"),Dec(x,"mark_price"),Dec(x,"unrealised_pnl"),leverage,Str(x,"pos_margin_mode")!="cross"&&Dec(x,"leverage")>0,Dec(x,"liq_price")));}return result;
    }
    public override async Task<IReadOnlyList<ExchangeOrder>> GetOpenOrdersAsync(string? symbol,CancellationToken ct)
    {
        var native=string.IsNullOrWhiteSpace(symbol)?null:Symbols.ToNative(symbol);var q=new Dictionary<string,string?>{{"status","open"},{"contract",native}};using var d=await Private(HttpMethod.Get,"/futures/usdt/orders",q,null,ct);var result=new List<ExchangeOrder>();foreach(var x in d.RootElement.EnumerateArray())result.Add(await MapOrder(x,false,ct));
        try{using var plans=await Private(HttpMethod.Get,"/futures/usdt/price_orders",new Dictionary<string,string?>{{"status","open"},{"contract",native}},null,ct);foreach(var x in plans.RootElement.EnumerateArray())result.Add(await MapProtection(x,ct));}catch{/* Regular order state must remain available if the optional trigger list is unavailable. */}
        return result;
    }
    public override async Task<TradingRule> GetRulesAsync(string symbol,CancellationToken ct)
    {
        var canonical=Symbols.ToCanonical(symbol);using var d=await Public(HttpMethod.Get,$"/futures/usdt/contracts/{Symbols.ToNative(canonical)}",null,ct);var x=d.RootElement;var multiplier=Dec(x,"quanto_multiplier");_multipliers[Symbols.ToNative(canonical)]=multiplier;return new(canonical,multiplier,Dec(x,"order_price_round"),Dec(x,"order_size_min")*multiplier,Math.Max(1,Dec(x,"order_size_min")*multiplier*Dec(x,"mark_price")),(int)Math.Max(1,Dec(x,"leverage_max")));
    }
    public override Task<IReadOnlyList<CandleEvidence>> GetCandlesAsync(string symbol,string interval,int limit,CancellationToken ct)=>Candles(symbol,interval,limit,null,null,ct);
    public override Task<IReadOnlyList<CandleEvidence>> GetCandlesRangeAsync(string symbol,string interval,DateTime start,DateTime end,int limit,CancellationToken ct)=>Candles(symbol,interval,limit,new DateTimeOffset(start.ToUniversalTime()).ToUnixTimeSeconds(),new DateTimeOffset(end.ToUniversalTime()).ToUnixTimeSeconds(),ct);
    protected override async Task<DerivativesSnapshot> GetDerivativesAsync(string symbol,CancellationToken ct){using var d=await Public(HttpMethod.Get,"/futures/usdt/tickers",new Dictionary<string,string?>{{"contract",Symbols.ToNative(symbol)}},ct);var data=d.RootElement;if(data.GetArrayLength()==0)return new(0,0,0,0,0,0,0);var x=data[0];var multiplier=Dec(x,"quanto_multiplier");var index=Dec(x,"index_price");var mark=Dec(x,"mark_price");return new(Dec(x,"funding_rate"),Dec(x,"total_size")*multiplier,0,0,0,0,index>0?(mark-index)/index:0);}
    public override async Task SetLeverageAsync(string symbol,int leverage,CancellationToken ct){var canonical=Symbols.ToCanonical(symbol);_leverages[canonical]=leverage;var isolated=_isolated.GetValueOrDefault(canonical,true);var q=new Dictionary<string,string?>{{"leverage",isolated?leverage.ToString():"0"},{"cross_leverage_limit",isolated?null:leverage.ToString()}};using var _=await Private(HttpMethod.Post,$"/futures/usdt/positions/{Symbols.ToNative(canonical)}/leverage",q,null,ct);}
    public override async Task SetMarginModeAsync(string symbol,bool isolated,CancellationToken ct){var canonical=Symbols.ToCanonical(symbol);_isolated[canonical]=isolated;if(_leverages.TryGetValue(canonical,out var leverage))await SetLeverageAsync(canonical,leverage,ct);}
    public override async Task SetHedgeModeAsync(bool enabled,CancellationToken ct){var q=new Dictionary<string,string?>{{"position_mode",enabled?"dual_plus":"single"}};try{using var _=await Private(HttpMethod.Post,"/futures/usdt/set_position_mode",q,null,ct);}catch(InvalidOperationException ex)when(ex.Message.Contains("same",StringComparison.OrdinalIgnoreCase)||ex.Message.Contains("NO_CHANGE",StringComparison.OrdinalIgnoreCase)){} }
    public override Task<ExchangeOrder> PlaceMarketAsync(string symbol,PositionSide side,decimal quantity,string clientOrderId,bool reduceOnly,CancellationToken ct)=>Place(symbol,side,quantity,0,clientOrderId,reduceOnly,ct);
    public override Task<ExchangeOrder> PlaceLimitAsync(string symbol,PositionSide side,decimal quantity,decimal price,string clientOrderId,bool reduceOnly,CancellationToken ct)=>Place(symbol,side,quantity,price,clientOrderId,reduceOnly,ct);
    public override async Task<ExchangeOrder> PlaceProtectionAsync(string symbol,PositionSide sideToClose,decimal stopLoss,decimal takeProfit,string groupId,CancellationToken ct)
    {
        var canonical=Symbols.ToCanonical(symbol);var isolated=_isolated.GetValueOrDefault(canonical,true);var tp=await PlaceTrigger(canonical,sideToClose,takeProfit,sideToClose==PositionSide.Long?1:2,groupId+"-tp",isolated,ct);try{_ =await PlaceTrigger(canonical,sideToClose,stopLoss,sideToClose==PositionSide.Long?2:1,groupId+"-sl",isolated,ct);}catch{await CancelOrderAsync(canonical,tp.OrderId,ct);throw;}return tp;
    }
    public override async Task<ExchangeOrder?> FindOrderAsync(string symbol,string clientOrderId,CancellationToken ct){var text=ClientText(clientOrderId);try{using var d=await Private(HttpMethod.Get,$"/futures/usdt/orders/{text}",null,null,ct);var mapped=await MapOrder(d.RootElement,false,ct);return mapped with{ClientOrderId=clientOrderId};}catch(InvalidOperationException ex)when(ex.Message.Contains("ORDER_NOT_FOUND",StringComparison.OrdinalIgnoreCase)){return null;}}
    public override async Task CancelOrderAsync(string symbol,string orderId,CancellationToken ct){var protection=_protectionIds.TryRemove(orderId,out _);using var response=await Private(HttpMethod.Delete,protection?$"/futures/usdt/price_orders/{orderId}":$"/futures/usdt/orders/{orderId}",null,null,ct);}

    private async Task<IReadOnlyList<CandleEvidence>> Candles(string symbol,string interval,int limit,long? from,long? to,CancellationToken ct){var q=new Dictionary<string,string?>{{"contract",Symbols.ToNative(symbol)},{"interval",interval},{"limit",Math.Clamp(limit,1,2000).ToString()},{"from",from?.ToString()},{"to",to?.ToString()}};using var d=await Public(HttpMethod.Get,"/futures/usdt/candlesticks",q,ct);var multiplier=await Multiplier(Symbols.ToNative(symbol),ct);return d.RootElement.EnumerateArray().Select(x=>new CandleEvidence(DateTimeOffset.FromUnixTimeSeconds((long)Dec(x,"t")).UtcDateTime,Dec(x,"o"),Dec(x,"h"),Dec(x,"l"),Dec(x,"c"),Dec(x,"v")*multiplier,Dec(x,"sum"),0,0)).OrderBy(x=>x.OpenTime).ToArray();}
    private async Task<ExchangeOrder> Place(string symbol,PositionSide side,decimal quantity,decimal price,string clientOrderId,bool reduceOnly,CancellationToken ct){var canonical=Symbols.ToCanonical(symbol);var native=Symbols.ToNative(canonical);var multiplier=await Multiplier(native,ct);var contracts=Math.Max(1,Math.Floor(quantity/multiplier));var direction=side==PositionSide.Long?1m:-1m;if(reduceOnly)direction=-direction;var body=new Dictionary<string,object?>{{"contract",native},{"size",F(contracts*direction)},{"price",price>0?F(price):"0"},{"tif",price>0?"gtc":"ioc"},{"text",ClientText(clientOrderId)},{"reduce_only",reduceOnly},{"is_dual_mode",true},{"pos_margin_mode",_isolated.GetValueOrDefault(canonical,true)?"isolated":"cross"}};using var d=await Private(HttpMethod.Post,"/futures/usdt/orders",null,body,ct);var mapped=await MapOrder(d.RootElement,false,ct);return mapped with{ClientOrderId=clientOrderId,PositionSide=side};}
    private async Task<ExchangeOrder> PlaceTrigger(string symbol,PositionSide side,decimal price,int rule,string clientId,bool isolated,CancellationToken ct){var orderType=side==PositionSide.Long?"close-long-order":"close-short-order";var body=new Dictionary<string,object?>{{"initial",new Dictionary<string,object?>{{"contract",Symbols.ToNative(symbol)},{"size","0"},{"price","0"},{"text",ClientText(clientId)},{"reduce_only",true}}},{"trigger",new Dictionary<string,object?>{{"strategy_type",0},{"price_type",1},{"price",F(price)},{"rule",rule},{"expiration",86400*30}}},{"order_type",orderType},{"pos_margin_mode",isolated?"isolated":"cross"}};using var d=await Private(HttpMethod.Post,"/futures/usdt/price_orders",null,body,ct);var id=Str(d.RootElement,"id_string");if(id.Length==0)id=Str(d.RootElement,"id");_protectionIds[id]=0;return new(symbol,id,clientId,"NEW",0,0,"TRIGGER",side,true,DateTime.UtcNow);}
    private async Task<ExchangeOrder> MapOrder(JsonElement x,bool protection,CancellationToken ct){var native=Str(x,"contract");var multiplier=await Multiplier(native,ct);var size=Dec(x,"size");var left=Dec(x,"left");var side=size<0?PositionSide.Short:PositionSide.Long;var status=Str(x,"status") switch{"open"=>left<Math.Abs(size)?"PARTIALLY_FILLED":"NEW","finished"=>Str(x,"finish_as") switch{"filled"=>"FILLED","cancelled"=>"CANCELED","rejected"=>"REJECTED",_=>"FILLED"},var s=>s.ToUpperInvariant()};var id=Str(x,"id_string");if(id.Length==0)id=Str(x,"id");return new(Symbols.ToCanonical(native),id,Str(x,"text"),status,(Math.Abs(size)-Math.Abs(left))*multiplier,Dec(x,"fill_price")>0?Dec(x,"fill_price"):Dec(x,"price"),protection?"TRIGGER":Dec(x,"price")==0?"MARKET":"LIMIT",side,protection,Seconds(Str(x,"update_time") is {Length:>0}t?t:Str(x,"create_time")));}
    private async Task<ExchangeOrder> MapProtection(JsonElement x,CancellationToken ct){var initial=x.GetProperty("initial");var native=Str(initial,"contract");_ =await Multiplier(native,ct);var id=Str(x,"id_string");if(id.Length==0)id=Str(x,"id");_protectionIds[id]=0;var side=Str(x,"order_type").Contains("short",StringComparison.OrdinalIgnoreCase)?PositionSide.Short:PositionSide.Long;return new(Symbols.ToCanonical(native),id,Str(initial,"text"),Str(x,"status")=="open"?"NEW":Str(x,"status").ToUpperInvariant(),0,0,"TRIGGER",side,true,Seconds(Str(x,"create_time")));}
    private async Task<decimal> Multiplier(string native,CancellationToken ct){if(_multipliers.TryGetValue(native,out var value)&&value>0)return value;using var d=await Public(HttpMethod.Get,$"/futures/usdt/contracts/{native}",null,ct);value=Dec(d.RootElement,"quanto_multiplier");if(value<=0)throw new InvalidOperationException($"Gate contract multiplier is invalid for {native}");_multipliers[native]=value;return value;}
    private async Task<JsonDocument> Public(HttpMethod method,string path,IReadOnlyDictionary<string,string?>? query,CancellationToken ct){var q=query is null?"":Query(query);var apiPath=_apiPrefix+path;var target=q.Length==0?apiPath:$"{apiPath}?{q}";return await SendAsync(()=>JsonRequest(method,target),Error,ct);}
    private async Task<JsonDocument> Private(HttpMethod method,string path,IReadOnlyDictionary<string,string?>? query,object? body,CancellationToken ct){var q=query is null?"":Query(query);var apiPath=_apiPrefix+path;var target=q.Length==0?apiPath:$"{apiPath}?{q}";var json=body is null?"":JsonSerializer.Serialize(body);return await SendAsync(()=>{var timestamp=DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString();var signature=ComputeSignature(_secret,method.Method,apiPath,q,json,timestamp);var request=JsonRequest(method,target,json.Length==0?null:json);request.Headers.Add("KEY",_key);request.Headers.Add("Timestamp",timestamp);request.Headers.Add("SIGN",signature);request.Headers.Add("X-Gate-Size-Decimal","1");return request;},Error,ct);}
    private static string? Error(JsonElement root)=>root.ValueKind==JsonValueKind.Object&&root.TryGetProperty("label",out var label)?$"{label.GetString()} {Str(root,"message")}":null;
    private static string ClientText(string value)=>"t-"+Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant()[..24];
    private static DateTime Seconds(string value)=>long.TryParse(value.Split('.')[0],out var seconds)&&seconds>0?DateTimeOffset.FromUnixTimeSeconds(seconds).UtcDateTime:DateTime.UtcNow;
    private static ExchangeConnectionProfile NormalizeProfile(ExchangeConnectionProfile profile){profile.Endpoint=profile.Endpoint.TrimEnd('/');if(profile.Endpoint.EndsWith("/api/v4",StringComparison.OrdinalIgnoreCase))profile.Endpoint=profile.Endpoint[..^7];return profile;}
    internal static string ComputeSignature(byte[] secret,string method,string apiPath,string query,string body,string timestamp){var bodyHash=Convert.ToHexString(SHA512.HashData(Encoding.UTF8.GetBytes(body))).ToLowerInvariant();var signText=$"{method.ToUpperInvariant()}\n{apiPath}\n{query}\n{bodyHash}\n{timestamp}";return Convert.ToHexString(HMACSHA512.HashData(secret,Encoding.UTF8.GetBytes(signText))).ToLowerInvariant();}
}
