using System.Collections.Concurrent;
using System.Globalization;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using 币安量化机器人.Services.Agent;

namespace 币安量化机器人.Services.Exchange;

public sealed class GateProviderPlugin:IExchangeProviderPlugin
{
    public static ExchangeProviderDescriptor ProviderDescriptor{get;}=new("gate","Gate.io",ExchangeAssetClass.CryptoCex,true,false,[new("apiKey","API Key",ExchangeCredentialKind.ApiKey),new("secret","API Secret",ExchangeCredentialKind.Secret)],new HashSet<string>(["account","balance","positions","margin","candles","funding","open-interest","index-price","mark-price","place-order","cancel-order","query-order","protection-orders","health"]));
    public ExchangeProviderDescriptor Descriptor=>ProviderDescriptor;
    public IExchangeProvider Create(ExchangeConnectionProfile profile,IReadOnlyDictionary<string,string> credentials)=>new GateExchangeProvider(profile,Required(credentials,"apiKey"),Required(credentials,"secret"));
    private static string Required(IReadOnlyDictionary<string,string> values,string key)=>values.TryGetValue(key,out var value)&&!string.IsNullOrWhiteSpace(value)?value:throw new InvalidOperationException($"Gate credential '{key}' is incomplete.");
}

public sealed class GateExchangeProvider:RestExchangeProviderBase,WpeAgent.RuntimeContracts.IProviderMarketCatalog
{
    private readonly string _key,_apiPrefix;private readonly byte[] _secret;private readonly ConcurrentDictionary<string,decimal> _multipliers=new(StringComparer.OrdinalIgnoreCase);private readonly ConcurrentDictionary<string,byte> _protectionIds=new();private readonly Dictionary<string,int> _leverages=new(StringComparer.OrdinalIgnoreCase);private readonly Dictionary<string,bool> _isolated=new(StringComparer.OrdinalIgnoreCase);
    public override string ProviderId=>"gate";public override ExchangeProviderDescriptor Descriptor=>GateProviderPlugin.ProviderDescriptor;
    public GateExchangeProvider(ExchangeConnectionProfile profile,string key,string secret):base(NormalizeProfile(profile)){_key=key;_secret=Encoding.UTF8.GetBytes(secret);_apiPrefix="/api/v4";}
    public override ProviderEnvironmentValidation ValidateEnvironment(bool requireTestnet)
    {
        if(!requireTestnet||Environment!=ExchangeEnvironment.Testnet)return new(false,false,false,"Gate Mainnet execution is not enabled.");
        if(!IsOfficialTestnetEndpoint(Profile.Endpoint))return new(false,false,false,"Gate Testnet requires the official https://api-testnet.gateapi.io endpoint.");
        return new(true,Profile.ExecutionEnabled,true,Profile.ExecutionEnabled?null:"Execution is disabled for this connection.");
    }
    public override async Task<DateTime> GetServerTimeAsync(CancellationToken ct){using var d=await Public(HttpMethod.Get,"/spot/time",null,ct);return Millis(Str(d.RootElement,"server_time"));}
    public override async Task<ExchangePermissionSnapshot> CheckPermissionsAsync(CancellationToken ct){_ =await GetAccountAsync(ct);return ConservativePermissionSnapshot();}
    internal static ExchangePermissionSnapshot ConservativePermissionSnapshot()=>new(true,false,false,"Gate Futures",["Gate APIv4 does not expose complete key trade permissions; trading remains disabled until a credentialed Testnet lifecycle is verified."]);
    public override async Task<AccountSnapshot> GetAccountAsync(CancellationToken ct){using var d=await Private(HttpMethod.Get,"/futures/usdt/accounts",null,null,ct);return ParseAccountSnapshot(d.RootElement,DateTime.UtcNow);}
    public override async Task<IReadOnlyList<ManagedPosition>> GetPositionsAsync(CancellationToken ct)
    {
        using var d=await Private(HttpMethod.Get,"/futures/usdt/positions",null,null,ct);var result=new List<ManagedPosition>();foreach(var x in d.RootElement.EnumerateArray()){var size=Dec(x,"size");if(size==0)continue;var native=Str(x,"contract");var multiplier=await Multiplier(native,ct);var mode=Str(x,"mode");var side=mode=="dual_short"||size<0?PositionSide.Short:PositionSide.Long;var leverage=Dec(x,"lever");if(leverage<=0)leverage=Dec(x,"leverage");if(leverage<=0)leverage=Dec(x,"cross_leverage_limit");result.Add(new(Symbols.ToCanonical(native),side,Math.Abs(size)*multiplier,Dec(x,"entry_price"),Dec(x,"mark_price"),Dec(x,"unrealised_pnl"),leverage,Str(x,"pos_margin_mode")!="cross"&&Dec(x,"leverage")>0,Dec(x,"liq_price")));}return result;
    }
    public override async Task<IReadOnlyList<ExchangeOrder>> GetOpenOrdersAsync(string? symbol,CancellationToken ct)
    {
        var native=string.IsNullOrWhiteSpace(symbol)?null:Symbols.ToNative(symbol);var q=new Dictionary<string,string?>{{"status","open"},{"contract",native},{"limit","100"}};using var d=await Private(HttpMethod.Get,"/futures/usdt/orders",q,null,ct);var regular=new List<ExchangeOrder>();foreach(var x in d.RootElement.EnumerateArray())regular.Add(await MapOrder(x,false,ct));
        using var plans=await Private(HttpMethod.Get,"/futures/usdt/price_orders",new Dictionary<string,string?>{{"status","open"},{"contract",native},{"limit","100"}},null,ct);var protection=new List<ExchangeOrder>();foreach(var x in plans.RootElement.EnumerateArray())protection.Add(await MapProtection(x,ct));
        return MergeOrderPages([regular,protection]);
    }
    public override async Task<TradingRule> GetRulesAsync(string symbol,CancellationToken ct)
    {
        var canonical=Symbols.ToCanonical(symbol);using var d=await Public(HttpMethod.Get,$"/futures/usdt/contracts/{Symbols.ToNative(canonical)}",null,ct);var x=d.RootElement;var multiplier=Dec(x,"quanto_multiplier");_multipliers[Symbols.ToNative(canonical)]=multiplier;return new(canonical,multiplier,Dec(x,"order_price_round"),Dec(x,"order_size_min")*multiplier,Math.Max(1,Dec(x,"order_size_min")*multiplier*Dec(x,"mark_price")),(int)Math.Max(1,Dec(x,"leverage_max")));
    }
    public async Task<WpeAgent.RuntimeContracts.ProviderMarketCatalog> DiscoverMarketCatalogAsync(CancellationToken ct)
    {
        var checkedAt=DateTimeOffset.UtcNow;
        if(Profile.IsTestnet&&(!Descriptor.SupportsTestnet||!IsOfficialTestnetEndpoint(Profile.Endpoint)))
            return new(WpeAgent.RuntimeContracts.ProviderCatalogState.Unsupported,Array.Empty<WpeAgent.RuntimeContracts.ProviderMarketCatalogEntry>(),checkedAt,"Gate Testnet catalog requires the official api-testnet.gateapi.io profile endpoint");
        try
        {
            using var document=await Public(HttpMethod.Get,"/futures/usdt/contracts",null,ct);
            var entries=WpeAgent.RuntimeContracts.GateMarketCatalogParser.Parse(document.RootElement,Descriptor.Id,ProviderId,Symbols.ToCanonical,Descriptor.SupportsTestnet,Environment==ExchangeEnvironment.Testnet,checkedAt);
            return new(WpeAgent.RuntimeContracts.ProviderCatalogState.Available,entries,checkedAt);
        }
        catch(Exception ex)
        {
            return new(WpeAgent.RuntimeContracts.ProviderCatalogState.Error,Array.Empty<WpeAgent.RuntimeContracts.ProviderMarketCatalogEntry>(),checkedAt,global::币安量化机器人.Services.SensitiveDataRedactor.ForLog(ex.Message,180));
        }
    }
    public override Task<IReadOnlyList<CandleEvidence>> GetCandlesAsync(string symbol,string interval,int limit,CancellationToken ct)=>Candles(symbol,interval,limit,null,null,ct);
    public override Task<IReadOnlyList<CandleEvidence>> GetCandlesRangeAsync(string symbol,string interval,DateTime start,DateTime end,int limit,CancellationToken ct)=>Candles(symbol,interval,limit,new DateTimeOffset(start.ToUniversalTime()).ToUnixTimeSeconds(),new DateTimeOffset(end.ToUniversalTime()).ToUnixTimeSeconds(),ct);
    protected override async Task<DerivativesSnapshot> GetDerivativesAsync(string symbol,CancellationToken ct){using var d=await Public(HttpMethod.Get,"/futures/usdt/tickers",new Dictionary<string,string?>{{"contract",Symbols.ToNative(symbol)}},ct);var data=d.RootElement;if(data.GetArrayLength()==0)return new(0,0,0,0,0,0,0);var x=data[0];var multiplier=Dec(x,"quanto_multiplier");var index=Dec(x,"index_price");var mark=Dec(x,"mark_price");return new(Dec(x,"funding_rate"),Dec(x,"total_size")*multiplier,0,0,0,0,index>0?(mark-index)/index:0);}
    public override async Task SetLeverageAsync(string symbol,int leverage,CancellationToken ct){var canonical=Symbols.ToCanonical(symbol);_leverages[canonical]=leverage;var isolated=_isolated.GetValueOrDefault(canonical,true);var q=new Dictionary<string,string?>{{"leverage",isolated?leverage.ToString():"0"},{"cross_leverage_limit",isolated?null:leverage.ToString()}};using var _=await Private(HttpMethod.Post,$"/futures/usdt/positions/{Symbols.ToNative(canonical)}/leverage",q,null,ct);}
    public override async Task SetMarginModeAsync(string symbol,bool isolated,CancellationToken ct){var canonical=Symbols.ToCanonical(symbol);_isolated[canonical]=isolated;if(_leverages.TryGetValue(canonical,out var leverage))await SetLeverageAsync(canonical,leverage,ct);}
    public override async Task SetHedgeModeAsync(bool enabled,CancellationToken ct){var q=new Dictionary<string,string?>{{"position_mode",enabled?"dual_plus":"single"}};try{using var _=await Private(HttpMethod.Post,"/futures/usdt/set_position_mode",q,null,ct);}catch(InvalidOperationException ex)when(ex.Message.Contains("same",StringComparison.OrdinalIgnoreCase)||ex.Message.Contains("NO_CHANGE",StringComparison.OrdinalIgnoreCase)){} }
    public override Task<ExchangeOrder> PlaceMarketAsync(string symbol,PositionSide side,decimal quantity,string clientOrderId,bool reduceOnly,CancellationToken ct)=>Place(symbol,side,quantity,0,clientOrderId,reduceOnly,ct);
    public override Task<ExchangeOrder> PlaceLimitAsync(string symbol,PositionSide side,decimal quantity,decimal price,string clientOrderId,bool reduceOnly,CancellationToken ct)=>Place(symbol,side,quantity,price,clientOrderId,reduceOnly,ct);
    public override async Task<ExchangeOrder> PlaceProtectionAsync(string symbol,PositionSide sideToClose,decimal stopLoss,decimal takeProfit,string groupId,CancellationToken ct)
    {
        var canonical=Symbols.ToCanonical(symbol);var isolated=_isolated.GetValueOrDefault(canonical,true);var tp=await PlaceTrigger(canonical,sideToClose,takeProfit,sideToClose==PositionSide.Long?1:2,groupId+"-tp",isolated,ct);try{_ =await PlaceTrigger(canonical,sideToClose,stopLoss,sideToClose==PositionSide.Long?2:1,groupId+"-sl",isolated,ct);}catch{await CancelOrderAsync(canonical,tp.OrderId,ct);throw;}return tp;
    }
    public override async Task<ExchangeOrder?> FindOrderAsync(string symbol,string clientOrderId,CancellationToken ct){var text=ClientText(clientOrderId);try{using var d=await Private(HttpMethod.Get,$"/futures/usdt/orders/{text}",null,null,ct);var mapped=await MapOrder(d.RootElement,false,ct);return mapped with{ClientOrderId=clientOrderId};}catch(InvalidOperationException ex)when(ex.Message.Contains("ORDER_NOT_FOUND",StringComparison.OrdinalIgnoreCase)){return null;}}
    public override async Task CancelOrderAsync(string symbol,string orderId,CancellationToken ct){var protection=_protectionIds.TryRemove(orderId,out _);using var response=await Private(HttpMethod.Delete,protection?$"/futures/usdt/price_orders/{orderId}":$"/futures/usdt/orders/{orderId}",null,null,ct);}

    private async Task<IReadOnlyList<CandleEvidence>> Candles(string symbol,string interval,int limit,long? from,long? to,CancellationToken ct){var q=new Dictionary<string,string?>{{"contract",Symbols.ToNative(symbol)},{"interval",interval},{"limit",Math.Clamp(limit,1,2000).ToString()},{"from",from?.ToString()},{"to",to?.ToString()}};using var d=await Public(HttpMethod.Get,"/futures/usdt/candlesticks",q,ct);var multiplier=await Multiplier(Symbols.ToNative(symbol),ct);return d.RootElement.EnumerateArray().Select(x=>new CandleEvidence(DateTimeOffset.FromUnixTimeSeconds((long)Dec(x,"t")).UtcDateTime,Dec(x,"o"),Dec(x,"h"),Dec(x,"l"),Dec(x,"c"),Dec(x,"v")*multiplier,Dec(x,"sum"),0,0)).OrderBy(x=>x.OpenTime).ToArray();}
    private async Task<ExchangeOrder> Place(string symbol,PositionSide side,decimal quantity,decimal price,string clientOrderId,bool reduceOnly,CancellationToken ct){var canonical=Symbols.ToCanonical(symbol);var native=Symbols.ToNative(canonical);var multiplier=await Multiplier(native,ct);var contracts=Math.Max(1,Math.Floor(quantity/multiplier));var direction=side==PositionSide.Long?1m:-1m;if(reduceOnly)direction=-direction;var body=new Dictionary<string,object?>{{"contract",native},{"size",F(contracts*direction)},{"price",price>0?F(price):"0"},{"tif",price>0?"gtc":"ioc"},{"text",ClientText(clientOrderId)},{"reduce_only",reduceOnly},{"is_dual_mode",true},{"pos_margin_mode",_isolated.GetValueOrDefault(canonical,true)?"isolated":"cross"}};using var d=await Private(HttpMethod.Post,"/futures/usdt/orders",null,body,ct);var mapped=await MapOrder(d.RootElement,false,ct);return mapped with{ClientOrderId=clientOrderId,PositionSide=side};}
    private async Task<ExchangeOrder> PlaceTrigger(string symbol,PositionSide side,decimal price,int rule,string clientId,bool isolated,CancellationToken ct){var orderType=side==PositionSide.Long?"close-long-order":"close-short-order";var body=new Dictionary<string,object?>{{"initial",new Dictionary<string,object?>{{"contract",Symbols.ToNative(symbol)},{"size","0"},{"price","0"},{"text",ClientText(clientId)},{"reduce_only",true}}},{"trigger",new Dictionary<string,object?>{{"strategy_type",0},{"price_type",1},{"price",F(price)},{"rule",rule},{"expiration",86400*30}}},{"order_type",orderType},{"pos_margin_mode",isolated?"isolated":"cross"}};using var d=await Private(HttpMethod.Post,"/futures/usdt/price_orders",null,body,ct);var id=Str(d.RootElement,"id_string");if(id.Length==0)id=Str(d.RootElement,"id");_protectionIds[id]=0;return new(symbol,id,clientId,"NEW",0,0,"TRIGGER",side,true,DateTime.UtcNow);}
    private async Task<ExchangeOrder> MapOrder(JsonElement x,bool protection,CancellationToken ct){var native=Str(x,"contract");var multiplier=await Multiplier(native,ct);var size=Dec(x,"size");var left=Dec(x,"left");var side=size<0?PositionSide.Short:PositionSide.Long;var status=NormalizeOrderStatus(Str(x,"status"),Str(x,"finish_as"),size,left);var id=Str(x,"id_string");if(id.Length==0)id=Str(x,"id");return new(Symbols.ToCanonical(native),id,Str(x,"text"),status,(Math.Abs(size)-Math.Abs(left))*multiplier,Dec(x,"fill_price")>0?Dec(x,"fill_price"):Dec(x,"price"),protection?"TRIGGER":Dec(x,"price")==0?"MARKET":"LIMIT",side,protection,Seconds(Str(x,"update_time") is {Length:>0}t?t:Str(x,"create_time")));}
    private async Task<ExchangeOrder> MapProtection(JsonElement x,CancellationToken ct){var initial=x.GetProperty("initial");var native=Str(initial,"contract");_ =await Multiplier(native,ct);var id=Str(x,"id_string");if(id.Length==0)id=Str(x,"id");_protectionIds[id]=0;var side=Str(x,"order_type").Contains("short",StringComparison.OrdinalIgnoreCase)?PositionSide.Short:PositionSide.Long;return new(Symbols.ToCanonical(native),id,Str(initial,"text"),NormalizeProtectionStatus(Str(x,"status")),0,0,"TRIGGER",side,true,Seconds(Str(x,"create_time")));}
    private async Task<decimal> Multiplier(string native,CancellationToken ct){if(_multipliers.TryGetValue(native,out var value)&&value>0)return value;using var d=await Public(HttpMethod.Get,$"/futures/usdt/contracts/{native}",null,ct);value=Dec(d.RootElement,"quanto_multiplier");if(value<=0)throw new InvalidOperationException($"Gate contract multiplier is invalid for {native}");_multipliers[native]=value;return value;}
    private async Task<JsonDocument> Public(HttpMethod method,string path,IReadOnlyDictionary<string,string?>? query,CancellationToken ct){var q=query is null?"":CanonicalQuery(query);var apiPath=_apiPrefix+path;var target=q.Length==0?apiPath:$"{apiPath}?{q}";return await SendAsync(()=>JsonRequest(method,target),Error,ct);}
    private async Task<JsonDocument> Private(HttpMethod method,string path,IReadOnlyDictionary<string,string?>? query,object? body,CancellationToken ct){var q=query is null?"":CanonicalQuery(query);var apiPath=_apiPrefix+path;var target=q.Length==0?apiPath:$"{apiPath}?{q}";var json=body is null?"":JsonSerializer.Serialize(body);return await SendAsync(()=>{var timestamp=DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture);var signature=ComputeSignature(_secret,method.Method,apiPath,q,json,timestamp);var request=JsonRequest(method,target,json.Length==0?null:json);AddUniqueHeader(request,"KEY",_key);AddUniqueHeader(request,"Timestamp",timestamp);AddUniqueHeader(request,"SIGN",signature);AddUniqueHeader(request,"X-Gate-Size-Decimal","1");return request;},Error,ct);}
    private static string? Error(JsonElement root)=>root.ValueKind==JsonValueKind.Object&&root.TryGetProperty("label",out var label)?$"{label.GetString()} {Str(root,"message")}":null;
    private static string ClientText(string value)=>"t-"+Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant()[..24];
    private static DateTime Seconds(string value)=>long.TryParse(value.Split('.')[0],out var seconds)&&seconds>0?DateTimeOffset.FromUnixTimeSeconds(seconds).UtcDateTime:DateTime.UtcNow;
    private static ExchangeConnectionProfile NormalizeProfile(ExchangeConnectionProfile profile){profile.Endpoint=profile.Endpoint.TrimEnd('/');if(profile.Endpoint.EndsWith("/api/v4",StringComparison.OrdinalIgnoreCase))profile.Endpoint=profile.Endpoint[..^7];return profile;}
    internal static string NormalizeOrderStatus(string status,string finishAs,decimal size,decimal left)=>status.ToLowerInvariant() switch{"open"=>left<Math.Abs(size)?"PARTIALLY_FILLED":"NEW","finished"=>finishAs.ToLowerInvariant() switch{"filled"=>"FILLED","cancelled"=>"CANCELED","rejected"=>"REJECTED",_=>"UNKNOWN"},_=>"UNKNOWN"};
    internal static string NormalizeProtectionStatus(string status)=>status.ToLowerInvariant() switch{"open"=>"NEW","cancelled" or "canceled"=>"CANCELED","expired"=>"EXPIRED","rejected"=>"REJECTED",_=>"UNKNOWN"};
    internal static AccountSnapshot ParseAccountSnapshot(JsonElement value,DateTime observedAtUtc){if(value.ValueKind!=JsonValueKind.Object||!TryDecimal(value,"total",out var total)||!TryDecimal(value,"available",out var available)||total<0||available<0)throw new InvalidOperationException("Gate account payload is incomplete or invalid.");return new(total,available,total,observedAtUtc);}
    private static bool TryDecimal(JsonElement value,string name,out decimal result){result=0;return value.TryGetProperty(name,out var property)&&decimal.TryParse(property.ValueKind==JsonValueKind.String?property.GetString():property.GetRawText(),NumberStyles.Any,CultureInfo.InvariantCulture,out result);}
    internal static bool IsServerTimeWithinReceiveWindow(DateTime serverUtc,DateTime localUtc)=>serverUtc!=default&&Math.Abs((localUtc-serverUtc).TotalSeconds)<=5;
    internal static IReadOnlyList<ExchangeOrder> MergeOrderPages(IEnumerable<IEnumerable<ExchangeOrder>> pages)=>MergeLatest(pages);
    private static IReadOnlyList<ExchangeOrder> MergeLatest(IEnumerable<IEnumerable<ExchangeOrder>> pages){var identified=new Dictionary<string,ExchangeOrder>(StringComparer.OrdinalIgnoreCase);var anonymous=new List<ExchangeOrder>();foreach(var order in pages.SelectMany(x=>x)){var key=!string.IsNullOrWhiteSpace(order.OrderId)?"id:"+order.OrderId:!string.IsNullOrWhiteSpace(order.ClientOrderId)?"client:"+order.ClientOrderId:null;if(key is null){anonymous.Add(order);continue;}if(!identified.TryGetValue(key,out var current)||order.UpdatedAt>=current.UpdatedAt)identified[key]=order;}return identified.Values.Concat(anonymous).OrderBy(x=>x.UpdatedAt).ToArray();}
    internal static bool IsOfficialTestnetEndpoint(string endpoint)=>ProviderEndpointPolicy.IsOfficialHttpsOrigin(endpoint,"api-testnet.gateapi.io");
    internal static string ComputeSignature(byte[] secret,string method,string apiPath,string query,string body,string timestamp){ValidateSigningInput(secret,method,apiPath,query,timestamp);var bodyHash=Convert.ToHexString(SHA512.HashData(Encoding.UTF8.GetBytes(body))).ToLowerInvariant();var signText=$"{method.ToUpperInvariant()}\n{apiPath}\n{query}\n{bodyHash}\n{timestamp}";return Convert.ToHexString(HMACSHA512.HashData(secret,Encoding.UTF8.GetBytes(signText))).ToLowerInvariant();}
    internal static string CanonicalQuery(IEnumerable<KeyValuePair<string,string?>> values){var materialized=values.Where(x=>x.Value is not null).ToArray();if(materialized.Any(x=>string.IsNullOrWhiteSpace(x.Key))||materialized.GroupBy(x=>x.Key,StringComparer.Ordinal).Any(x=>x.Count()>1))throw new InvalidOperationException("Gate query contains an empty or duplicate parameter.");return string.Join("&",materialized.OrderBy(x=>x.Key,StringComparer.Ordinal).Select(x=>$"{Uri.EscapeDataString(x.Key)}={Uri.EscapeDataString(x.Value!)}"));}
    internal static bool IsTimestampWithinReceiveWindow(string timestamp,DateTimeOffset now){return long.TryParse(timestamp,NumberStyles.None,CultureInfo.InvariantCulture,out var seconds)&&Math.Abs((now-DateTimeOffset.FromUnixTimeSeconds(seconds)).TotalSeconds)<=5;}
    internal static void AddUniqueHeader(HttpRequestMessage request,string name,string value){if(request.Headers.Contains(name))throw new InvalidOperationException($"Duplicate Gate header '{name}' is not allowed.");request.Headers.Add(name,value);}
    private static void ValidateSigningInput(byte[] secret,string method,string path,string query,string timestamp){var normalized=method.ToUpperInvariant();if(secret.Length==0||normalized is not ("GET" or "POST" or "DELETE")||!path.StartsWith("/api/v4/",StringComparison.Ordinal)||path.Contains('?')||path.Any(char.IsWhiteSpace)||query.StartsWith('?')||!long.TryParse(timestamp,NumberStyles.None,CultureInfo.InvariantCulture,out _))throw new InvalidOperationException("Gate signing input is invalid.");}
}
